export const commonSkillMap = [
  {
    jobID: '000',
    skillID: '0000190',
    skillName: '연합의 의지',
    skillDesc: '연합의 의지에 따라 강한 힘을 발휘한다.',
    maxLevel: '1',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '000',
    skillID: '0000012',
    skillName: '정령의 축복',
    skillDesc: '다른 캐릭터를 레벨 10이상 육성하면 스킬포인트 1이 증가한다. 단, 정령의 축복과 여제의 축복중 좋은 효과로 발동된다.',
    maxLevel: '20',
    invisible: 'False',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '000',
    skillID: '0000073',
    skillName: '여제의 축복',
    skillDesc:
      '다른 시그너스 캐릭터와 미하일 캐릭터를 레벨 5이상 육성하면 스킬포인트 1이 증가한다. 단, 정령의 축복과 여제의 축복중 높은 효과로 발동된다.\\r\\n다른 시그너스, 미하일 캐릭터의 고귀한 정신에 의해 마스터 레벨이 최대 30까지 확장될 수 있다. ',
    maxLevel: '30',
    invisible: 'False',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '000',
    skillID: '0001005',
    skillName: '영웅의 메아리',
    skillDesc: '[마스터 레벨 : 1]\\n주변 모든 캐릭터의 공격력과 마력을 증가시킨다.',
    maxLevel: '1',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '6000',
    skillID: '60001005',
    skillName: '익스클루시브 스펠',
    skillDesc: '[마스터 레벨 : 1]\\n주변 모든 캐릭터의 공격력과 마력을 증가시킨다.',
    maxLevel: '1',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '10000',
    skillID: '100001005',
    skillName: '인탠시브 타임',
    skillDesc: '초월자의 힘으로 주변 모든 캐릭터의 공격력과 마력을 증가시킨다.',
    maxLevel: '1',
    invisible: 'False',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '200',
  },
  {
    jobID: '112',
    skillID: '1121011',
    skillName: '용사의 의지',
    skillDesc:
      '정신을 집중하여 상태 이상으로부터 벗어난다. 사용 후 3초 동안 상태 이상 면역. 단, 일부 상태 이상 효과에는 적용되지 않고 컴뱃 오더스가 적용되지 않는다.\\n용사의 의지는 다른 스킬 사용 중 사용 가능하다.',
    maxLevel: '5',
    invisible: 'False',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '3122',
    skillID: '31221015',
    skillName: '데몬즈 윌',
    skillDesc:
      '정신을 집중하여 상태 이상으로부터 벗어난다. 사용 후 3초 동안 상태 이상 면역. 단, 일부 상태 이상 효과에는 적용되지 않고 컴뱃 오더스가 적용되지 않는다.\\n데몬즈 윌은 다른 스킬 사용 중 사용 가능하다.',
    maxLevel: '1',
    invisible: 'False',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '1112',
    skillID: '11121015',
    skillName: '시그너스 기사단의 의지',
    skillDesc:
      '정신을 집중하여 상태 이상으로부터 벗어난다. 사용 후 3초 동안 상태 이상 면역. 단, 일부 상태 이상 효과에는 적용되지 않고 컴뱃 오더스가 적용되지 않는다.\\n시그너스 기사단의 의지는 다른 스킬 사용 중 사용 가능하다.',
    maxLevel: '1',
    invisible: 'False',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '6112',
    skillID: '61121015',
    skillName: '노바 용사의 의지',
    skillDesc:
      '정신을 집중하여 상태 이상으로부터 벗어난다. 사용 후 3초 동안 상태 이상 면역. 단, 일부 상태 이상 효과에는 적용되지 않고 컴뱃 오더스가 적용되지 않는다.\\n노바 용사의 의지는 다른 스킬 사용 중 사용 가능하다.',
    maxLevel: '5',
    invisible: 'False',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '15112',
    skillID: '151121006',
    skillName: '레프 용사의 의지',
    skillDesc:
      '정신을 집중하여 상태 이상으로부터 벗어난다. 사용 후 3초 동안 상태 이상 면역. 단, 일부 상태 이상 효과에는 적용되지 않고 컴뱃 오더스가 적용되지 않는다.\\n레프 용사의 의지는 다른 스킬 사용 중 사용 가능하다.',
    maxLevel: '5',
    invisible: 'False',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '16212',
    skillID: '162121024',
    skillName: '아니마 용사의 의지',
    skillDesc:
      '정신을 집중하여 상태 이상으로부터 벗어난다. 사용 후 3초 동안 상태 이상 면역. 단, 일부 상태 이상 효과에는 적용되지 않고 컴뱃 오더스가 적용되지 않는다.\\n아니마 용사의 의지는 다른 스킬 사용 중 사용 가능하다.',
    maxLevel: '5',
    invisible: 'False',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '10000',
    skillID: '100001284',
    skillName: '초월자의 의지',
    skillDesc:
      '정신을 집중하여 상태 이상으로부터 벗어난다. 사용 후 3초 동안 상태 이상 면역. 단, 일부 상태 이상 효과에는 적용되지 않고 컴뱃 오더스가 적용되지 않는다.\\n초월자의 의지는 다른 스킬 사용 중 사용 가능하다.',
    maxLevel: '1',
    invisible: 'False',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '140',
  },
  {
    jobID: '14212',
    skillID: '142121005',
    skillName: '정신 정화',
    skillDesc:
      '정신을 정화하여 상태 이상으로부터 벗어난다. 사용 후 3초 동안 상태 이상 면역. 단, 일부 상태 이상 효과에는 적용되지 않고 컴뱃 오더스가 적용되지 않는다.\\n정신정화는 다른 스킬 사용 중 사용 가능하다. 추가로 상태 이상 내성이 영구히 증가한다.',
    maxLevel: '5',
    invisible: 'False',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '112',
    skillID: '1121000',
    skillName: '메이플 용사',
    skillDesc: '메이플 월드의 여신의 가호로 인해 자신의 모든 능력치가 일정 퍼센트만큼 증가한다. 스킬을 사용하면 메이플 월드의 여신이 잠시 현신한다.',
    maxLevel: '30',
    invisible: 'False',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '3122',
    skillID: '31221008',
    skillName: '메이플 용사',
    skillDesc: '마스테리아의 여신의 가호로 인해 자신의 모든 능력치가 일정 퍼센트만큼 증가한다. 스킬을 사용하면 마스테리아의 여신이 잠시 현신한다.',
    maxLevel: '30',
    invisible: 'False',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '1112',
    skillID: '11121000',
    skillName: '시그너스 나이츠',
    skillDesc: '각성한 여제의 축복으로 인해 자신의 모든 능력치가 일정 퍼센트만큼 증가한다. 스킬을 사용하면 각성한 여제가 잠시 현신한다.',
    maxLevel: '30',
    invisible: 'False',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '6112',
    skillID: '61121014',
    skillName: '노바의 용사',
    skillDesc: '그란디스 여신의 가호로 인해 자신의 모든 능력치가 일정 퍼센트만큼 증가한다. 스킬을 사용하면 그란디스의 여신이 잠시 현신한다.',
    maxLevel: '30',
    invisible: 'False',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '15112',
    skillID: '151121005',
    skillName: '레프의 용사',
    skillDesc: '레프의 잠재된 힘으로 자신의 모든 능력치가 일정 퍼센트만큼 증가한다. 스킬을 사용하면 레프의 문양이 생성된다.',
    maxLevel: '30',
    invisible: 'False',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '16112',
    skillID: '161121009',
    skillName: '아니마 용사',
    skillDesc: '그란디스 여신의 가호로 인해 자신의 모든 능력치가 일정 퍼센트만큼 증가한다. 스킬을 사용하면 그란디스의 여신이 잠시 현신한다.',
    maxLevel: '30',
    invisible: 'False',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '10000',
    skillID: '100001268',
    skillName: '륀느의 가호',
    skillDesc: '륀느 여신의 가호로 인해 자신의 모든 능력치가 일정 퍼센트만큼 증가한다. 스킬을 사용하면 륀느 여신이 잠시 현신한다.',
    maxLevel: '1',
    invisible: 'False',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '14212',
    skillID: '142121004',
    skillName: '이계의 용사',
    skillDesc: '이계의 여신의 가호로 인해 자신의 모든 능력치가 일정 퍼센트만큼 증가한다. 스킬을 사용하면 이계의 여신이 잠시 현신한다.',
    maxLevel: '30',
    invisible: 'False',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
];

export const rawCommonSkillBaseMap = {
  trueAllClassPassive: {
    kind: 'trueAllClassPassive',
    desc: '모든 직업에 동일하게 존재하는 진짜 전체 공통 패시브 스킬',
    skills: ['연합의 의지', '정령의 축복', '여제의 축복'],
  },
  echo: {
    kind: 'activeBuff',
    desc: '전직업 공통 공격력/마력 증가 버프. 소속군에 따라 이름만 다르다.',
    maxLevel: 1,
    isCombatOrders: false,
    variants: {
      '영웅의 메아리': {
        lineages: ['adventurer', 'heroes', 'demon', 'resistance', 'friendsWorld'],
      },
      '익스클루시브 스펠': {
        lineages: ['nova', 'lef', 'anima'],
      },
      '인탠시브 타임': {
        lineages: ['transcendent'],
        override: {
          reqLevel: 200,
        },
      },
    },
  },
  mapleHero: {
    kind: 'activeEffectPassiveStat',
    desc: 'AP로 올린 주스탯을 증가시키는 용사류 스킬. 대부분 maxLevel 30이며 컴뱃 오더스로 31레벨 이상 확장 가능하다.',
    maxLevel: 30,
    isCombatOrders: true,
    stat: 'apStatRate',
    levelScaling: {
      level30: 15,
      level31: 16,
    },
    variants: {
      '메이플 용사': {
        lineages: ['adventurer', 'resistance', 'heroes', 'demon'],
      },
      '시그너스 나이츠': {
        lineages: ['cygnus'],
        classNames: ['미하일'],
      },
      '노바의 용사': {
        lineages: ['nova'],
      },
      '레프의 용사': {
        lineages: ['lef'],
      },
      '아니마 용사': {
        lineages: ['anima'],
      },
      '이계의 용사': {
        lineages: ['friendsWorld'],
      },
      '륀느의 가호': {
        lineages: ['transcendent'],
        override: {
          maxLevel: 1,
          isCombatOrders: false,
          fixedValue: 15,
          reason: '제로 0차 스킬이라 컴뱃 오더스와 레벨 상한 초과가 적용되지 않는다.',
        },
      },
    },
    jobOverrides: {
      '3122': {
        skillName: '메이플 용사',
        classNames: ['데몬어벤져'],
        addPassiveStats: [
          {
            stat: 'maxHpRate',
            desc: '데몬어벤져 전용 메이플 용사는 패시브 HP 증가 옵션을 별도로 가진다.',
          },
        ],
      },
    },
  },
  will: {
    kind: 'activeUtility',
    desc: '상태 이상 해제/일시 면역 의지류 스킬. 이름만 다르고 효과가 같다.',
    maxLevel: 5,
    isCombatOrders: false,
    variants: {
      '용사의 의지': {
        lineages: ['adventurer', 'heroes', 'resistance'],
      },
      '데몬즈 윌': {
        lineages: ['demon'],
      },
      '시그너스 기사단의 의지': {
        lineages: ['cygnus'],
        classNames: ['미하일'],
      },
      '노바 용사의 의지': {
        lineages: ['nova'],
      },
      '레프 용사의 의지': {
        lineages: ['lef'],
      },
      '아니마 용사의 의지': {
        lineages: ['anima'],
      },
      '정신 정화': {
        lineages: ['friendsWorld'],
        override: {
          addPassiveStats: [
            {
              stat: 'statusResistance',
              desc: '키네시스 의지류는 상태 이상 내성 영구 증가 설명이 붙어 있다.',
            },
          ],
        },
      },
      '초월자의 의지': {
        lineages: ['transcendent'],
        override: {
          maxLevel: 1,
          reqLevel: 140,
          reason: '제로 전용 0차 스킬이며 효과는 의지류와 같지만 maxLevel과 필요 레벨이 다르다.',
        },
      },
    },
  },
} as const;

export const rawCommonSkillAliasMap = {
  '연합의 의지': 'trueAllClassPassive',
  '정령의 축복': 'trueAllClassPassive',
  '여제의 축복': 'trueAllClassPassive',

  '영웅의 메아리': 'echo',
  '익스클루시브 스펠': 'echo',
  '인탠시브 타임': 'echo',

  '메이플 용사': 'mapleHero',
  '시그너스 나이츠': 'mapleHero',
  '노바의 용사': 'mapleHero',
  '레프의 용사': 'mapleHero',
  '아니마 용사': 'mapleHero',
  '륀느의 가호': 'mapleHero',
  '이계의 용사': 'mapleHero',

  '용사의 의지': 'will',
  '데몬즈 윌': 'will',
  '시그너스 기사단의 의지': 'will',
  '노바 용사의 의지': 'will',
  '레프 용사의 의지': 'will',
  '아니마 용사의 의지': 'will',
  '초월자의 의지': 'will',
  '정신 정화': 'will',
} as const satisfies Record<string, keyof typeof rawCommonSkillBaseMap>;
