export const linkSkillMap = [
  {
    jobID: '000',
    skillID: '0000252',
    skillName: '인빈서블 빌리프(히어로)',
    skillDesc:
      '꺾이지 않는 신념을 가져 위기 상황일 때 HP를 대량으로 회복한다.\\n마을 및 특정한 회복 불가 상황에서는 발동되지 않고 재사용 대기시간 초기화, 버프 지속시간 증가, 회복 스킬 효율 증가 및 감소의 효과를 받지 않는다.\\n월드 내 서로 다른 모험가 전사 직업군이 존재할 경우 한 캐릭터에 최대 3번 중복해서 링크 스킬 지급이 가능하다.\\n\\n#c7레벨 : 모험가 전사 직업군은 영구적으로 데미지 증가',
    maxLevel: '9',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '000',
    skillID: '0000253',
    skillName: '인빈서블 빌리프(팔라딘)',
    skillDesc:
      '꺾이지 않는 신념을 가져 위기 상황일 때 HP를 대량으로 회복한다.\\n마을 및 특정한 회복 불가 상황에서는 발동되지 않고 재사용 대기시간 초기화, 버프 지속시간 증가, 회복 스킬 효율 증가 및 감소의 효과를 받지 않는다.\\n월드 내 서로 다른 모험가 전사 직업군이 존재할 경우 한 캐릭터에 최대 3번 중복해서 링크 스킬 지급이 가능하다.\\n\\n#c7레벨 : 모험가 전사 직업군은 영구적으로 데미지 증가',
    maxLevel: '9',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '000',
    skillID: '0000254',
    skillName: '인빈서블 빌리프(다크나이트)',
    skillDesc:
      '꺾이지 않는 신념을 가져 위기 상황일 때 HP를 대량으로 회복한다.\\n마을 및 특정한 회복 불가 상황에서는 발동되지 않고 재사용 대기시간 초기화, 버프 지속시간 증가, 회복 스킬 효율 증가 및 감소의 효과를 받지 않는다.\\n월드 내 서로 다른 모험가 전사 직업군이 존재할 경우 한 캐릭터에 최대 3번 중복해서 링크 스킬 지급이 가능하다.\\n\\n#c7레벨 : 모험가 전사 직업군은 영구적으로 데미지 증가',
    maxLevel: '9',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '000',
    skillID: '0000255',
    skillName: '임피리컬 널리지(아크메이지 불, 독)',
    skillDesc:
      '실전적인 탐구를 통해 약점을 파악하여 해당 적에 대한 데미지와 방어율 무시를 점차 증가시킨다.\\n월드 내 서로 다른 모험가 마법사 직업군이 존재할 경우 한 캐릭터에 최대 3번 중복해서 링크 스킬 지급이 가능하다.',
    maxLevel: '9',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '000',
    skillID: '0000256',
    skillName: '임피리컬 널리지(아크메이지 썬, 콜)',
    skillDesc:
      '실전적인 탐구를 통해 약점을 파악하여 해당 적에 대한 데미지와 방어율 무시를 점차 증가시킨다.\\n월드 내 서로 다른 모험가 마법사 직업군이 존재할 경우 한 캐릭터에 최대 3번 중복해서 링크 스킬 지급이 가능하다.',
    maxLevel: '9',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '000',
    skillID: '0000257',
    skillName: '임피리컬 널리지(비숍)',
    skillDesc:
      '실전적인 탐구를 통해 약점을 파악하여 해당 적에 대한 데미지와 방어율 무시를 점차 증가시킨다.\\n월드 내 서로 다른 모험가 마법사 직업군이 존재할 경우 한 캐릭터에 최대 3번 중복해서 링크 스킬 지급이 가능하다.',
    maxLevel: '9',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '000',
    skillID: '0000258',
    skillName: '어드벤쳐러 큐리어스(보우마스터)',
    skillDesc:
      '특유의 호기심을 발휘해 몬스터 컬렉션 등록 확률과 크리티컬 확률을 증가시킨다.\\n몬스터 컬렉션 등록 확률은 기존 확률에 곱적용으로 적용된다.\\n월드 내 서로 다른 모험가 궁수 직업군이 존재할 경우 한 캐릭터에 최대 3번 중복해서 링크 스킬 지급이 가능하다.\\n\\n#c7레벨 : 모험가 궁수 직업군은 영구적으로 데미지 증가',
    maxLevel: '9',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '000',
    skillID: '0000259',
    skillName: '어드벤쳐러 큐리어스(신궁)',
    skillDesc:
      '특유의 호기심을 발휘해 몬스터 컬렉션 등록 확률과 크리티컬 확률을 증가시킨다.\\n몬스터 컬렉션 등록 확률은 기존 확률에 곱적용으로 적용된다.\\n월드 내 서로 다른 모험가 궁수 직업군이 존재할 경우 한 캐릭터에 최대 3번 중복해서 링크 스킬 지급이 가능하다.\\n\\n#c7레벨 : 모험가 궁수 직업군은 영구적으로 데미지 증가',
    maxLevel: '9',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '000',
    skillID: '0000260',
    skillName: '어드벤쳐러 큐리어스(패스파인더)',
    skillDesc:
      '특유의 호기심을 발휘해 몬스터 컬렉션 등록 확률과 크리티컬 확률을 증가시킨다.\\n몬스터 컬렉션 등록 확률은 기존 확률에 곱적용으로 적용된다.\\n월드 내 서로 다른 모험가 궁수 직업군이 존재할 경우 한 캐릭터에 최대 3번 중복해서 링크 스킬 지급이 가능하다.\\n\\n#c7레벨 : 모험가 궁수 직업군은 영구적으로 데미지 증가',
    maxLevel: '9',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '000',
    skillID: '0000261',
    skillName: '시프 커닝(나이트로드)',
    skillDesc:
      '도적 특유의 교활함을 발휘해 적을 약화시키면 데미지가 증가한다.\\n재사용 대기시간 초기화, 버프 지속시간 증가의 효과를 받지 않는다.\\n월드 내 서로 다른 모험가 도적 직업군이 존재할 경우 한 캐릭터에 최대 3번 중복해서 링크 스킬 지급이 가능하다.',
    maxLevel: '9',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '000',
    skillID: '0000262',
    skillName: '시프 커닝(섀도어)',
    skillDesc:
      '도적 특유의 교활함을 발휘해 적을 약화시키면 데미지가 증가한다.\\n재사용 대기시간 초기화, 버프 지속시간 증가의 효과를 받지 않는다.\\n월드 내 서로 다른 모험가 도적 직업군이 존재할 경우 한 캐릭터에 최대 3번 중복해서 링크 스킬 지급이 가능하다.',
    maxLevel: '9',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '000',
    skillID: '0000263',
    skillName: '시프 커닝(듀얼블레이드)',
    skillDesc:
      '도적 특유의 교활함을 발휘해 적을 약화시키면 데미지가 증가한다.\\n재사용 대기시간 초기화, 버프 지속시간 증가의 효과를 받지 않는다.\\n월드 내 서로 다른 모험가 도적 직업군이 존재할 경우 한 캐릭터에 최대 3번 중복해서 링크 스킬 지급이 가능하다.',
    maxLevel: '9',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '000',
    skillID: '0000264',
    skillName: '파이렛 블레스(바이퍼)',
    skillDesc:
      '해적 특유의 강인함을 익혀 각종 스탯이 증가하고 피격 데미지가 감소된다.\\n월드 내 서로 다른 모험가 해적 직업군이 존재할 경우 한 캐릭터에 최대 3번 중복해서 링크 스킬 지급이 가능하다.\\n스킬을 사용하면 무기, 보조 무기, 아케인심볼, 어센틱심볼, 펫장비를 제외한 부위에 장착된 장비의 힘과 민첩이 바뀌어 적용된다.\\n\\n#c7레벨 : 모험가 해적 직업군은 더 많은 스탯 증가',
    maxLevel: '9',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '000',
    skillID: '0000265',
    skillName: '파이렛 블레스(캡틴)',
    skillDesc:
      '해적 특유의 강인함을 익혀 각종 스탯이 증가하고 피격 데미지가 감소된다.\\n월드 내 서로 다른 모험가 해적 직업군이 존재할 경우 한 캐릭터에 최대 3번 중복해서 링크 스킬 지급이 가능하다.\\n스킬을 사용하면 무기, 보조 무기, 아케인심볼, 어센틱심볼, 펫장비를 제외한 부위에 장착된 장비의 힘과 민첩이 바뀌어 적용된다.\\n\\n#c7레벨 : 모험가 해적 직업군은 더 많은 스탯 증가',
    maxLevel: '9',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '000',
    skillID: '0000110',
    skillName: '파이렛 블레스(캐논슈터)',
    skillDesc:
      '해적 특유의 강인함을 익혀 각종 스탯이 증가하고 피격 데미지가 감소된다.\\n월드 내 서로 다른 모험가 해적 직업군이 존재할 경우 한 캐릭터에 최대 3번 중복해서 링크 스킬 지급이 가능하다.\\n스킬을 사용하면 무기, 보조 무기, 아케인심볼, 어센틱심볼, 펫장비를 제외한 부위에 장착된 장비의 힘과 민첩이 바뀌어 적용된다.\\n\\n#c7레벨 : 모험가 해적 직업군은 더 많은 스탯 증가',
    maxLevel: '9',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '1000',
    skillID: '10000255',
    skillName: '시그너스 블레스(전사)',
    skillDesc:
      '각성한 여제의 가호가 몸에 깃들어 적의 위협으로부터 벗어난다.\\n월드 내 서로 다른 시그너스 직업군이 존재할 경우 한 캐릭터에 최대 5번 중복해서 링크 스킬 지급이 가능하다.\\n\\n#c11레벨 : 시그너스 직업군은 더 많은 공격력, 마력 증가',
    maxLevel: '15',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '1000',
    skillID: '10000256',
    skillName: '시그너스 블레스(마법사)',
    skillDesc:
      '각성한 여제의 가호가 몸에 깃들어 적의 위협으로부터 벗어난다.\\n월드 내 서로 다른 시그너스 직업군이 존재할 경우 한 캐릭터에 최대 5번 중복해서 링크 스킬 지급이 가능하다.\\n\\n#c11레벨 : 시그너스 직업군은 더 많은 공격력, 마력 증가',
    maxLevel: '15',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '1000',
    skillID: '10000257',
    skillName: '시그너스 블레스(궁수)',
    skillDesc:
      '각성한 여제의 가호가 몸에 깃들어 적의 위협으로부터 벗어난다.\\n월드 내 서로 다른 시그너스 직업군이 존재할 경우 한 캐릭터에 최대 5번 중복해서 링크 스킬 지급이 가능하다.\\n\\n#c11레벨 : 시그너스 직업군은 더 많은 공격력, 마력 증가',
    maxLevel: '15',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '1000',
    skillID: '10000258',
    skillName: '시그너스 블레스(도적)',
    skillDesc:
      '각성한 여제의 가호가 몸에 깃들어 적의 위협으로부터 벗어난다.\\n월드 내 서로 다른 시그너스 직업군이 존재할 경우 한 캐릭터에 최대 5번 중복해서 링크 스킬 지급이 가능하다.\\n\\n#c11레벨 : 시그너스 직업군은 더 많은 공격력, 마력 증가',
    maxLevel: '15',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '1000',
    skillID: '10000259',
    skillName: '시그너스 블레스(해적)',
    skillDesc:
      '각성한 여제의 가호가 몸에 깃들어 적의 위협으로부터 벗어난다.\\n월드 내 서로 다른 시그너스 직업군이 존재할 경우 한 캐릭터에 최대 5번 중복해서 링크 스킬 지급이 가능하다.\\n\\n#c11레벨 : 시그너스 직업군은 더 많은 공격력, 마력 증가',
    maxLevel: '15',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '5000',
    skillID: '50001214',
    skillName: '빛의 수호',
    skillDesc:
      '빛의 수호를 받아 일정 시간 동안 적에게서 받는 피해를 방어하고 데미지가 증가한다. 링크 스킬로 사용 시 일정 시간 상태 이상 내성이 증가한다.\\n\\n#c3레벨 : 미하일은 영구적으로 데미지 증가#',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '2000',
    skillID: '20000297',
    skillName: '콤보킬 어드밴티지',
    skillDesc: '폴암의 정령 마하의 신비한 힘을 통해 콤보 플레이에 대한 축복을 받는다.\\n\\n#c3레벨 : 아란은 영구적으로 데미지 증가',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '2001',
    skillID: '20010294',
    skillName: '룬 퍼시스턴스',
    skillDesc: '룬의 마력을 증폭시켜 해방된 룬 힘의 지속시간을 증가 시킨다.\\n\\n#c3레벨 : 에반은 영구적으로 데미지 증가',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '2004',
    skillID: '20040218',
    skillName: '퍼미에이트',
    skillDesc: '무엇으로 가려도 스며드는 빛의 힘으로 적의 방어를 일정 부분 무시한다.\\n\\n#c3레벨 : 루미너스는 영구적으로 데미지 증가',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '2002',
    skillID: '20021110',
    skillName: '엘프의 축복',
    skillDesc: '고대 엘프의 축복으로 에우렐로 돌아갈 수 있고, 영구적으로 경험치 획득량이 증가한다.\\n\\n#c3레벨 : 메르세데스는 영구적으로 데미지가 증가',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '2003',
    skillID: '20030204',
    skillName: '데들리 인스팅트',
    skillDesc: '뛰어난 통찰력을 통해 적의 치명적인 약점을 찾아내는 본성을 가지고 있다.\\n\\n#c3레벨 : 팬텀은 영구적으로 데미지 증가',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '2005',
    skillID: '20050286',
    skillName: '구사 일생',
    skillDesc: '사망에 이르는 공격을 당했을 시, 일정 확률로 생존한다.\\n\\n#c3레벨 : 은월은 영구적으로 데미지 증가',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '3001',
    skillID: '30010241',
    skillName: '와일드 레이지',
    skillDesc: '분노로 인해 데미지가 증가한다.',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '3001',
    skillID: '30010112',
    skillName: '데몬스 퓨리',
    skillDesc: '대상이 보스 몬스터 일 경우, 내면에 잠재된 분노를 이끌어 내 더욱 강력한 데미지를 입히고 데몬 슬래시 사용 시 추가 포스를 흡수한다.',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '3000',
    skillID: '30000074',
    skillName: '스피릿 오브 프리덤(마법사)',
    skillDesc:
      '자유를 염원하는 레지스탕스가 가진 혼의 힘이다. 월드 내 서로 다른 레지스탕스 직업군이 존재할 경우 한 캐릭터에 최대 4번 중복해서 링크 스킬 지급이 가능하다.\\n\\n#c9레벨 : 블래스터, 배틀메이지, 와일드헌터, 메카닉은 영구적으로 데미지 증가',
    maxLevel: '12',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '3000',
    skillID: '30000075',
    skillName: '스피릿 오브 프리덤(궁수)',
    skillDesc:
      '자유를 염원하는 레지스탕스가 가진 혼의 힘이다. 월드 내 서로 다른 레지스탕스 직업군이 존재할 경우 한 캐릭터에 최대 4번 중복해서 링크 스킬 지급이 가능하다.\\n\\n#c9레벨 : 블래스터, 배틀메이지, 와일드헌터, 메카닉은 영구적으로 데미지 증가',
    maxLevel: '12',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '3000',
    skillID: '30000076',
    skillName: '스피릿 오브 프리덤(해적)',
    skillDesc:
      '자유를 염원하는 레지스탕스가 가진 혼의 힘이다. 월드 내 서로 다른 레지스탕스 직업군이 존재할 경우 한 캐릭터에 최대 4번 중복해서 링크 스킬 지급이 가능하다.\\n\\n#c9레벨 : 블래스터, 배틀메이지, 와일드헌터, 메카닉은 영구적으로 데미지 증가',
    maxLevel: '12',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '3000',
    skillID: '30000077',
    skillName: '스피릿 오브 프리덤(전사)',
    skillDesc:
      '자유를 염원하는 레지스탕스가 가진 혼의 힘이다. 월드 내 서로 다른 레지스탕스 직업군이 존재할 경우 한 캐릭터에 최대 4번 중복해서 링크 스킬 지급이 가능하다.\\n\\n#c9레벨 : 블래스터, 배틀메이지, 와일드헌터, 메카닉은 영구적으로 데미지 증가',
    maxLevel: '12',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '3002',
    skillID: '30020233',
    skillName: '하이브리드 로직',
    skillDesc: '하이브리드 로직 디자인을 적용하여 모든 능력치가 영구히 증가한다.',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '6000',
    skillID: '60000222',
    skillName: '아이언 윌',
    skillDesc: '강철의 의지를 가진 카이저는 추가 HP를 가지고 모프 게이지 단계에 따라 데미지가 증가한다. 링크 스킬로 사용 시 HP 증가만 적용된다.',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '6003',
    skillID: '60030241',
    skillName: '프라이어 프리퍼레이션',
    skillDesc: '적을 확실하게 처리하기 위한 사전 준비를 한다.',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '6002',
    skillID: '60020218',
    skillName: '인텐시브 인썰트',
    skillDesc: '자신보다 약한 적에겐 더 효과적인 공격을 가한다.',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '6001',
    skillID: '60011219',
    skillName: '소울 컨트랙트',
    skillDesc: '에스카다와의 계약을 통해 순간적으로 데미지를 극대화한다.\\n소울 컨트랙트는 다른 스킬 사용 중 사용 가능하다.',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '10000',
    skillID: '100000271',
    skillName: '륀느의 축복',
    skillDesc:
      '륀느 여신에게 축복을 받아 적에게 받는 데미지가 감소하며, 공격 시 방어율을 일정 부분 무시한다. \\n#c활성화 된 여신의 눈물을 획득할 때마다 스킬 효과가 강력해진다.#\\n\\n#c6레벨 : 제로는 영구적으로 데미지 증가',
    maxLevel: '6',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '14000',
    skillID: '140000292',
    skillName: '판단',
    skillDesc: '타고난 판단력으로 적에게 가능한 최고의 치명상을 입힌다.',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '15002',
    skillID: '150020241',
    skillName: '노블레스',
    skillDesc: '강력한 상대로부터 누군가를 지켜야 할 때 더 큰 힘을 발휘하는 숭고함을 가진다.',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '15000',
    skillID: '150000017',
    skillName: '전투의 흐름',
    skillDesc: '전투의 흐름이 끊기지 않게 유지한다.\\n일정 시간 내에 특정 거리를 이동 할 때 마다 데미지가 증가한다.\t\t',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '15003',
    skillID: '150030241',
    skillName: '이네이트 기프트',
    skillDesc:
      '사막의 축복을 받아 공격 시 짧은 시간 동안 HP와 MP를 회복한다. 추가로 영구적으로 데미지가 증가한다. 이네이트 기프트는 재사용 대기시간 초기화, 재사용 대기시간 감소, 버프 지속시간 증가의 효과를 받지 않는다.\\n\\n#c3레벨 : 칼리는 데미지가 추가로 증가',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '15001',
    skillID: '150010241',
    skillName: '무아',
    skillDesc: '자신을 잊어버릴 정도로 전투에 집중한다.\\n일정 시간 동안 전투 상태가 지속되면 데미지가 증가한다.',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '16002',
    skillID: '160020001',
    skillName: '강체',
    skillDesc: '심법 수련을 통해 신체를 단련하여 적의 공격 피해를 경감시킨다.\\n\\n#c3레벨 : 렌은 영구적으로 데미지 증가',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '16001',
    skillID: '160010001',
    skillName: '자연의 벗',
    skillDesc: '주변의 자연과 친구가 되어 도움을 받는다. 신비한 자연의 힘을 견디지 못하는 약한 몬스터에게는 더 큰 효과가 있다.\\n\\n#c3레벨 : 라라는 데미지가 추가로 증가',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
  {
    jobID: '16000',
    skillID: '160000001',
    skillName: '자신감',
    skillDesc:
      '강한 적에게도 위축되지 않는 자신감으로 적의 방어율을 일정 부분 무시하고 체력이 가득 찬 몬스터를 공격할 때 더 큰 피해를 입힌다.\\n\\n#c3레벨 : 호영은 영구적으로 데미지 증가',
    maxLevel: '3',
    invisible: 'True',
    hyper: '0',
    reqSkill: '',
    reqSkillLevel: '0',
    reqLevel: '0',
  },
];
