type ClassName = string;

type CreateGeneratedTaxonomyClassDetailSourceOptions = {
  allClassKeyMap: Record<string, string>;
  generatorKeys: readonly string[];
  generatorClassNames: Record<string, readonly string[]>;
};

function toClassKeyMap(classNames: readonly ClassName[], allClassKeyMap: Record<string, string>): Record<string, string> {
  return Object.fromEntries(classNames.map((className) => [className, allClassKeyMap[className] ?? className]));
}

function toPascalCase(value: string): string {
  return value
    .split(/[-_]/g)
    .filter(Boolean)
    .map((word) => `${word[0]?.toUpperCase() ?? ''}${word.slice(1)}`)
    .join('');
}

function stringifyConstObject(name: string, value: Record<string, string>): string {
  const entries = Object.entries(value)
    .map(([key, entryValue]) => `  ${JSON.stringify(key)}: ${JSON.stringify(entryValue)},`)
    .join('\n');

  return `export const ${name} = {\n${entries}\n} as const;`;
}

function createClassNameKeyMapBlock(namePrefix: string, classNames: readonly ClassName[], allClassKeyMap: Record<string, string>): string {
  const pascalName = toPascalCase(namePrefix);
  const keyMapName = `${namePrefix}ClassNameKeyMap`;
  const classNameType = `${pascalName}ClassName`;
  const classNameKeyType = `${pascalName}ClassNameKey`;
  const classNameKeysName = `${namePrefix}ClassNameKeys`;

  return [
    stringifyConstObject(keyMapName, toClassKeyMap(classNames, allClassKeyMap)),
    '',
    `export type ${classNameKeyType} = (typeof ${keyMapName})[${classNameType}];`,
    `export const ${classNameKeysName} = Object.values(${keyMapName}) as ${classNameKeyType}[];`,
  ].join('\n');
}

export function createGeneratedTaxonomyClassDetailSource({
  allClassKeyMap,
  generatorKeys,
  generatorClassNames,
}: CreateGeneratedTaxonomyClassDetailSourceOptions): string {
  const blocks: string[] = [
    '/* eslint-disable */',
    '// This file is generated by packages/bootstrap/src/scripts/generate-core-taxonomy.ts.',
    '',
  ];

  const classNameTypes: string[] = [];

  for (const generatorKey of generatorKeys) {
    const classNames = generatorClassNames[generatorKey];

    if (!classNames) {
      throw new Error(`Missing generator class names: ${generatorKey}`);
    }

    classNameTypes.push(`${toPascalCase(generatorKey)}ClassName`);
    blocks.push(createClassNameKeyMapBlock(generatorKey, classNames, allClassKeyMap), '');
  }

  blocks.splice(3, 0, `import type { ${classNameTypes.join(', ')} } from '../class';`, '');

  return `${blocks.join('\n')}\n`;
}
