const warriorJobsMap = {
  히어로: 'hero',
  다크나이트: 'dark_night',
  팔라딘: 'paladin',
  소울마스터: 'soul_master',
  미하일: 'mikhail',
  블래스터: 'blaster',
  데몬슬레이어: 'demon_slayer',
  데몬어벤져: 'demon_avenger',
  아란: 'aran',
  카이저: 'kaiser',
  아델: 'adele',
  렌: 'len',
  제로: 'zero',
};
