import fs from 'fs';
import path from 'path';
import { convertCase } from '@maple/utils';

const JOBS_PATH = path.resolve(__dirname, '../src/jobs');
const OUTPUT_PATH = path.resolve(__dirname, '../src/jobs/job.type.ts');

// 유틸: kebab-case → PascalCase
// const toPascal = (str: string) => str.replace(/(^\w|-\w)/g, (m) => m.replace('-', '').toUpperCase());

const jobCategories = fs.readdirSync(JOBS_PATH).filter((name) => {
  const full = path.join(JOBS_PATH, name);
  return fs.statSync(full).isDirectory();
});

let output = `// Auto-generated from scripts/generateJobTypes.ts\n\n`;

// JobCategory 타입
output += `export type JobCategory = ${jobCategories.map((j) => `"${j}"`).join(' | ')};\n\n`;

// 각 클래스 타입
for (const category of jobCategories) {
  const categoryPath = path.join(JOBS_PATH, category);
  const subDirs = fs.readdirSync(categoryPath).filter((name) => {
    const full = path.join(categoryPath, name);
    return fs.statSync(full).isDirectory();
  });

  const typeName = `${convertCase({ from: 'kebab', to: 'pascal', data: category })}Classes`;
  output += `export type ${typeName} = ${subDirs.map((s) => `"${s}"`).join(' | ')};\n`;
}

output += `\n`;

// ClassTypes 인터페이스
output += `export interface ClassTypes {\n`;

for (const category of jobCategories) {
  const mapFile = path.join(JOBS_PATH, category, `${category}-job.json`);
  if (!fs.existsSync(mapFile)) continue;

  const mapData = JSON.parse(fs.readFileSync(mapFile, 'utf-8')) as Record<string, string>;

  output += `  ${category}: {\n`;
  for (const [kor, eng] of Object.entries(mapData)) {
    output += `    "${kor}": "${eng}";\n`;
  }
  output += `  };\n`;
}

output += `}\n`;

// 파일 저장
fs.writeFileSync(OUTPUT_PATH, output, 'utf-8');

console.log(`✅ Generated: ${OUTPUT_PATH}`);

//
//
//
//

// import fs from 'fs';
// import { convertCase } from '@maple/utils';
// import path from 'path';
//
// const JOB_ROOT = path.resolve(__dirname, 'src', 'jobs');
//
// const jobCategories = fs
//   .readdirSync(JOB_ROOT, { withFileTypes: true })
//   .filter((dirent) => dirent.isDirectory())
//   .map((dirent) => dirent.name);
//
// let output = '';
//
// output += `// Auto-generated by generate-types.ts\n\n`;
// output += `type JobCategory = ${jobCategories.map((j) => `"${j}"`).join(' | ')};\n\n`;
