export const statMap = [
  'minStatAP',
  'maxStatAP',
  'damage',
  'bossDamage',
  'finalDamage',
  'ignoreDefense',
  'CRIRate',
  'CRIDamage',
  'statusResistance',
  'stance',
  'defense',
  'moveSpeed',
  'jumpPower',
  'starForce',
  'arcForce',
  'autForce',
  'STR',
  'DEX',
  'INT',
  'LUK',
  'HP',
  'MP',
  'apSTR',
  'apDEX',
  'apINT',
  'apLUK',
  'apHP',
  'apMP',
  'itemDropRate',
  'mesoDropRate',
  'buffDuration',
  'ATKSpeed',
  'mobDamage',
  'cooldownFlat',
  'cooldownRate',
  'cooldownIgnoreRate',
  'ignoreResist',
  'statusDamage',
  'weaponMastery',
  'addEXPGain',
  'PATK',
  'MATK',
  'combatPower',
  'summonDuration',
];

export const koreanToEnglishStatMap: Record<string, string> = {
  '최소 스탯공격력': 'minStatAP',
  '최대 스탯공격력': 'maxStatAP',
  데미지: 'damage',
  '보스 몬스터 데미지': 'bossDamage',
  '최종 데미지': 'finalDamage',
  '방어율 무시': 'ignoreDefense',
  '크리티컬 확률': 'CRIRate',
  '크리티컬 데미지': 'CRIDamage',
  '상태이상 내성': 'statusResistance',
  스탠스: 'stance',
  방어력: 'defense',
  이동속도: 'moveSpeed',
  점프력: 'jumpPower',
  스타포스: 'starForce',
  아케인포스: 'arcForce',
  어센틱포스: 'autForce',
  STR: 'STR',
  DEX: 'DEX',
  INT: 'INT',
  LUK: 'LUK',
  HP: 'HP',
  MP: 'MP',
  'AP 배분 STR': 'apSTR',
  'AP 배분 DEX': 'apDEX',
  'AP 배분 INT': 'apINT',
  'AP 배분 LUK': 'apLUK',
  'AP 배분 HP': 'apHP',
  'AP 배분 MP': 'apMP',
  '아이템 드롭률': 'itemDropRate',
  '메소 획득량': 'mesoDropRate',
  '버프 지속시간': 'buffDuration',
  '공격 속도': 'ATKSpeed',
  '일반 몬스터 데미지': 'mobDamage',
  '재사용 대기시간 감소 (초)': 'cooldownFlat',
  '재사용 대기시간 감소 (%)': 'cooldownRate',
  '재사용 대기시간 미적용': 'cooldownIgnoreRate',
  '속성 내성 무시': 'ignoreResist',
  '상태이상 추가 데미지': 'statusDamage',
  '무기 숙련도': 'weaponMastery',
  '추가 경험치 획득': 'addEXPGain',
  공격력: 'PATK',
  마력: 'MATK',
  전투력: 'combatPower',
  '소환수 지속시간 증가': 'summonDuration',
} as const;

export type statName_ko = keyof typeof koreanToEnglishStatMap;
export type statName_en = (typeof koreanToEnglishStatMap)[statName_ko];
