export const inputStatKeys = [
  'str',
  'dex',
  'int',
  'luk',
  'apStr',
  'apDex',
  'apInt',
  'apLuk',
  'strRate',
  'dexRate',
  'intRate',
  'lukRate',
  'levelStr',
  'levelDex',
  'levelInt',
  'levelLuk',
  'allStat',
  'allStatRate',
  'apStatRate',
  'apHp',
  'maxHp',
  'maxHpRate',
  'maxMp',
  'maxMpRate',
  'armor',
  'armorRate',
  'attackPower',
  'attackPowerRate',
  'weaponPureAttackPowerRate',
  'magicPower',
  'magicPowerRate',
  'damage',
  'normalDamage',
  'bossDamage',
  'finalDamage',
  'ignoreMonsterArmor',
  'cooldownSec',
  'cooldownRate',
  'cooldownIgnore',
  'weaponMastery',
  'buffDurationRate',
  'summonDurationRate',
  'expRate',
  'elementalResistanceRate',
  'elementalResistanceIgnore',
  'attackSpeed',
  'stance',
  'speed',
  'maxSpeed',
  'jump',
  'criticalRate',
  'criticalDamage',
  'statusResistance',
  'statusConditionAdditionalDamage',
  'starforce',
] as const;

export type InputStatKey = (typeof inputStatKeys)[number];

export const inputStatLabelMap: Record<InputStatKey, string> = {
  str: 'STR',
  dex: 'DEX',
  int: 'INT',
  luk: 'LUK',
  strRate: 'STR(%)',
  dexRate: 'DEX(%)',
  intRate: 'INT(%)',
  lukRate: 'LUK(%)',
  levelStr: '캐릭터 9레벨 당 STR',
  levelDex: '캐릭터 9레벨 당 DEX',
  levelInt: '캐릭터 9레벨 당 INT',
  levelLuk: '캐릭터 9레벨 당 LUK',
  allStat: '올스탯',
  allStatRate: '올스탯(%)',
  apStatRate: 'AP로 올린 스탯%',
  apStr: 'AP STR',
  apDex: 'AP DEX',
  apInt: 'AP INT',
  apLuk: 'AP LUK',
  apHp: 'AP HP',
  maxHp: '최대 HP',
  maxHpRate: '최대 HP(%)',
  maxMp: '최대 MP',
  maxMpRate: '최대 MP(%)',
  armor: '방어력',
  armorRate: '방어력(%)',
  attackPower: '공격력',
  attackPowerRate: '공격력(%)',
  weaponPureAttackPowerRate: '무기 순수 공격력 비율(%)',
  magicPower: '마력',
  magicPowerRate: '마력(%)',
  damage: '데미지(%)',
  normalDamage: '일반 몬스터 데미지(%)',
  bossDamage: '보스 몬스터 데미지(%)',
  finalDamage: '최종 데미지(%)',
  ignoreMonsterArmor: '몬스터 방어율 무시(%)',
  cooldownSec: '재사용 대기시간 감소(초)',
  cooldownRate: '재사용 대기시간 감소(%)',
  cooldownIgnore: '재사용 대기시간 미적용(%)',
  weaponMastery: '무기 숙련도(%)',
  buffDurationRate: '버프 지속시간 증가(%)',
  summonDurationRate: '소환수 지속시간 증가(%)',
  expRate: '경험치 획득량 증가(%)',
  elementalResistanceRate: '모든 속성 내성(%)',
  elementalResistanceIgnore: '속성 내성 무시(%)',
  attackSpeed: '공격 속도',
  stance: '스탠스',
  speed: '이동속도',
  maxSpeed: '최대 이동속도',
  jump: '점프력',
  criticalRate: '크리티컬 확률',
  criticalDamage: '크리티컬 데미지',
  statusResistance: '상태이상 내성',
  statusConditionAdditionalDamage: '상태이상 추가 데미지',
  starforce: '스타포스',
};
