/* eslint-disable */
// This file is generated by packages/generator/scripts/generate-taxonomy-affiliation-class.mjs.

export const adventurerClassKeyMap = {
  "검사": "swordman",
  "파이터": "fighter",
  "크루세이더": "crusader",
  "히어로": "hero",
  "페이지": "page",
  "나이트": "white-knight",
  "팔라딘": "paladin",
  "스피어맨": "spearman",
  "버서커": "berserker",
  "다크나이트": "dark-knight",
  "메지션": "magician",
  "위자드(불,독)": "wizard-fire-poison",
  "메이지(불,독)": "mage-fire-poison",
  "아크메이지(불,독)": "arch-mage-fire-poison",
  "위자드(썬,콜)": "wizard-ice-lightning",
  "메이지(썬,콜)": "mage-ice-lightning",
  "아크메이지(썬,콜)": "arch-mage-ice-lightning",
  "클레릭": "cleric",
  "프리스트": "priest",
  "비숍": "bishop",
  "아처": "archer",
  "헌터": "hunter",
  "레인저": "ranger",
  "보우마스터": "bow-master",
  "사수": "crossbowman",
  "저격수": "sniper",
  "신궁": "marksman",
  "에이션트 아처": "ancient-archer",
  "체이서": "chaser",
  "패스파인더": "pathfinder",
  "로그": "rogue",
  "어쌔신": "assassin",
  "허밋": "hermit",
  "나이트로드": "night-lord",
  "시프": "thief",
  "시프마스터": "thief-master",
  "섀도어": "shadower",
  "세미듀어러": "semi-dueler",
  "듀어러": "dueler",
  "듀얼마스터": "dual-master",
  "슬래셔": "slasher",
  "듀얼블레이더": "dual-blader",
  "해적": "pirate",
  "인파이터": "infighter",
  "버커니어": "buccaneer",
  "바이퍼": "viper",
  "건슬링거": "gunslinger",
  "발키리": "valkyrie",
  "캡틴": "captain",
  "캐논슈터": "cannon-shooter",
  "캐논블래스터": "cannon-blaster",
  "캐논마스터": "cannon-master",
} as const;

export type AdventurerClassName = keyof typeof adventurerClassKeyMap;
export type AdventurerClassKey = (typeof adventurerClassKeyMap)[AdventurerClassName];
export const adventurerClassNames = Object.keys(adventurerClassKeyMap) as AdventurerClassName[];
export const adventurerClassKeys = Object.values(adventurerClassKeyMap) as AdventurerClassKey[];

export const cygnusClassKeyMap = {
  "소울마스터": "soul-master",
  "미하일": "mikhail",
  "플레임위자드": "flame-wizard",
  "윈드브레이커": "wind-breaker",
  "나이트워커": "night-walker",
  "스트라이커": "striker",
} as const;

export type CygnusClassName = keyof typeof cygnusClassKeyMap;
export type CygnusClassKey = (typeof cygnusClassKeyMap)[CygnusClassName];
export const cygnusClassNames = Object.keys(cygnusClassKeyMap) as CygnusClassName[];
export const cygnusClassKeys = Object.values(cygnusClassKeyMap) as CygnusClassKey[];

export const heroesClassKeyMap = {
  "아란": "aran",
  "에반": "evan",
  "루미너스": "luminous",
  "메르세데스": "mercedes",
  "팬텀": "phantom",
  "은월": "eunwol",
} as const;

export type HeroesClassName = keyof typeof heroesClassKeyMap;
export type HeroesClassKey = (typeof heroesClassKeyMap)[HeroesClassName];
export const heroesClassNames = Object.keys(heroesClassKeyMap) as HeroesClassName[];
export const heroesClassKeys = Object.values(heroesClassKeyMap) as HeroesClassKey[];

export const resistanceClassKeyMap = {
  "블래스터": "blaster",
  "배틀메이지": "battle-mage",
  "와일드헌터": "wild-hunter",
  "메카닉": "mechanic",
  "데몬슬레이어": "demon-slayer",
  "데몬어벤져": "demon-avenger",
  "제논": "xenon",
} as const;

export type ResistanceClassName = keyof typeof resistanceClassKeyMap;
export type ResistanceClassKey = (typeof resistanceClassKeyMap)[ResistanceClassName];
export const resistanceClassNames = Object.keys(resistanceClassKeyMap) as ResistanceClassName[];
export const resistanceClassKeys = Object.values(resistanceClassKeyMap) as ResistanceClassKey[];

export const novaClassKeyMap = {
  "카이저": "kaiser",
  "카인": "kain",
  "카데나": "cadena",
  "엔젤릭버스터": "angelic-buster",
} as const;

export type NovaClassName = keyof typeof novaClassKeyMap;
export type NovaClassKey = (typeof novaClassKeyMap)[NovaClassName];
export const novaClassNames = Object.keys(novaClassKeyMap) as NovaClassName[];
export const novaClassKeys = Object.values(novaClassKeyMap) as NovaClassKey[];

export const transcendentClassKeyMap = {
  "제로": "zero",
} as const;

export type TranscendentClassName = keyof typeof transcendentClassKeyMap;
export type TranscendentClassKey = (typeof transcendentClassKeyMap)[TranscendentClassName];
export const transcendentClassNames = Object.keys(transcendentClassKeyMap) as TranscendentClassName[];
export const transcendentClassKeys = Object.values(transcendentClassKeyMap) as TranscendentClassKey[];

export const friendsWorldClassKeyMap = {
  "키네시스": "kinesis",
} as const;

export type FriendsWorldClassName = keyof typeof friendsWorldClassKeyMap;
export type FriendsWorldClassKey = (typeof friendsWorldClassKeyMap)[FriendsWorldClassName];
export const friendsWorldClassNames = Object.keys(friendsWorldClassKeyMap) as FriendsWorldClassName[];
export const friendsWorldClassKeys = Object.values(friendsWorldClassKeyMap) as FriendsWorldClassKey[];

export const lefClassKeyMap = {
  "아델": "adele",
  "일리움": "illium",
  "칼리": "khali",
  "아크": "ark",
} as const;

export type LefClassName = keyof typeof lefClassKeyMap;
export type LefClassKey = (typeof lefClassKeyMap)[LefClassName];
export const lefClassNames = Object.keys(lefClassKeyMap) as LefClassName[];
export const lefClassKeys = Object.values(lefClassKeyMap) as LefClassKey[];

export const animaClassKeyMap = {
  "렌": "len",
  "라라": "lara",
  "호영": "hoyoung",
} as const;

export type AnimaClassName = keyof typeof animaClassKeyMap;
export type AnimaClassKey = (typeof animaClassKeyMap)[AnimaClassName];
export const animaClassNames = Object.keys(animaClassKeyMap) as AnimaClassName[];
export const animaClassKeys = Object.values(animaClassKeyMap) as AnimaClassKey[];

export const demonClassKeyMap = {
  "데몬슬레이어": "demon-slayer",
  "데몬어벤져": "demon-avenger",
} as const;

export type DemonClassName = keyof typeof demonClassKeyMap;
export type DemonClassKey = (typeof demonClassKeyMap)[DemonClassName];
export const demonClassNames = Object.keys(demonClassKeyMap) as DemonClassName[];
export const demonClassKeys = Object.values(demonClassKeyMap) as DemonClassKey[];

export const resistanceSkillClassKeyMap = {
  "블래스터": "blaster",
  "배틀메이지": "battle-mage",
  "와일드헌터": "wild-hunter",
  "메카닉": "mechanic",
  "제논": "xenon",
} as const;

export type ResistanceSkillClassName = keyof typeof resistanceSkillClassKeyMap;
export type ResistanceSkillClassKey = (typeof resistanceSkillClassKeyMap)[ResistanceSkillClassName];
export const resistanceSkillClassNames = Object.keys(resistanceSkillClassKeyMap) as ResistanceSkillClassName[];
export const resistanceSkillClassKeys = Object.values(resistanceSkillClassKeyMap) as ResistanceSkillClassKey[];

