import { createAccessoryStatBuilder } from './builder';
import type { AccessoryItemStat } from './builder';
import type {
  SpecialRingItemName,
  EventRingItemName,
  RingItemName,
  EyeItemName,
  EarringItemName,
  BeltItemName,
  PocketItemName,
  BadgeItemName,
  AndroidHeartItemName,
  ShoulderItemName,
  PendantItemName,
  FaceItemName,
  EmblemItemName,
} from './name';

import type { EquipmentGenerationStatInput } from '@/rule';

export const specialRingItemMetaMap = createAccessoryStatBuilder<SpecialRingItemName>(
  {
    setKey: null,
    requiredLevel: 110,
    category: 'accessory',
    part: 'ring',
    requiredClass: '공용',
    capability: {
      starforceEnabled: false,
      scrollUpgradeEnabled: false,
      potentialEnabled: false,
      addOptionEnabled: false,
    },
  },
  {
    all: 4,
    attackPower: 4,
    isOppositeAttack: true,
    specialRingLevel: 0,
  },
)
  .add('컨티뉴어스 링', { baseName: '컨티뉴어스 링' })
  .add('리스트레인트 링', { baseName: '리스트레인트 링' })
  .add('리스크테이커 링', { baseName: '리스크테이커 링' })
  .add('웨폰퍼프 - S링', { baseName: '웨폰퍼프 - S링' })
  .add('웨폰퍼프 - D링', { baseName: '웨폰퍼프 - D링' })
  .add('웨폰퍼프 - I링', { baseName: '웨폰퍼프 - I링' })
  .add('웨폰퍼프 - L링', { baseName: '웨폰퍼프 - L링' })
  .add('레벨퍼프 - S링', { baseName: '레벨퍼프 - S링' })
  .add('레벨퍼프 - D링', { baseName: '레벨퍼프 - D링' })
  .add('레벨퍼프 - I링', { baseName: '레벨퍼프 - I링' })
  .add('레벨퍼프 - L링', { baseName: '레벨퍼프 - L링' })
  .add('얼티메이덤 링', { baseName: '얼티메이덤 링' })
  .add('크리데미지 링', { baseName: '크리데미지 링' })
  .add('컨티뉴어스 링 Lv.3', { baseName: '컨티뉴어스 링', specialRingLevel: 3, grantedSkills: ['컨티뉴어스 링 Lv.3'] })
  .add('컨티뉴어스 링 Lv.4', { baseName: '컨티뉴어스 링', specialRingLevel: 4, grantedSkills: ['컨티뉴어스 링 Lv.4'] })
  .add('컨티뉴어스 링 Lv.5', { baseName: '컨티뉴어스 링', specialRingLevel: 5, grantedSkills: ['컨티뉴어스 링 Lv.5'] })
  .add('컨티뉴어스 링 Lv.6', { baseName: '컨티뉴어스 링', specialRingLevel: 6, grantedSkills: ['컨티뉴어스 링 Lv.6'] })
  .add('리스트레인트 링 Lv.3', { baseName: '리스트레인트 링', specialRingLevel: 3, grantedSkills: ['리스트레인트 링 Lv.3'] })
  .add('리스트레인트 링 Lv.4', { baseName: '리스트레인트 링', specialRingLevel: 4, grantedSkills: ['리스트레인트 링 Lv.4'] })
  .add('리스트레인트 링 Lv.5', { baseName: '리스트레인트 링', specialRingLevel: 5, grantedSkills: ['리스트레인트 링 Lv.5'] })
  .add('리스트레인트 링 Lv.6', { baseName: '리스트레인트 링', specialRingLevel: 6, grantedSkills: ['리스트레인트 링 Lv.6'] })
  .add('웨폰퍼프 - S링 Lv.3', { baseName: '웨폰퍼프 - S링', specialRingLevel: 3, grantedSkills: ['웨폰퍼프 - S링 Lv.3'] })
  .add('웨폰퍼프 - S링 Lv.4', { baseName: '웨폰퍼프 - S링', specialRingLevel: 4, grantedSkills: ['웨폰퍼프 - S링 Lv.4'] })
  .add('웨폰퍼프 - D링 Lv.3', { baseName: '웨폰퍼프 - D링', specialRingLevel: 3, grantedSkills: ['웨폰퍼프 - D링 Lv.3'] })
  .add('웨폰퍼프 - D링 Lv.4', { baseName: '웨폰퍼프 - D링', specialRingLevel: 4, grantedSkills: ['웨폰퍼프 - D링 Lv.4'] })
  .add('웨폰퍼프 - I링 Lv.3', { baseName: '웨폰퍼프 - I링', specialRingLevel: 3, grantedSkills: ['웨폰퍼프 - I링 Lv.3'] })
  .add('웨폰퍼프 - I링 Lv.4', { baseName: '웨폰퍼프 - I링', specialRingLevel: 4, grantedSkills: ['웨폰퍼프 - I링 Lv.4'] })
  .add('웨폰퍼프 - L링 Lv.3', { baseName: '웨폰퍼프 - L링', specialRingLevel: 3, grantedSkills: ['웨폰퍼프 - L링 Lv.3'] })
  .add('웨폰퍼프 - L링 Lv.4', { baseName: '웨폰퍼프 - L링', specialRingLevel: 4, grantedSkills: ['웨폰퍼프 - L링 Lv.4'] })
  .doneStrict();

const eventRingSpecs = {
  first: {
    all: 40,
    maxHp: 4000,
    maxMp: 4000,
    attackPower: 25,
    isOppositeAttack: true,
  },
  second: {
    all: 30,
    maxHp: 3000,
    maxMp: 3000,
    attackPower: 20,
    isOppositeAttack: true,
  },
  third: {
    all: 20,
    maxHp: 2000,
    maxMp: 2000,
    attackPower: 20,
    isOppositeAttack: true,
  },
} as const satisfies Record<string, EquipmentGenerationStatInput>;

export const eventRingItemMetaMap = createAccessoryStatBuilder<EventRingItemName>(
  {
    setKey: null,
    requiredLevel: 120,
    category: 'accessory',
    part: 'ring',
    requiredClass: '공용',
    capability: {
      starforceEnabled: false,
      scrollUpgradeEnabled: false,
    },
  },
  {
    ...eventRingSpecs.first,
  },
)
  .add('벤젼스 링', eventRingSpecs.third)
  .add('코스모스 링', { requiredLevel: 50, ...eventRingSpecs.third })
  .add('SS급 마스터 쥬얼링', eventRingSpecs.second)
  .add('결속의 반지', eventRingSpecs.second)
  .add('어드벤쳐 딥다크 크리티컬', {
    all: 20,
    maxHp: 1500,
    maxMp: 1500,
    attackPower: 20,
    criRate: 15,
    criDamage: 5,
  })
  .add('카오스 링', eventRingSpecs.second)
  .add('테네브리스 원정대 반지')
  .add('글로리온 링 : 가디언', eventRingSpecs.third)
  .add('글로리온 링 : 커맨더', eventRingSpecs.third)
  .add('글로리온 링 : 마스터', eventRingSpecs.third)
  .add('글로리온 링 : 슈프림')
  .add('어웨이크 링', { scrollCount: 3 }, { scrollUpgradeEnabled: true })
  .add('이터널 플레임 링')
  .add('어비스 헌터스 링', { all: 20, maxHp: 1000, maxMp: 1000, attackPower: 20, normalDamage: 20 })
  .doneStrict();

export const ringItemMetaMap = createAccessoryStatBuilder<RingItemName>(
  {
    setKey: null,
    category: 'accessory',
    part: 'ring',
    requiredClass: '공용',
  },
  { isOppositeAttack: true, all: 5, attackPower: 2, scrollCount: 3 },
)
  .add('마이스터 링', {
    maxHp: 200,
    maxMp: 200,
    attackPower: 1,
    armor: 150,
    scrollCount: 2,
    requiredLevel: 140,
    setKey: 'meister',
  })
  .add('실버블라썸 링', {
    requiredLevel: 110,
    setKey: 'bossAccessory',
  })
  .add('고귀한 이피아의 반지', {
    maxHp: 200,
    maxMp: 200,
    requiredLevel: 120,
    setKey: 'bossAccessory',
  })
  .add('가디언 엔젤 링', {
    maxHp: 200,
    maxMp: 200,
    requiredLevel: 160,
    setKey: 'bossAccessory',
  })
  .add('여명의 가디언 엔젤 링', {
    maxHp: 200,
    maxMp: 200,
    requiredLevel: 160,
    setKey: 'dawnBoss',
  })
  .add('거대한 공포', {
    maxHp: 250,
    maxMp: 250,
    attackPower: 4,
    requiredLevel: 200,
    setKey: 'darkBoss',
  })
  .add('근원의 속삭임', {
    all: 10,
    maxHp: 500,
    maxMp: 500,
    attackPower: 5,
    scrollCount: 4,
    requiredLevel: 250,
    setKey: 'brilliantBoss',
  })
  .add('황홀한 악몽', {
    all: 10,
    maxHp: 500,
    maxMp: 500,
    attackPower: 5,
    scrollCount: 4,
    requiredLevel: 250,
    setKey: 'brilliantBoss',
  })
  .done();

export const pendantItemMetaMap = createAccessoryStatBuilder<PendantItemName>({ setKey: null, requiredClass: '공용', category: 'accessory', part: 'pendant' })
  .add('혼테일의 목걸이', {
    requiredLevel: 120,
    setKey: 'bossAccessory',
    all: 7,
    attackPower: 0,
    isOppositeAttack: true,
    armor: 108,
    scrollCount: 3,
  })
  .add('카오스 혼테일의 목걸이', {
    requiredLevel: 120,
    setKey: 'bossAccessory',
    all: 10,
    maxHpRate: 10,
    maxMpRate: 10,
    attackPower: 2,
    armor: 140,
    scrollCount: 3,
  })
  .add('매커네이터 펜던트', {
    requiredLevel: 120,
    setKey: 'bossAccessory',
    all: 10,
    maxHp: 250,
    maxMp: 250,
    attackPower: 1,
    armor: 100,
    scrollCount: 3,
  })
  .add('도미네이터 펜던트', {
    requiredLevel: 140,
    setKey: 'bossAccessory',
    all: 20,
    maxHpRate: 10,
    maxMpRate: 10,
    attackPower: 3,
    armor: 100,
    scrollCount: 6,
  })
  .add('데이브레이크 펜던트', {
    requiredLevel: 140,
    setKey: 'dawnBoss',
    all: 8,
    maxHp: 5,
    attackPower: 2,
    armor: 100,
    scrollCount: 6,
  })
  .add('고통의 근원', {
    requiredLevel: 160,
    setKey: 'darkBoss',
    all: 10,
    maxHpRate: 5,
    attackPower: 3,
    armor: 200,
    scrollCount: 6,
  })
  .add('죽음의 맹세', {
    requiredLevel: 250,
    setKey: 'brilliantBoss',
    all: 15,
    maxHpRate: 5,
    attackPower: 5,
    armor: 300,
    scrollCount: 7,
  })
  .add(
    '정령의 펜던트',
    {
      requiredLevel: 0,
    },
    {
      scrollUpgradeEnabled: false,
      addOptionEnabled: false,
      potentialEnabled: false,
      starforceEnabled: false,
    },
  )
  .doneStrict();

export const faceItemMetaMap = createAccessoryStatBuilder<FaceItemName>(
  { setKey: null, requiredClass: '공용', category: 'accessory', part: 'face' },
  {
    isOppositeAttack: true,
  },
)
  .add('응축된 힘의 결정석', {
    requiredLevel: 110,
    setKey: 'bossAccessory',
    all: 5,
    attackPower: 5,
    armor: 100,
    scrollCount: 6,
  })
  .add('트와일라이트 마크', {
    requiredLevel: 140,
    setKey: 'dawnBoss',
    all: 5,
    attackPower: 5,
    armor: 100,
    scrollCount: 4,
  })
  .add('루즈 컨트롤 머신 마크', {
    requiredLevel: 160,
    setKey: 'darkBoss',
    all: 10,
    attackPower: 10,
    armor: 200,
    scrollCount: 6,
    exceptionalScroll: 1,
  })
  .add('오만의 원죄', {
    requiredLevel: 250,
    setKey: 'brilliantBoss',
    all: 15,
    attackPower: 15,
    armor: 300,
    scrollCount: 7,
    exceptionalScroll: 3,
  })
  .doneStrict();

export const eyeItemMetaMap = createAccessoryStatBuilder<EyeItemName>(
  {
    setKey: null,
    category: 'accessory',
    part: 'eye',
    requiredClass: '공용',
  },
  {
    isOppositeAttack: true,
  },
)
  .add('아쿠아틱 레터 눈장식', {
    requiredLevel: 100,
    setKey: 'bossAccessory',
    all: 6,
    attackPower: 1,
    armor: 100,
    scrollCount: 4,
  })
  .add('블랙빈 마크', {
    requiredLevel: 135,
    setKey: 'bossAccessory',
    all: 7,
    attackPower: 1,
    armor: 120,
    scrollCount: 6,
  })
  .add('파풀라투스 마크', {
    requiredLevel: 145,
    setKey: 'bossAccessory',
    all: 8,
    attackPower: 1,
    armor: 150,
    scrollCount: 6,
  })
  .add('마력이 깃든 안대', {
    requiredLevel: 160,
    setKey: 'darkBoss',
    all: 15,
    attackPower: 3,
    armor: 300,
    scrollCount: 4,
    exceptionalScroll: 1,
  })
  .doneStrict();

export const earringItemMetaMap = createAccessoryStatBuilder<EarringItemName>(
  {
    setKey: null,
    category: 'accessory',
    part: 'earring',
    requiredClass: '공용',
  },
  {
    isOppositeAttack: true,
  },
)
  .add('지옥의 불꽃', {
    requiredLevel: 130,
    setKey: 'bossAccessory',
    all: 7,
    maxHp: 100,
    maxMp: 100,
    attackPower: 2,
    armor: 100,
    scrollCount: 6,
  })
  .add('데아 시두스 이어링', {
    requiredLevel: 130,
    setKey: 'bossAccessory',
    all: 5,
    attackPower: 2,
    armor: 50,
    scrollCount: 7,
  })
  .add('마이스터 이어링', {
    requiredLevel: 140,
    setKey: 'meister',
    all: 5,
    maxHp: 500,
    maxMp: 500,
    attackPower: 4,
    armor: 70,
    scrollCount: 7,
  })
  .add('오션 글로우 이어링', {
    requiredLevel: 150,
    all: 7,
    maxHp: 750,
    maxMp: 750,
    attackPower: 5,
    armor: 75,
    scrollCount: 8,
  })
  .add('에스텔라 이어링', {
    requiredLevel: 160,
    setKey: 'dawnBoss',
    all: 7,
    maxHp: 300,
    maxMp: 300,
    attackPower: 2,
    armor: 100,
    scrollCount: 7,
  })
  .add('커맨더 포스 이어링', {
    requiredLevel: 200,
    setKey: 'darkBoss',
    all: 7,
    maxHp: 500,
    maxMp: 500,
    attackPower: 5,
    armor: 100,
    scrollCount: 7,
  })
  .doneStrict();

export const beltItemMetaMap = createAccessoryStatBuilder<BeltItemName>(
  {
    setKey: null,
    requiredClass: '공용',
    category: 'accessory',
    part: 'belt',
  },
  { isOppositeAttack: true },
)
  .add('골든 클로버 벨트', {
    requiredLevel: 140,
    setKey: 'bossAccessory',
    all: 15,
    maxHp: 150,
    maxMp: 150,
    attackPower: 1,
    armor: 150,
    scrollCount: 4,
  })
  .add('분노한 자쿰의 벨트', {
    requiredLevel: 150,
    setKey: 'bossAccessory',
    all: 18,
    maxHp: 150,
    maxMp: 150,
    attackPower: 1,
    armor: 150,
    scrollCount: 4,
  })
  .add('몽환의 벨트', {
    requiredLevel: 200,
    setKey: 'darkBoss',
    all: 50,
    maxHp: 150,
    maxMp: 150,
    attackPower: 6,
    armor: 150,
    scrollCount: 4,
    exceptionalScroll: 1,
  })
  .doneStrict();

export const pocketItemMetaMap = createAccessoryStatBuilder<PocketItemName>(
  {
    setKey: null,
    requiredClass: '공용',
    category: 'accessory',
    part: 'pocket',
  },
  {
    isOppositeAttack: true,
    scrollCount: 0,
  },
)
  .add('영생의 돌', {
    requiredLevel: 0,
    setKey: 'bossAccessory',
    all: 3,
    attackPower: 3,
  })
  .add('핑크빛 성배', {
    requiredLevel: 140,
    setKey: 'bossAccessory',
    all: 5,
    maxHp: 50,
    maxMp: 50,
    attackPower: 5,
  })
  .add('저주받은 적의 마도서', {
    requiredLevel: 160,
    setKey: 'darkBoss',
    all: 10,
    str: 20,
    maxHp: 100,
    maxMp: 100,
    attackPower: 10,
  })
  .add('저주받은 청의 마도서', {
    requiredLevel: 160,
    setKey: 'darkBoss',
    all: 10,
    int: 20,
    maxHp: 100,
    maxMp: 100,
    attackPower: 10,
  })
  .add('저주받은 녹의 마도서', {
    requiredLevel: 160,
    setKey: 'darkBoss',
    all: 10,
    dex: 20,
    maxHp: 100,
    maxMp: 100,
    attackPower: 10,
  })
  .add('저주받은 황의 마도서', {
    requiredLevel: 160,
    setKey: 'darkBoss',
    all: 10,
    luk: 20,
    maxHp: 100,
    maxMp: 100,
    attackPower: 10,
  })
  .doneStrict();

export const badgeItemMetaMap = createAccessoryStatBuilder<BadgeItemName>(
  {
    setKey: null,
    category: 'accessory',
    part: 'badge',
    requiredClass: '공용',
  },
  {
    isOppositeAttack: true,
    scrollCount: 0,
  },
)
  .add('칠요의 뱃지', {
    requiredLevel: 100,
    setKey: 'sevenDay',
    all: 7,
    attackPower: 7,
    ignoreMonsterArmor: 10,
  })
  .add('크리스탈 웬투스 뱃지', {
    requiredLevel: 130,
    setKey: 'bossAccessory',
    all: 10,
    attackPower: 5,
    speed: 10,
    jump: 10,
  })
  .add('창세의 뱃지', {
    requiredLevel: 200,
    setKey: 'darkBoss',
    all: 15,
    attackPower: 10,
    speed: 10,
    jump: 10,
  })
  .done();

export const androidHeartItemMetaMap = createAccessoryStatBuilder<AndroidHeartItemName>(
  {
    setKey: null,
    category: 'etc',
    part: 'androidHeart',
    requiredClass: '공용',
  },
  { isOppositeAttack: true },
)
  .add('티타늄 하트', {
    requiredLevel: 100,
    all: 3,
    maxHp: 50,
    scrollCount: 10,
  })
  .add('페어리 하트', {
    requiredLevel: 100,
    maxHp: 100,
    scrollCount: 10,
  })
  .add('리퀴드메탈 하트', {
    requiredLevel: 120,
    all: 3,
    maxHp: 100,
    scrollCount: 10,
  })
  .add('플라즈마 하트', {
    requiredLevel: 130,
    all: 10,
    maxHp: 500,
    maxMp: 500,
    attackPower: 5,
    ignoreMonsterArmor: 15,
    scrollCount: 10,
  })
  .add('블랙 하트', {
    requiredLevel: 120,
    setKey: 'darkBoss',
    all: 50,
    maxHp: 100,
    attackPower: 77,
    bossDamage: 30,
    ignoreMonsterArmor: 30,
    scrollCount: 0,
  })
  .add('컴플리트 언더컨트롤', {
    requiredLevel: 200,
    setKey: 'darkBoss',
    all: 25,
    maxHp: 1250,
    attackPower: 15,
    ignoreMonsterArmor: 30,
    scrollCount: 10,
  })
  .doneStrict();

export const shoulderItemMetaMap = createAccessoryStatBuilder<ShoulderItemName>(
  {
    setKey: null,
    category: 'accessory',
    part: 'shoulder',
    requiredClass: '공용',
  },
  {
    isOppositeAttack: true,
  },
)
  .add('마이스터 숄더', {
    requiredLevel: 140,
    setKey: 'meister',
    all: 13,
    attackPower: 9,
    armor: 150,
    scrollCount: 2,
  })
  .add('도전자의 어깨장식', {
    requiredLevel: 160,
    setKey: 'challenger',
    all: 14,
    attackPower: 10,
    armor: 100,
    scrollCount: 0,
  })
  .done();

export const emblemItemMetaMap = createAccessoryStatBuilder<EmblemItemName>(
  {
    setKey: null,
    category: 'emblem',
    part: 'emblem',
    requiredClass: '공용',
  },
  {
    all: 10,
    attackPower: 1,
    isOppositeAttack: true,
    scrollCount: 0,
  },
)
  .add('골드 메이플리프 엠블렘', {
    requiredClass: [
      '히어로',
      '팔라딘',
      '다크나이트',
      '아크메이지(불,독)',
      '아크메이지(썬,콜)',
      '비숍',
      '보우마스터',
      '신궁',
      '패스파인더',
      '나이트로드',
      '섀도어',
      '듀얼블레이더',
      '캡틴',
      '바이퍼',
      '캐논마스터',
    ],
  })
  .add('골드 시그너스 엠블렘', {
    requiredClass: ['미하일', '소울마스터', '플레임위자드', '윈드브레이커', '나이트워커'],
  })
  .add('골드 레지스탕스 엠블렘', {
    requiredClass: ['블래스터', '배틀메이지', '와일드헌터', '메카닉'],
  })
  .add('골드 데몬 엠블렘', {
    requiredClass: ['데몬슬레이어', '데몬어벤져'],
    maxHp: 500,
  })
  .add('하이브리드 하트', {
    requiredClass: '제논',
    all: 0,
    maxHp: 300,
    maxMp: 100,
    armor: 100,
  })
  .add('골드 히어로즈 엠블렘', {
    requiredClass: ['아란', '에반', '루미너스', '메르세데스', '팬텀', '은월'],
  })
  .add('드래곤 엠블렘', {
    requiredClass: '카이저',
    all: 0,
    stat: 10,
  })
  .add('골드 히트맨 엠블렘', {
    requiredClass: '카인',
  })
  .add('골드 에이전트 엠블렘', {
    requiredClass: '카데나',
  })
  .add('엔젤 엠블렘', {
    requiredClass: '엔젤릭버스터',
    all: 0,
    stat: 10,
    maxHp: 400,
  })
  .add('골드 나이트 엠블렘', {
    requiredClass: '아델',
  })
  .add('골드 크리스탈 엠블렘', {
    requiredClass: '일리움',
  })
  .add('골드 체이서 엠블렘', {
    requiredClass: '칼리',
  })
  .add('골드 어비스 엠블렘', {
    requiredClass: '아크',
  })
  .add('금빛 검수 엠블렘', {
    requiredClass: '렌',
  })
  .add('금빛 풍수사 엠블렘', {
    requiredClass: '라라',
  })
  .add('금빛 천지인 엠블렘', {
    requiredClass: '호영',
  })
  .add('이터널 타임 엠블렘', {
    requiredClass: '제로',
  })
  .add('골드 키네시스 엠블렘', {
    requiredClass: '키네시스',
  })
  .add('미트라의 분노 : 전사', {
    requiredClass: '전사',
    all: 0,
    stat: 40,
    maxHp: 700,
    attackPower: 5,
    setKey: 'darkBoss',
  })
  .add('미트라의 분노 : 마법사', {
    requiredClass: '마법사',
    all: 0,
    stat: 40,
    attackPower: 5,
    setKey: 'darkBoss',
  })
  .add('미트라의 분노 : 궁수', {
    requiredClass: '궁수',
    all: 0,
    stat: 40,
    attackPower: 5,
    setKey: 'darkBoss',
  })
  .add('미트라의 분노 : 도적', {
    requiredClass: '도적',
    all: 0,
    stat: 40,
    attackPower: 5,
    setKey: 'darkBoss',
  })
  .add('미트라의 분노 : 해적', {
    requiredClass: '해적',
    all: 0,
    stat: 40,
    attackPower: 5,
    setKey: 'darkBoss',
  })
  .doneStrict();

const baseMedalMeta = {
  setKey: null,
  category: 'accessory',
  part: 'medal',
  requiredClass: '공용',
  isOppositeAttack: true,
} as const;

export const medalItemMetaMap = {
  '초보 모험가': { ...baseMedalMeta, requiredLevel: 8 },
  '주니어 모험가': { ...baseMedalMeta, requiredLevel: 30 },
  '베테랑 모험가': { ...baseMedalMeta, requiredLevel: 60 },
  '시그너스의 후계자': { ...baseMedalMeta, requiredLevel: 60 },
  '마스터 모험가': { ...baseMedalMeta, requiredLevel: 100 },
  투신: { ...baseMedalMeta, requiredLevel: 200 },
  현자: { ...baseMedalMeta, requiredLevel: 200 },
  '스나이퍼 로드': { ...baseMedalMeta, requiredLevel: 200 },
  '레전더리 시프': { ...baseMedalMeta, requiredLevel: 200 },
  해적왕: { ...baseMedalMeta, requiredLevel: 200 },
  '저주에 사로잡힌 자': { ...baseMedalMeta, requiredLevel: 10 },
  '시련과 맞선 자': { ...baseMedalMeta, requiredLevel: 30 },
  '어둠의 추적자': { ...baseMedalMeta, requiredLevel: 60 },
  '길을 찾는 자': { ...baseMedalMeta, requiredLevel: 100 },
  '고대 힘의 주인': { ...baseMedalMeta, requiredLevel: 200 },
  노블레스: { ...baseMedalMeta, requiredLevel: 0 },
  수련기사: { ...baseMedalMeta, requiredLevel: 10 },
  정식기사: { ...baseMedalMeta, requiredLevel: 30 },
  상급기사: { ...baseMedalMeta, requiredLevel: 60 },
  기사단장: { ...baseMedalMeta, requiredLevel: 100 },
  '시그너스의 여섯 별': { ...baseMedalMeta, requiredLevel: 200 },
  '새로 태어난 빛': { ...baseMedalMeta, requiredLevel: 10 },
  '수습 빛의 기사': { ...baseMedalMeta, requiredLevel: 30 },
  '정식 빛의 기사': { ...baseMedalMeta, requiredLevel: 60 },
  '빛의 기사단장': { ...baseMedalMeta, requiredLevel: 100 },
  '진정한 빛의 기사': { ...baseMedalMeta, requiredLevel: 200 },
  '깨어난 아란': { ...baseMedalMeta, requiredLevel: 10 },
  '기억속의 아란': { ...baseMedalMeta, requiredLevel: 30 },
  '시련속의 아란': { ...baseMedalMeta, requiredLevel: 60 },
  '희망속의 아란': { ...baseMedalMeta, requiredLevel: 100 },
  '영웅 아란': { ...baseMedalMeta, requiredLevel: 200 },
  '착한 아이': { ...baseMedalMeta, requiredLevel: 14 },
  '페리온 경비병': { ...baseMedalMeta, requiredLevel: 21 },
  '커닝시티 명예시민': { ...baseMedalMeta, requiredLevel: 32 },
  '비밀단체 임시멤버': { ...baseMedalMeta, requiredLevel: 46 },
  '드래곤 마스터': { ...baseMedalMeta, requiredLevel: 60 },
  '드래곤 마스터2': { ...baseMedalMeta, requiredLevel: 100 },
  '영웅의 후계자': { ...baseMedalMeta, requiredLevel: 200 },
  '빛을 되찾은 자': { ...baseMedalMeta, requiredLevel: 10 },
  '어둠에 물든 자': { ...baseMedalMeta, requiredLevel: 10 },
  '어둠을 극복한 자': { ...baseMedalMeta, requiredLevel: 30 },
  '어둠을 흡수한 자': { ...baseMedalMeta, requiredLevel: 60 },
  '빛과 어둠의 수호자': { ...baseMedalMeta, requiredLevel: 100 },
  '운명의 대적자': { ...baseMedalMeta, requiredLevel: 200 },
  '영웅이었던 자': { ...baseMedalMeta, requiredLevel: 10 },
  '에우렐의 엘프': { ...baseMedalMeta, requiredLevel: 30 },
  '고귀한 자의 표식': { ...baseMedalMeta, requiredLevel: 60 },
  '엘프의 영웅': { ...baseMedalMeta, requiredLevel: 100 },
  '엘프의 왕': { ...baseMedalMeta, requiredLevel: 200 },
  '영웅이었던 자(팬텀)': { ...baseMedalMeta, requiredLevel: 10 },
  신출귀몰: { ...baseMedalMeta, requiredLevel: 30 },
  '괴도 레이븐의 제자': { ...baseMedalMeta, requiredLevel: 60 },
  '아리아를 기억하는 자': { ...baseMedalMeta, requiredLevel: 100 },
  '괴도 팬텀': { ...baseMedalMeta, requiredLevel: 200 },
  이방인: { ...baseMedalMeta, requiredLevel: 10 },
  '뾰족귀 여우의 일원': { ...baseMedalMeta, requiredLevel: 30 },
  '기억 너머의 이': { ...baseMedalMeta, requiredLevel: 60 },
  '여우의 벗': { ...baseMedalMeta, requiredLevel: 100 },
  '잊혀진 영웅': { ...baseMedalMeta, requiredLevel: 200 },
  '특별수업 신입생': { ...baseMedalMeta, requiredLevel: 10 },
  '특별수업 중급생': { ...baseMedalMeta, requiredLevel: 30 },
  '특별수업 상급생': { ...baseMedalMeta, requiredLevel: 60 },
  '특별수업 최상급생': { ...baseMedalMeta, requiredLevel: 100 },
  '특별수업 졸업생': { ...baseMedalMeta, requiredLevel: 200 },
  '기억을 찾는 자': { ...baseMedalMeta, requiredLevel: 10 },
  '비밀기관 특수요원': { ...baseMedalMeta, requiredLevel: 30 },
  '자유를 추구하는 자': { ...baseMedalMeta, requiredLevel: 60 },
  '경계에 서있는 자': { ...baseMedalMeta, requiredLevel: 100 },
  '마지막 귀환자': { ...baseMedalMeta, requiredLevel: 200 },
  '부활한 마족': { ...baseMedalMeta, requiredLevel: 10 },
  '어둠의 계약자': { ...baseMedalMeta, requiredLevel: 30 },
  '각성의 마족': { ...baseMedalMeta, requiredLevel: 60 },
  '어둠의 용사': { ...baseMedalMeta, requiredLevel: 100 },
  '복수의 화신': { ...baseMedalMeta, requiredLevel: 200 },
  '분노의 첫 걸음': { ...baseMedalMeta, requiredLevel: 10 },
  '분노의 화신': { ...baseMedalMeta, requiredLevel: 30 },
  '심연의 복수자': { ...baseMedalMeta, requiredLevel: 60 },
  '분노의 정복자': { ...baseMedalMeta, requiredLevel: 100 },
  '궁극의 복수자': { ...baseMedalMeta, requiredLevel: 200 },
  '환생한 카이저': { ...baseMedalMeta, requiredLevel: 10 },
  '카이저의 운명을 걷는 자': { ...baseMedalMeta, requiredLevel: 30 },
  '각성한 카이저': { ...baseMedalMeta, requiredLevel: 60 },
  '카이저의 의지를 잇는자': { ...baseMedalMeta, requiredLevel: 100 },
  '극의에 도달한 자': { ...baseMedalMeta, requiredLevel: 200 },
  '밤의 응시자': { ...baseMedalMeta, requiredLevel: 10 },
  '분노의 심판자': { ...baseMedalMeta, requiredLevel: 30 },
  '기억의 탐색자': { ...baseMedalMeta, requiredLevel: 60 },
  '악의의 계승자': { ...baseMedalMeta, requiredLevel: 100 },
  '어둠의 추격자': { ...baseMedalMeta, requiredLevel: 200 },
  '뒷골목의 그림자': { ...baseMedalMeta, requiredLevel: 10 },
  '도시의 그림자': { ...baseMedalMeta, requiredLevel: 30 },
  '그란디스의 그림자': { ...baseMedalMeta, requiredLevel: 60 },
  '두 세계의 그림자': { ...baseMedalMeta, requiredLevel: 100 },
  '운명의 개척자': { ...baseMedalMeta, requiredLevel: 200 },
  '고대 노바의 계약자': { ...baseMedalMeta, requiredLevel: 10 },
  '정의의 대리인': { ...baseMedalMeta, requiredLevel: 30 },
  '핑크 엔젤': { ...baseMedalMeta, requiredLevel: 60 },
  '전장의 아이돌': { ...baseMedalMeta, requiredLevel: 100 },
  '슈퍼스타★': { ...baseMedalMeta, requiredLevel: 200 },
  '검을 쥐어라': { ...baseMedalMeta, requiredLevel: 10 },
  '맹세의 불꽃을 태워라': { ...baseMedalMeta, requiredLevel: 30 },
  '시련을 품에 안아라': { ...baseMedalMeta, requiredLevel: 60 },
  '어둠 속 빛을 찾아라': { ...baseMedalMeta, requiredLevel: 100 },
  '빛의 검이 되어라': { ...baseMedalMeta, requiredLevel: 200 },
  '미약한 신입': { ...baseMedalMeta, requiredLevel: 10 },
  '피난처의 희망': { ...baseMedalMeta, requiredLevel: 30 },
  '불완전한 방랑자': { ...baseMedalMeta, requiredLevel: 60 },
  '선택받은 언약자': { ...baseMedalMeta, requiredLevel: 100 },
  '광휘의 날개': { ...baseMedalMeta, requiredLevel: 200 },
  '모래의 날개': { ...baseMedalMeta, requiredLevel: 10 },
  '죄악의 심판자': { ...baseMedalMeta, requiredLevel: 30 },
  '사막의 그림자': { ...baseMedalMeta, requiredLevel: 60 },
  '분노의 칼날': { ...baseMedalMeta, requiredLevel: 100 },
  '복수의 바람': { ...baseMedalMeta, requiredLevel: 200 },
  '움트는 심연': { ...baseMedalMeta, requiredLevel: 10 },
  '요동치는 심연': { ...baseMedalMeta, requiredLevel: 30 },
  '심연 속에서': { ...baseMedalMeta, requiredLevel: 60 },
  '심연 속의 빛': { ...baseMedalMeta, requiredLevel: 100 },
  '심연을 삼키다': { ...baseMedalMeta, requiredLevel: 200 },
  용심청매: { ...baseMedalMeta, requiredLevel: 10 },
  천몽지로: { ...baseMedalMeta, requiredLevel: 30 },
  청풍검객: { ...baseMedalMeta, requiredLevel: 60 },
  강호귀왕: { ...baseMedalMeta, requiredLevel: 100 },
  적목객성: { ...baseMedalMeta, requiredLevel: 200 },
  '견습 풍수사': { ...baseMedalMeta, requiredLevel: 10 },
  '용맥을 읽는 자': { ...baseMedalMeta, requiredLevel: 30 },
  '토지령의 벗': { ...baseMedalMeta, requiredLevel: 60 },
  '소중한 이들의 수호자': { ...baseMedalMeta, requiredLevel: 100 },
  '희망의 전파자': { ...baseMedalMeta, requiredLevel: 200 },
  '청운의 꿈': { ...baseMedalMeta, requiredLevel: 10 },
  '천지인의 도': { ...baseMedalMeta, requiredLevel: 30 },
  '천방지축 도사': { ...baseMedalMeta, requiredLevel: 60 },
  '도술의 달인': { ...baseMedalMeta, requiredLevel: 100 },
  호연지기: { ...baseMedalMeta, requiredLevel: 200 },
  '그림자 기사': { ...baseMedalMeta, requiredLevel: 100 },
  '신의 아이': { ...baseMedalMeta, requiredLevel: 180 },
  '폰, 시작의 한 걸음': { ...baseMedalMeta, requiredLevel: 8 },
  '나이트, 고뇌의 움직임': { ...baseMedalMeta, requiredLevel: 30 },
  '룩, 물러섬 없는 도전': { ...baseMedalMeta, requiredLevel: 60 },
  '퀸, 전장의 지배자': { ...baseMedalMeta, requiredLevel: 100 },
  '킹, 모든 움직임의 지배자': { ...baseMedalMeta, requiredLevel: 200 },
  '등으로 말한다': { ...baseMedalMeta, requiredLevel: 0 },
  '턱수염 카리스마': { ...baseMedalMeta, requiredLevel: 0 },
  '왕의 위엄': { ...baseMedalMeta, requiredLevel: 0 },
  '매의 눈': { ...baseMedalMeta, requiredLevel: 0 },
  '요정의 눈동자': { ...baseMedalMeta, requiredLevel: 0 },
  천리안: { ...baseMedalMeta, requiredLevel: 0 },
  고진감래: { ...baseMedalMeta, requiredLevel: 0 },
  '기다림의 미학': { ...baseMedalMeta, requiredLevel: 0 },
  '인내의 화신': { ...baseMedalMeta, requiredLevel: 0 },
  '가정의 손길': { ...baseMedalMeta, requiredLevel: 0 },
  '달인의 마음': { ...baseMedalMeta, requiredLevel: 0 },
  '마이더스의 손': { ...baseMedalMeta, requiredLevel: 0 },
  '질풍노도의 시기': { ...baseMedalMeta, requiredLevel: 0 },
  음유시인: { ...baseMedalMeta, requiredLevel: 0 },
  '인간의 마음': { ...baseMedalMeta, requiredLevel: 0 },
  시선집중: { ...baseMedalMeta, requiredLevel: 0 },
  매력덩어리: { ...baseMedalMeta, requiredLevel: 0 },
  '미의 결정체': { ...baseMedalMeta, requiredLevel: 0 },
  '요정학원 명예교수': { ...baseMedalMeta, requiredLevel: 30 },
  '골드비치 멤버스': { ...baseMedalMeta, requiredLevel: 30 },
  '견습 항해사': { ...baseMedalMeta, requiredLevel: 30 },
  '숲의 비밀을 파헤친 자': { ...baseMedalMeta, requiredLevel: 30 },
  '버섯왕국 수호자': { ...baseMedalMeta, requiredLevel: 30 },
  '꿈을 이뤄준 은인': { ...baseMedalMeta, requiredLevel: 35 },
  '초심을 되찾은 자': { ...baseMedalMeta, requiredLevel: 35 },
  '크리세 구원자': { ...baseMedalMeta, requiredLevel: 60 },
  '비올레타의 수호기사': { ...baseMedalMeta, requiredLevel: 65 },
  '달과 벚꽃의 무사': { ...baseMedalMeta, requiredLevel: 75 },
  '엘린숲의 수호자': { ...baseMedalMeta, requiredLevel: 105 },
  '영원한 충정': { ...baseMedalMeta, requiredLevel: 110 },
  '장미의 기사': { ...baseMedalMeta, requiredLevel: 110 },
  '황금사원의 구도자': { ...baseMedalMeta, requiredLevel: 120 },
  '판타스틱 베이비': { ...baseMedalMeta, requiredLevel: 125 },
  '101번째 프로포즈': { ...baseMedalMeta, requiredLevel: 125 },
  '구름처럼 바람처럼': { ...baseMedalMeta, requiredLevel: 130 },
  '마스테리아를 구할 자': { ...baseMedalMeta, requiredLevel: 130 },
  '시간을 여행한 자': { ...baseMedalMeta, requiredLevel: 130 },
  '저주받은 항아리': { ...baseMedalMeta, requiredLevel: 135 },
  '메소레인저 화이트': { ...baseMedalMeta, requiredLevel: 140 },
  '대박엔터 공동대표': { ...baseMedalMeta, requiredLevel: 150 },
  '거인만큼 위대한 자': { ...baseMedalMeta, requiredLevel: 150 },
  '탐정 레이브의 명예조수': { ...baseMedalMeta, requiredLevel: 175 },
  '뾰족귀 수비대원': { ...baseMedalMeta, requiredLevel: 180 },
  '늪지대 해결사': { ...baseMedalMeta, requiredLevel: 45 },
  '바위산의 사냥꾼': { ...baseMedalMeta, requiredLevel: 55 },
  '위험을 쫓는 자': { ...baseMedalMeta, requiredLevel: 65 },
  '구름 위의 조력자': { ...baseMedalMeta, requiredLevel: 70 },
  '설원의 탐험가': { ...baseMedalMeta, requiredLevel: 77 },
  '아리안트 문화 전문가': { ...baseMedalMeta, requiredLevel: 90 },
  '마가티아의 연금술사': { ...baseMedalMeta, requiredLevel: 95 },
  '루디브리엄 보안관': { ...baseMedalMeta, requiredLevel: 110 },
  '세계수의 수호자': { ...baseMedalMeta, requiredLevel: 110 },
  '신선 수행': { ...baseMedalMeta, requiredLevel: 135 },
  '폐허에서 일어서다': { ...baseMedalMeta, requiredLevel: 160 },
  '황혼의 전사': { ...baseMedalMeta, requiredLevel: 180 },
  '아즈모스 협곡 탐사대': { ...baseMedalMeta, requiredLevel: 200 },
  '나비의 꿈': { ...baseMedalMeta, requiredLevel: 200 },
  '별을 삼킨 고래': { ...baseMedalMeta, requiredLevel: 200 },
  '연합의 증표': { ...baseMedalMeta, requiredLevel: 200 },
  '공허를 극복한 자': { ...baseMedalMeta, requiredLevel: 200 },
  '영원의 늪에서 일어난 빛': { ...baseMedalMeta, requiredLevel: 200 },
  '운명을 넘어선 자': { ...baseMedalMeta, requiredLevel: 200 },
  '검의 주인을 기다리며': { ...baseMedalMeta, requiredLevel: 200 },
  '구원은 그대의 손아귀에': { ...baseMedalMeta, requiredLevel: 200 },
  '가장 느리지만 가장 빠른자': { ...baseMedalMeta, requiredLevel: 200 },
  '혼돈의 눈을 감긴 자': { ...baseMedalMeta, requiredLevel: 200 },
  '낙원에 도달한 사람': { ...baseMedalMeta, requiredLevel: 200 },
  '다시 만나길 기약하며': { ...baseMedalMeta, requiredLevel: 200 },
  '영원의 나무를 지켜낸 자': { ...baseMedalMeta, requiredLevel: 200 },
  '미트라의 전설': { ...baseMedalMeta, requiredLevel: 200 },
  '심해 속 비밀에 닿은 자': { ...baseMedalMeta, requiredLevel: 200 },
  '운명을 거스르는 대적자': { ...baseMedalMeta, requiredLevel: 200 },
  '악몽을 벤 자': { ...baseMedalMeta, requiredLevel: 200 },
  '신들의 진혼사': { ...baseMedalMeta, requiredLevel: 200 },
  '성실한 모험가': { ...baseMedalMeta, requiredLevel: 0 },
  '파티퀘스트 매니아': { ...baseMedalMeta, requiredLevel: 0 },
  '퀘스트 스페셜리스트': { ...baseMedalMeta, requiredLevel: 0 },
  인기인: { ...baseMedalMeta, requiredLevel: 0 },
  '노련한 사냥꾼': { ...baseMedalMeta, requiredLevel: 0 },
  '베스트 사회인': { ...baseMedalMeta, requiredLevel: 0 },
  '러블리 펫주인': { ...baseMedalMeta, requiredLevel: 0 },
  '몬스터 박사': { ...baseMedalMeta, requiredLevel: 0 },
  '끝없는 도전': { ...baseMedalMeta, requiredLevel: 0 },
  '버라이어티 헤어체인저': { ...baseMedalMeta, requiredLevel: 0 },
  '정상에 서본 자': { ...baseMedalMeta, requiredLevel: 0 },
  '초보 탐험가': { ...baseMedalMeta, requiredLevel: 0 },
  '슬리피우드 탐험가': { ...baseMedalMeta, requiredLevel: 0 },
  '빅토리아 탐험가': { ...baseMedalMeta, requiredLevel: 0 },
  '엘나스 산맥 탐험가': { ...baseMedalMeta, requiredLevel: 0 },
  '루더스 호수 탐험가': { ...baseMedalMeta, requiredLevel: 0 },
  '해저 탐험가': { ...baseMedalMeta, requiredLevel: 0 },
  '무릉도원 탐험가': { ...baseMedalMeta, requiredLevel: 0 },
  '니할사막 탐험가': { ...baseMedalMeta, requiredLevel: 0 },
  '미나르숲 탐험가': { ...baseMedalMeta, requiredLevel: 0 },
  '오시리아 탐험가': { ...baseMedalMeta, requiredLevel: 0 },
  '메이플 탐험가': { ...baseMedalMeta, requiredLevel: 0 },
  '메이플 아이돌스타': { ...baseMedalMeta, requiredLevel: 0 },
  '혼테일 슬레이어': { ...baseMedalMeta, requiredLevel: 0 },
  '핑크빈 슬레이어': { ...baseMedalMeta, requiredLevel: 0 },
  '전설적인 사냥꾼': { ...baseMedalMeta, requiredLevel: 0 },
  '리스항구 기부왕': { ...baseMedalMeta, requiredLevel: 0 },
  '헤네시스 기부왕': { ...baseMedalMeta, requiredLevel: 0 },
  '엘리니아 기부왕': { ...baseMedalMeta, requiredLevel: 0 },
  '노틸러스 기부왕': { ...baseMedalMeta, requiredLevel: 0 },
  '페리온 기부왕': { ...baseMedalMeta, requiredLevel: 0 },
  '커닝시티 기부왕': { ...baseMedalMeta, requiredLevel: 0 },
  '슬리피우드 기부왕': { ...baseMedalMeta, requiredLevel: 0 },
  '엘나스 기부왕': { ...baseMedalMeta, requiredLevel: 0 },
  '아쿠아리움 기부왕': { ...baseMedalMeta, requiredLevel: 0 },
  '루디브리엄 기부왕': { ...baseMedalMeta, requiredLevel: 0 },
  '지구방위본부 기부왕': { ...baseMedalMeta, requiredLevel: 0 },
  '아랫마을 기부왕': { ...baseMedalMeta, requiredLevel: 0 },
  '리프레 기부왕': { ...baseMedalMeta, requiredLevel: 0 },
  '무릉 기부왕': { ...baseMedalMeta, requiredLevel: 0 },
  '백초마을 기부왕': { ...baseMedalMeta, requiredLevel: 0 },
  '마가티아 기부왕': { ...baseMedalMeta, requiredLevel: 0 },
  '오르비스 기부왕': { ...baseMedalMeta, requiredLevel: 0 },
  '파티퀘스트 전설의 컬렉터': { ...baseMedalMeta, requiredLevel: 70 },
  '훌륭한 요리사': { ...baseMedalMeta, requiredLevel: 100 },
  '대가족을 이끄는 자': { ...baseMedalMeta, requiredLevel: 0 },
  '절대승리 카니발리언': { ...baseMedalMeta, requiredLevel: 51 },
  '천부적인 카니발리언': { ...baseMedalMeta, requiredLevel: 51 },
  열혈카니발리언: { ...baseMedalMeta, requiredLevel: 30 },
  카니발위너: { ...baseMedalMeta, requiredLevel: 30 },
  '명예 역무원': { ...baseMedalMeta, requiredLevel: 25 },
  '파라오의 수호자': { ...baseMedalMeta, requiredLevel: 40 },
  '이볼빙 시스템 마스터': { ...baseMedalMeta, requiredLevel: 100 },
  '갓컨 브론즈 원스타': { ...baseMedalMeta, requiredLevel: 33 },
  '갓컨 브론즈 투스타': { ...baseMedalMeta, requiredLevel: 33 },
  '갓컨 브론즈 쓰리스타': { ...baseMedalMeta, requiredLevel: 33 },
  '마노 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '스텀피 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '데우 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '킹슬라임 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '대왕지네 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '파우스트 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '킹크랑 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '머쉬맘 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '알리샤르 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '타이머 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '다일 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '파파픽시 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '좀비머쉬맘 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '제노 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '데비존 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '구미호 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '태륜 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '포이즌골렘 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '요괴선사 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '주니어발록 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '엘리쟈 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '프랑켄로이드 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '키메라 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '포장마차 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '스노우맨 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '블루머쉬맘 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '크림슨발록 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '마뇽 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '그리프 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '레비아탄 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '파풀라투스 수행자': { ...baseMedalMeta, requiredLevel: 0 },
  '무릉도장 정복자': { ...baseMedalMeta, requiredLevel: 0 },
  '소공의 후계자': { ...baseMedalMeta, requiredLevel: 0 },
  '견습 크로스헌터': { ...baseMedalMeta, requiredLevel: 75 },
  '정식 크로스헌터': { ...baseMedalMeta, requiredLevel: 90 },
  '전문 크로스헌터': { ...baseMedalMeta, requiredLevel: 105 },
  '크로스헌터 마스터': { ...baseMedalMeta, requiredLevel: 120 },
  '엘리트 크로스헌터': { ...baseMedalMeta, requiredLevel: 180 },
  '방어전 참가자': { ...baseMedalMeta, requiredLevel: 140 },
  '디펜스의 달인': { ...baseMedalMeta, requiredLevel: 140 },
  '힐라의 위엄': { ...baseMedalMeta, requiredLevel: 140 },
  '매그너스의 위엄': { ...baseMedalMeta, requiredLevel: 140 },
  '강 건너 불 구경': { ...baseMedalMeta, requiredLevel: 140 },
  '산전수전 공중전': { ...baseMedalMeta, requiredLevel: 160 },
  'The Seed 뉴비': { ...baseMedalMeta, requiredLevel: 110 },
  '웹 페네트레이터': { ...baseMedalMeta, requiredLevel: 110 },
  'The Seed 비기너': { ...baseMedalMeta, requiredLevel: 110 },
  '아이언 멜터': { ...baseMedalMeta, requiredLevel: 110 },
  'The Seed 트레블러': { ...baseMedalMeta, requiredLevel: 110 },
  '라이언 체이서': { ...baseMedalMeta, requiredLevel: 110 },
  'The Seed 엑스퍼트': { ...baseMedalMeta, requiredLevel: 110 },
  '헤이 버너': { ...baseMedalMeta, requiredLevel: 110 },
  'The Seed 마스터': { ...baseMedalMeta, requiredLevel: 110 },
  '도로시 챌린저': { ...baseMedalMeta, requiredLevel: 110 },
  '얼씨구 좋구나': { ...baseMedalMeta, requiredLevel: 130 },
  '풍악을 울려라': { ...baseMedalMeta, requiredLevel: 130 },
  '닐리리야 니나노': { ...baseMedalMeta, requiredLevel: 130 },
  '월요일엔 역시 몬스터파크': { ...baseMedalMeta, requiredLevel: 100 },
  '화요일엔 역시 몬스터파크': { ...baseMedalMeta, requiredLevel: 100 },
  '수요일엔 역시 몬스터파크': { ...baseMedalMeta, requiredLevel: 100 },
  '목요일엔 역시 몬스터파크': { ...baseMedalMeta, requiredLevel: 100 },
  '금요일엔 역시 몬스터파크': { ...baseMedalMeta, requiredLevel: 100 },
  '토요일엔 역시 몬스터파크': { ...baseMedalMeta, requiredLevel: 100 },
  '일요일엔 역시 몬스터파크': { ...baseMedalMeta, requiredLevel: 100 },
  '칠요의 몬스터파커': { ...baseMedalMeta, requiredLevel: 100, setKey: 'sevenDay', all: 7, attackPower: 7, ignoreMonsterArmor: 10 },
  '프리토의 친구': { ...baseMedalMeta, requiredLevel: 0 },
  '폴로의 친구': { ...baseMedalMeta, requiredLevel: 0 },
  '빅토리아의 수집가': { ...baseMedalMeta, requiredLevel: 33 },
  '빅토리아 히어로': { ...baseMedalMeta, requiredLevel: 33 },
  '아일랜드 탐험가': { ...baseMedalMeta, requiredLevel: 33 },
  '에델슈타인의 수집가': { ...baseMedalMeta, requiredLevel: 33 },
  '엘나스산맥의 수집가': { ...baseMedalMeta, requiredLevel: 33 },
  '장난감 수집가': { ...baseMedalMeta, requiredLevel: 33 },
  '심해의 수집가': { ...baseMedalMeta, requiredLevel: 33 },
  '사막의 수집가': { ...baseMedalMeta, requiredLevel: 33 },
  '무릉도원의 수집가': { ...baseMedalMeta, requiredLevel: 33 },
  '미나르숲의 수집가': { ...baseMedalMeta, requiredLevel: 33 },
  '신전의 수호자': { ...baseMedalMeta, requiredLevel: 33 },
  '이계의 수집가': { ...baseMedalMeta, requiredLevel: 33 },
  '아케인리버의 수집가': { ...baseMedalMeta, requiredLevel: 33 },
  '프렌즈의 수집가': { ...baseMedalMeta, requiredLevel: 33 },
  '하얀 마법사의 추격자': { ...baseMedalMeta, requiredLevel: 100 },
  '여제 메이커': { ...baseMedalMeta, requiredLevel: 100 },
  '취미는 책읽기': { ...baseMedalMeta, requiredLevel: 100 },
  '설원의 음유시인': { ...baseMedalMeta, requiredLevel: 100 },
  '그림자 연금술사': { ...baseMedalMeta, requiredLevel: 100 },
  '샤레니안의 기사': { ...baseMedalMeta, requiredLevel: 100 },
  '신의 선택을 받은 자': { ...baseMedalMeta, requiredLevel: 100 },
  '드림 브레이커 30단 점령자': { ...baseMedalMeta, requiredLevel: 33 },
  '드림 브레이커 40단 점령자': { ...baseMedalMeta, requiredLevel: 33 },
  '드림 브레이커 50단 점령자': { ...baseMedalMeta, requiredLevel: 33 },
  '드림 브레이커 60단 점령자': { ...baseMedalMeta, requiredLevel: 33 },
  '드림 브레이커 70단 점령자': { ...baseMedalMeta, requiredLevel: 33 },
  '드림 브레이커 80단 점령자': { ...baseMedalMeta, requiredLevel: 33 },
  '드림 브레이커 90단 점령자': { ...baseMedalMeta, requiredLevel: 33 },
  '마스터 드림 브레이커': { ...baseMedalMeta, requiredLevel: 33 },
  '연합의 에이스': { ...baseMedalMeta, requiredLevel: 60 },
  '메이플 월드의 구원자': { ...baseMedalMeta, requiredLevel: 120 },
  '와장창 아이스 브레이커': { ...baseMedalMeta, requiredLevel: 100 },
  '막타는 내꺼야': { ...baseMedalMeta, requiredLevel: 100 },
  '나도 이젠 영웅': { ...baseMedalMeta, requiredLevel: 100 },
  '프리드의 리더십': { ...baseMedalMeta, requiredLevel: 100 },
  '메르세데스의 추진력': { ...baseMedalMeta, requiredLevel: 100 },
  '아란의 행동력': { ...baseMedalMeta, requiredLevel: 100 },
  '팬텀의 자유로움': { ...baseMedalMeta, requiredLevel: 100 },
  '은월의 사려깊음': { ...baseMedalMeta, requiredLevel: 100 },
  '루미너스의 집중력': { ...baseMedalMeta, requiredLevel: 100 },
  '와장창 항아리 브레이커': { ...baseMedalMeta, requiredLevel: 100 },
  '내 길을 막지마': { ...baseMedalMeta, requiredLevel: 100 },
  '정답을 피해간 자': { ...baseMedalMeta, requiredLevel: 100 },
  '변장술의 달인': { ...baseMedalMeta, requiredLevel: 100 },
  '미션 파서블': { ...baseMedalMeta, requiredLevel: 100 },
  '세계수 정복자': { ...baseMedalMeta, requiredLevel: 100 },
  '꽃들에게 죽음을': { ...baseMedalMeta, requiredLevel: 100 },
  '데미안 대적자': { ...baseMedalMeta, requiredLevel: 100 },
  '시그너스의 절친': { ...baseMedalMeta, requiredLevel: 33 },
  '나인하트의 절친': { ...baseMedalMeta, requiredLevel: 33 },
  '오즈의 절친': { ...baseMedalMeta, requiredLevel: 33 },
  '이리나의 절친': { ...baseMedalMeta, requiredLevel: 33 },
  '이카르트의 절친': { ...baseMedalMeta, requiredLevel: 33 },
  '호크아이의 절친': { ...baseMedalMeta, requiredLevel: 33 },
  '미하일의 절친': { ...baseMedalMeta, requiredLevel: 33 },
  '오르카의 절친': { ...baseMedalMeta, requiredLevel: 33 },
  '프란시스의 절친': { ...baseMedalMeta, requiredLevel: 33 },
  '헬레나의 절친': { ...baseMedalMeta, requiredLevel: 33 },
  '리린의 절친': { ...baseMedalMeta, requiredLevel: 33 },
  '힐라의 절친': { ...baseMedalMeta, requiredLevel: 33 },
  '하얀 교생선생님의 절친': { ...baseMedalMeta, requiredLevel: 33 },
  '트리스탄 후계자': { ...baseMedalMeta, requiredLevel: 0 },
  '아스완의 구원자': { ...baseMedalMeta, requiredLevel: 120 },
  '아스완의 불사조': { ...baseMedalMeta, requiredLevel: 170 },
  '아스완의 빛': { ...baseMedalMeta, requiredLevel: 170 },
  '힐라를 잘 아는자': { ...baseMedalMeta, requiredLevel: 170 },
  '타락여제 구원자': { ...baseMedalMeta, requiredLevel: 0 },
  '카오스 반반 킬러': { ...baseMedalMeta, requiredLevel: 0 },
  '카오스 피에르 킬러': { ...baseMedalMeta, requiredLevel: 0 },
  '카오스 블러디퀸 킬러': { ...baseMedalMeta, requiredLevel: 0 },
  '카오스 벨룸 킬러': { ...baseMedalMeta, requiredLevel: 0, bossDamage: 5 },
  '우르스 격파자': { ...baseMedalMeta, requiredLevel: 100 },
  '우르스 격파왕': { ...baseMedalMeta, requiredLevel: 100 },
  '신의 컨트롤 보유자': { ...baseMedalMeta, requiredLevel: 100 },
  '근성 하나로 살아가는 자': { ...baseMedalMeta, requiredLevel: 100 },
  '우르스 SSS 획득자': { ...baseMedalMeta, requiredLevel: 100 },
  '우르스 SSS 컬렉터': { ...baseMedalMeta, requiredLevel: 100 },
  '우르스 SSS 슈퍼 컬렉터': { ...baseMedalMeta, requiredLevel: 100 },
  '우르스의 가글인': { ...baseMedalMeta, requiredLevel: 100 },
  '우르스의 악력기': { ...baseMedalMeta, requiredLevel: 100 },
  '어시스트의 달인': { ...baseMedalMeta, requiredLevel: 100 },
  '악몽의 주인 격파자': { ...baseMedalMeta, requiredLevel: 200 },
  '진실을 꿰뚫는 자': { ...baseMedalMeta, requiredLevel: 200 },
  '미궁의 깊이를 아는 자': { ...baseMedalMeta, requiredLevel: 200 },
  '태양과 맞서 싸운 자': { ...baseMedalMeta, requiredLevel: 200 },
  '감시자를 해방한 자': { ...baseMedalMeta, requiredLevel: 200 },
  '불멸의 유산': {
    ...baseMedalMeta,
    requiredLevel: 250,
    setKey: 'brilliantBoss',
    all: 10,
    maxHp: 500,
    maxMp: 500,
    attackPower: 10,
    bossDamage: 10,
    exceptionalScroll: 3,
    capability: { addOptionEnabled: true },
  },
  '사계절을 되찾은 자': { ...baseMedalMeta, requiredLevel: 200 },
  '근원을 파헤친 자': { ...baseMedalMeta, requiredLevel: 200 },
  '연합의 일원': { ...baseMedalMeta, requiredLevel: 70 },
  영안사: { ...baseMedalMeta, requiredLevel: 46 },
  음양사: { ...baseMedalMeta, requiredLevel: 62 },
  퇴마사: { ...baseMedalMeta, requiredLevel: 75 },
  '세인트 엑소시스트': { ...baseMedalMeta, requiredLevel: 100 },
  꿈나무: { ...baseMedalMeta, requiredLevel: 0 },
  '프리미엄 PC방': { ...baseMedalMeta, requiredLevel: 0, all: 8, maxHp: 300, maxMp: 300, attackPower: 10, starforce: 15, arc: 30 },
  '본 투 비 골드': { ...baseMedalMeta, requiredLevel: 0 },
  '본 투 비 다이아': { ...baseMedalMeta, requiredLevel: 0 },
  '본 투 비 레드': { ...baseMedalMeta, requiredLevel: 0 },
  '본 투 비 블랙': { ...baseMedalMeta, requiredLevel: 0 },
  'The Bronze': { ...baseMedalMeta, requiredLevel: 0 },
  'The Silver': { ...baseMedalMeta, requiredLevel: 0 },
  'The Gold': { ...baseMedalMeta, requiredLevel: 0 },
  'The Diamond': { ...baseMedalMeta, requiredLevel: 0 },
  'THE RED': { ...baseMedalMeta, requiredLevel: 0, all: 7, maxHp: 350, maxMp: 350, attackPower: 7, bossDamage: 5 },
  'THE BLACK': { ...baseMedalMeta, requiredLevel: 0, all: 7, maxHp: 350, maxMp: 350, attackPower: 7, bossDamage: 5 },
  '저주를 푼 자': { ...baseMedalMeta, requiredLevel: 0 },
  '매크로 사냥금지': { ...baseMedalMeta, requiredLevel: 0 },
  '바른말 고운말 쓰기': { ...baseMedalMeta, requiredLevel: 0 },
  '무엇이든 물어보세요': { ...baseMedalMeta, requiredLevel: 0 },
  '저와 친구해주세요': { ...baseMedalMeta, requiredLevel: 0 },
  '명예 메소레인저': { ...baseMedalMeta, requiredLevel: 0 },
  '1일 꿈': { ...baseMedalMeta, requiredLevel: 0 },
  '2일 꿈': { ...baseMedalMeta, requiredLevel: 0 },
  '3일 꿈': { ...baseMedalMeta, requiredLevel: 0 },
  '4일 꿈': { ...baseMedalMeta, requiredLevel: 0 },
  '5일 꿈': { ...baseMedalMeta, requiredLevel: 0 },
  '6일 꿈': { ...baseMedalMeta, requiredLevel: 0 },
  '7일 꿈': { ...baseMedalMeta, requiredLevel: 0 },
  '8일 꿈': { ...baseMedalMeta, requiredLevel: 0 },
  '9일 꿈': { ...baseMedalMeta, requiredLevel: 0 },
  '10일 꿈': { ...baseMedalMeta, requiredLevel: 0 },
  '11일 꿈': { ...baseMedalMeta, requiredLevel: 0 },
  '12일 꿈': { ...baseMedalMeta, requiredLevel: 0 },
  '13일 꿈': { ...baseMedalMeta, requiredLevel: 0 },
  '14일 꿈': { ...baseMedalMeta, requiredLevel: 0 },
  '15일 꿈': { ...baseMedalMeta, requiredLevel: 0 },
  메이플러버: { ...baseMedalMeta, requiredLevel: 0 },
  '참 나라사랑': { ...baseMedalMeta, requiredLevel: 0 },
  '명예 메소레인저 2기': { ...baseMedalMeta, requiredLevel: 0 },
  '유물 대회 Top10': { ...baseMedalMeta, requiredLevel: 13 },
  '신비로운 유물 발견자': { ...baseMedalMeta, requiredLevel: 13 },
  '메이플 스쿨': { ...baseMedalMeta, requiredLevel: 10 },
  '콤보 매니아': { ...baseMedalMeta, requiredLevel: 10 },
  '콤보의 달인': { ...baseMedalMeta, requiredLevel: 10 },
  콤보왕: { ...baseMedalMeta, requiredLevel: 10 },
  '2009 여름 소년': { ...baseMedalMeta, requiredLevel: 13 },
  '2009 여름 소녀': { ...baseMedalMeta, requiredLevel: 13 },
  '류호 이주민': { ...baseMedalMeta, requiredLevel: 20 },
  '류호 도전자': { ...baseMedalMeta, requiredLevel: 30 },
  '류호 정착자': { ...baseMedalMeta, requiredLevel: 40 },
  '류호 개척자': { ...baseMedalMeta, requiredLevel: 50 },
  '명예 메소레인저 3기': { ...baseMedalMeta, requiredLevel: 0 },
  '명예 맨손레인저': { ...baseMedalMeta, requiredLevel: 0 },
  '명예 맨발레인저': { ...baseMedalMeta, requiredLevel: 0 },
  '2009루돌프': { ...baseMedalMeta, requiredLevel: 13 },
  'DS 매니아': { ...baseMedalMeta, requiredLevel: 0 },
  '명예 모험가': { ...baseMedalMeta, requiredLevel: 40 },
  '블레이드 명인': { ...baseMedalMeta, requiredLevel: 10 },
  '블레이드 최고명인': { ...baseMedalMeta, requiredLevel: 10 },
  '메이플 가족': { ...baseMedalMeta, requiredLevel: 0 },
  '메이플 진정한 가족': { ...baseMedalMeta, requiredLevel: 0 },
  '7주년 파티 멤버': { ...baseMedalMeta, requiredLevel: 0 },
  '모바일 메이플': { ...baseMedalMeta, requiredLevel: 0 },
  '천안함 46 용사 추모': { ...baseMedalMeta, requiredLevel: 0 },
  '나는야 럭키가이★': { ...baseMedalMeta, requiredLevel: 10 },
  '달빛의 음유시인': { ...baseMedalMeta, requiredLevel: 10 },
  '메이플 가이드북3': { ...baseMedalMeta, requiredLevel: 30 },
  '메이플 가이드북4': { ...baseMedalMeta, requiredLevel: 30 },
  '메이플 가이드북 마스터': { ...baseMedalMeta, requiredLevel: 30 },
  'OTP이용자의 허세': { ...baseMedalMeta, requiredLevel: 10 },
  '깜찍한 뉴비': { ...baseMedalMeta, requiredLevel: 0 },
  쑥쑥커라: { ...baseMedalMeta, requiredLevel: 30 },
  '럭셔리 유저': { ...baseMedalMeta, requiredLevel: 50 },
  '2010루돌프': { ...baseMedalMeta, requiredLevel: 13 },
  '메이플 퀴즈스타 훈장': { ...baseMedalMeta, requiredLevel: 13 },
  '메이플 퀴즈왕 훈장': { ...baseMedalMeta, requiredLevel: 13 },
  '2011 복만이': { ...baseMedalMeta, requiredLevel: 13 },
  아이스나이트: { ...baseMedalMeta, requiredLevel: 30 },
  '출석체크 종결자': { ...baseMedalMeta, requiredLevel: 13 },
  '카오스를 깨달은 자': { ...baseMedalMeta, requiredLevel: 13 },
  '2011 유물 대회 참가자': { ...baseMedalMeta, requiredLevel: 13 },
  '2011 유물 대회 Top 10': { ...baseMedalMeta, requiredLevel: 13 },
  '2011 신비로운 유물 발견자': { ...baseMedalMeta, requiredLevel: 13 },
  '메이플 8樂 지존': { ...baseMedalMeta, requiredLevel: 10 },
  '성실한 발굴단원': { ...baseMedalMeta, requiredLevel: 13 },
  '메이플 가이드북 훈장': { ...baseMedalMeta, requiredLevel: 30 },
  '메이플 3000일 훈장': { ...baseMedalMeta, requiredLevel: 10 },
  '레전드 62만의 주인공': { ...baseMedalMeta, requiredLevel: 50 },
  '근사한 유저': { ...baseMedalMeta, requiredLevel: 50 },
  '초코스틱 위크엔드 스페셜': { ...baseMedalMeta, requiredLevel: 10 },
  '2011 크리스마스 훈장': { ...baseMedalMeta, requiredLevel: 10 },
  '크리스마스의 기적': { ...baseMedalMeta, requiredLevel: 10 },
  '새롭게 태어난 듀블': { ...baseMedalMeta, requiredLevel: 0 },
  '어둠 속의 회오리': { ...baseMedalMeta, requiredLevel: 30 },
  '바람을 가르는 자': { ...baseMedalMeta, requiredLevel: 60 },
  '가장 빛나는 그림자': { ...baseMedalMeta, requiredLevel: 100 },
  '메이플 가이드북 지식인': { ...baseMedalMeta, requiredLevel: 0 },
  '2012 유물대회 참가자': { ...baseMedalMeta, requiredLevel: 10 },
  '2012 슈피겔만의 유물 발굴자': { ...baseMedalMeta, requiredLevel: 10 },
  '메이플 9주년 기념 훈장': { ...baseMedalMeta, requiredLevel: 10 },
  정다정다정다정다정: { ...baseMedalMeta, requiredLevel: 0 },
  'SIU의 윙트리 훈장': { ...baseMedalMeta, requiredLevel: 0 },
  '시간 여행자': { ...baseMedalMeta, requiredLevel: 30 },
  '다시 태어난 영웅': { ...baseMedalMeta, requiredLevel: 0 },
  '성공한 독서가': { ...baseMedalMeta, requiredLevel: 30 },
  '메이플 뉴페이스': { ...baseMedalMeta, requiredLevel: 10 },
  '미스틱 반 레온의 악몽': { ...baseMedalMeta, requiredLevel: 75 },
  '미스틱 아카이럼의 악몽': { ...baseMedalMeta, requiredLevel: 75 },
  '미스틱 힐라의 악몽': { ...baseMedalMeta, requiredLevel: 75 },
  '미스틱 자쿰의 악몽': { ...baseMedalMeta, requiredLevel: 75 },
  '미스틱 혼테일의 악몽': { ...baseMedalMeta, requiredLevel: 75 },
  '미스틱 게이트 연구자': { ...baseMedalMeta, requiredLevel: 75 },
  '메이플 유령스쿨 훈장': { ...baseMedalMeta, requiredLevel: 10 },
  '폭풍을 이끄는 자': { ...baseMedalMeta, requiredLevel: 30 },
  '매그너스 격파 선봉장': { ...baseMedalMeta, requiredLevel: 0 },
  '메이플 박물왕': { ...baseMedalMeta, requiredLevel: 10 },
  '다섯 영웅의 완성': { ...baseMedalMeta, requiredLevel: 10 },
  '할로윈의 별': { ...baseMedalMeta, requiredLevel: 10 },
  '빅토리 할로윈 스타': { ...baseMedalMeta, requiredLevel: 30 },
  '2012 버닝 메이플 훈장': { ...baseMedalMeta, requiredLevel: 75 },
  '용감한 리본돼지의 기상': { ...baseMedalMeta, requiredLevel: 13 },
  '내가 바로 액션 히어로': { ...baseMedalMeta, requiredLevel: 13 },
  내껀내가지킨다: { ...baseMedalMeta, requiredLevel: 10 },
  '글로리어스 윈터': { ...baseMedalMeta, requiredLevel: 13 },
  '언리미티드 훈장': { ...baseMedalMeta, requiredLevel: 10 },
  '연합을 이끄는 자': { ...baseMedalMeta, requiredLevel: 30 },
  '럭키럭키 훈장': { ...baseMedalMeta, requiredLevel: 10 },
  '얼티밋의 별': { ...baseMedalMeta, requiredLevel: 100 },
  '올마이티 데몬': { ...baseMedalMeta, requiredLevel: 0 },
  메리크리스마스: { ...baseMedalMeta, requiredLevel: 10 },
  '아이테르의 별': { ...baseMedalMeta, requiredLevel: 100 },
  '2013 설날': { ...baseMedalMeta, requiredLevel: 13 },
  '★★13개의 별★★': { ...baseMedalMeta, requiredLevel: 13 },
  '시그너스 리턴즈': { ...baseMedalMeta, requiredLevel: 13 },
  '설날 의자왕': { ...baseMedalMeta, requiredLevel: 13 },
  '메이플 박물왕중왕': { ...baseMedalMeta, requiredLevel: 13 },
  '메이플 모태솔로': { ...baseMedalMeta, requiredLevel: 13 },
  '메이플 하트브레이커': { ...baseMedalMeta, requiredLevel: 13 },
  '10주년 광고모델': { ...baseMedalMeta, requiredLevel: 13 },
  공모자들: { ...baseMedalMeta, requiredLevel: 13 },
  '메이플 10년의 주인': { ...baseMedalMeta, requiredLevel: 10 },
  '메이플 10년의 기적': { ...baseMedalMeta, requiredLevel: 10 },
  '10주년의 화가': { ...baseMedalMeta, requiredLevel: 13 },
  '왕관 쌓기의 달인': { ...baseMedalMeta, requiredLevel: 13 },
  '지구방위대 훈장': { ...baseMedalMeta, requiredLevel: 10 },
  '양떼 목장의 지배자': { ...baseMedalMeta, requiredLevel: 13 },
  '붉은 여름의 문턱': { ...baseMedalMeta, requiredLevel: 10 },
  '붉은 여름 안에서': { ...baseMedalMeta, requiredLevel: 10 },
  '붉은 여름의 승리자': { ...baseMedalMeta, requiredLevel: 10 },
  '붉은 여름을 기억하는': { ...baseMedalMeta, requiredLevel: 10 },
  '예전의 내가 아니야': { ...baseMedalMeta, requiredLevel: 13 },
  '의자왕 훈장': { ...baseMedalMeta, requiredLevel: 13 },
  '한가위 한가득': { ...baseMedalMeta, requiredLevel: 13 },
  '커플을 지킨 솔로': { ...baseMedalMeta, requiredLevel: 30 },
  '새해 목표왕': { ...baseMedalMeta, requiredLevel: 33 },
  타이피스트: { ...baseMedalMeta, requiredLevel: 33 },
  '광속의 댓글러': { ...baseMedalMeta, requiredLevel: 33 },
  '키보드 배틀의 신': { ...baseMedalMeta, requiredLevel: 33 },
  '비자발적 독신주의자': { ...baseMedalMeta, requiredLevel: 33 },
  '미스틱 게이트 마스터': { ...baseMedalMeta, requiredLevel: 100 },
  '절대적인 힘에 도전한 자': { ...baseMedalMeta, requiredLevel: 13 },
  '왕관 쌓기의 대가': { ...baseMedalMeta, requiredLevel: 13 },
  '미니게임의 달인': { ...baseMedalMeta, requiredLevel: 0 },
  '루밍의 수제자': { ...baseMedalMeta, requiredLevel: 0 },
  '11주년을 함께한': { ...baseMedalMeta, requiredLevel: 0 },
  '몬스터 연구가': { ...baseMedalMeta, requiredLevel: 33 },
  '친구가 사줬어': { ...baseMedalMeta, requiredLevel: 0 },
  '떡국 맛 좀 보신 분': { ...baseMedalMeta, requiredLevel: 0 },
  '호로록 떡국 푸드파이터': { ...baseMedalMeta, requiredLevel: 0 },
  '성공적, 로맨티스트': { ...baseMedalMeta, requiredLevel: 33 },
  '모은다, 적립한다, 쓴다': { ...baseMedalMeta, requiredLevel: 0 },
  '메이플 트레져': { ...baseMedalMeta, requiredLevel: 30 },
  BlackHeavenLover: { ...baseMedalMeta, requiredLevel: 0 },
  '메이플스토리전을 함께한': { ...baseMedalMeta, requiredLevel: 0 },
  '돼지바 퀴즈왕': { ...baseMedalMeta, requiredLevel: 0 },
  '내 친구는 핑크빈': { ...baseMedalMeta, requiredLevel: 0 },
  '빙수 소믈리에': { ...baseMedalMeta, requiredLevel: 33 },
  '빙수학 명예박사': { ...baseMedalMeta, requiredLevel: 33 },
  '2015 세계여행자': { ...baseMedalMeta, requiredLevel: 120 },
  '황룡파 문하생': { ...baseMedalMeta, requiredLevel: 33 },
  '적호파 문하생': { ...baseMedalMeta, requiredLevel: 33 },
  히에이잔: { ...baseMedalMeta, requiredLevel: 33 },
  '털었다. 완소 메이플스토어': { ...baseMedalMeta, requiredLevel: 0 },
  '몸에 좋은 황금물고기': { ...baseMedalMeta, requiredLevel: 0 },
  '간담회에 간담': { ...baseMedalMeta, requiredLevel: 0 },
  '메이플 컬렉터': { ...baseMedalMeta, requiredLevel: 30 },
  '가위바위보 참 쉼쿰': { ...baseMedalMeta, requiredLevel: 33 },
  '왕관쌓기의 고수': { ...baseMedalMeta, requiredLevel: 33 },
  '원티드 프레시': { ...baseMedalMeta, requiredLevel: 33 },
  '원티드 엘리트': { ...baseMedalMeta, requiredLevel: 33 },
  '원티드 베테랑': { ...baseMedalMeta, requiredLevel: 33 },
  '원티드 에이스': { ...baseMedalMeta, requiredLevel: 33 },
  '리부트2 개척자': { ...baseMedalMeta, requiredLevel: 150 },
  '메이플스토리M 훈장': { ...baseMedalMeta, requiredLevel: 0 },
  '호빵의 신': { ...baseMedalMeta, requiredLevel: 33 },
  '라떼 아티스트': { ...baseMedalMeta, requiredLevel: 33 },
  '까치와 함께 보낸 설': { ...baseMedalMeta, requiredLevel: 33 },
  '무신강림 훈장': { ...baseMedalMeta, requiredLevel: 33 },
  '룬 역사학자': { ...baseMedalMeta, requiredLevel: 33 },
  '동아리 트레이너': { ...baseMedalMeta, requiredLevel: 33 },
  '유령 조사원': { ...baseMedalMeta, requiredLevel: 33 },
  '캔디는 달콤해': { ...baseMedalMeta, requiredLevel: 33 },
  '꿀 떨어진다': { ...baseMedalMeta, requiredLevel: 33 },
  '해변의 무법자': { ...baseMedalMeta, requiredLevel: 33 },
  '메이플블리츠X 훈장': { ...baseMedalMeta, requiredLevel: 0 },
  '왕관 쌓기의 장인': { ...baseMedalMeta, requiredLevel: 33 },
  '15번가 셀럽': { ...baseMedalMeta, requiredLevel: 0 },
  '꿈의 오케스트라': { ...baseMedalMeta, requiredLevel: 0 },
  BURNING: { ...baseMedalMeta, requiredLevel: 0 },
  '내가 바로 메잘알': { ...baseMedalMeta, requiredLevel: 0 },
  '뉴트로 히어로': { ...baseMedalMeta, requiredLevel: 0 },
  '호텔 메이플 VIP 멤버': { ...baseMedalMeta, requiredLevel: 0 },
  'medal 블랙스완': { ...baseMedalMeta, requiredLevel: 0 },
  '블루밍 메이플': { ...baseMedalMeta, requiredLevel: 0 },
  '★★★★★★★★★★': { ...baseMedalMeta, requiredLevel: 0 },
  '메이플의 ★': { ...baseMedalMeta, requiredLevel: 0 },
  '영예의 금손': { ...baseMedalMeta, requiredLevel: 0 },
  '빛나는 은손': { ...baseMedalMeta, requiredLevel: 0 },
  '환상 오케스트라': { ...baseMedalMeta, requiredLevel: 0 },
  '메이플 모멘트리': { ...baseMedalMeta, requiredLevel: 0 },
  'MAPLE LIVE TALK': { ...baseMedalMeta, requiredLevel: 0 },
  '2022 싸전귀 레전드': { ...baseMedalMeta, requiredLevel: 0 },
  '2022 싸전귀 다이아': { ...baseMedalMeta, requiredLevel: 0 },
  '2022 싸전귀 골드': { ...baseMedalMeta, requiredLevel: 0 },
  '2022 싸전귀 실버': { ...baseMedalMeta, requiredLevel: 0 },
  '진 천사': { ...baseMedalMeta, requiredLevel: 0 },
  '진 악마': { ...baseMedalMeta, requiredLevel: 0 },
  '풀 문 미니게임 콜렉터': { ...baseMedalMeta, requiredLevel: 0 },
  '슈퍼 예티X핑크빈': { ...baseMedalMeta, requiredLevel: 0 },
  BLACK: { ...baseMedalMeta, requiredLevel: 0 },
  PINK: { ...baseMedalMeta, requiredLevel: 0 },
  '☆메이프릴 아일랜드☆': { ...baseMedalMeta, requiredLevel: 0 },
  '프로즌 블래스트 노비스': { ...baseMedalMeta, requiredLevel: 0 },
  '프로즌 블래스트 익스퍼트': { ...baseMedalMeta, requiredLevel: 0 },
  '프로즌 블래스트 베테랑': { ...baseMedalMeta, requiredLevel: 0 },
  'NEW AGE': { ...baseMedalMeta, requiredLevel: 0 },
  'HYPER BURNING': { ...baseMedalMeta, requiredLevel: 200 },
  '이덴티스크의 전사': { ...baseMedalMeta, requiredLevel: 0 },
  '이덴티스크의 주술사': { ...baseMedalMeta, requiredLevel: 0 },
  '이덴티스크의 사냥꾼': { ...baseMedalMeta, requiredLevel: 0 },
  '이덴티스크의 베테랑 헌터': { ...baseMedalMeta, requiredLevel: 0 },
  '엘 클리어': { ...baseMedalMeta, requiredLevel: 0 },
  '엘 페일': { ...baseMedalMeta, requiredLevel: 0 },
  '재즈 온 메이플': { ...baseMedalMeta, requiredLevel: 0 },
  '싣나모 아래 우리': { ...baseMedalMeta, requiredLevel: 0 },
  '뜻을 아로새긴 자': { ...baseMedalMeta, requiredLevel: 0 },
  '아스라이 나리는 꿈': { ...baseMedalMeta, requiredLevel: 0 },
  DREAMER: { ...baseMedalMeta, requiredLevel: 0 },
  '춤의 조각 수집가': { ...baseMedalMeta, requiredLevel: 0 },
  빅토리아컵: { ...baseMedalMeta, requiredLevel: 0 },
  '검은 천국의 대적자': { ...baseMedalMeta, requiredLevel: 200 },
  '2024 싸전귀 레전드': { ...baseMedalMeta, requiredLevel: 0 },
  '2024 싸전귀 다이아': { ...baseMedalMeta, requiredLevel: 0 },
  '2024 싸전귀 골드': { ...baseMedalMeta, requiredLevel: 0 },
  '2024 싸전귀 실버': { ...baseMedalMeta, requiredLevel: 0 },
  MILESTONE: { ...baseMedalMeta, requiredLevel: 0 },
  '근원의 지배자': { ...baseMedalMeta, requiredLevel: 200 },
  챔피언: { ...baseMedalMeta, requiredLevel: 0 },
  'DAVE THE DIVER': { ...baseMedalMeta, requiredLevel: 0 },
  귀살대: { ...baseMedalMeta, requiredLevel: 0 },
  '메이플 X 귀멸의 칼날': { ...baseMedalMeta, requiredLevel: 0 },
  '힘내라, 탄지로! 힘내라!': { ...baseMedalMeta, requiredLevel: 0 },
  '내가 제일 잘 올라': { ...baseMedalMeta, requiredLevel: 0 },
  '메이플 캅스 출동': { ...baseMedalMeta, requiredLevel: 0 },
  NEXT: { ...baseMedalMeta, requiredLevel: 0 },
  'HYPER BURNING MAX': { ...baseMedalMeta, requiredLevel: 200 },
  '에오스의 인도자': { ...baseMedalMeta, requiredLevel: 0 },
  '헬리오스의 인도자': { ...baseMedalMeta, requiredLevel: 0 },
  '완전히 이해했어': { ...baseMedalMeta, requiredLevel: 0 },
  '챌린저스 월드 브론즈': { ...baseMedalMeta, requiredLevel: 200 },
  '챌린저스 월드 실버': { ...baseMedalMeta, requiredLevel: 200 },
  '챌린저스 월드 골드': { ...baseMedalMeta, requiredLevel: 200 },
  '챌린저스 월드 에메랄드': { ...baseMedalMeta, requiredLevel: 200 },
  '챌린저스 월드 다이아': { ...baseMedalMeta, requiredLevel: 200 },
  '챌린저스 월드 챌린저': { ...baseMedalMeta, requiredLevel: 200 },
  '윷놀이의 달인': { ...baseMedalMeta, requiredLevel: 0 },
  '황금 문어의 심장': { ...baseMedalMeta, requiredLevel: 0 },
  '메이플 대학교': { ...baseMedalMeta, requiredLevel: 0 },
  '메이플 대학생': { ...baseMedalMeta, requiredLevel: 0 },
  '차원의 TOP': { ...baseMedalMeta, requiredLevel: 0 },
  '2025 싸전귀 레전드': { ...baseMedalMeta, requiredLevel: 0 },
  '2025 싸전귀 다이아': { ...baseMedalMeta, requiredLevel: 0 },
  '2025 싸전귀 골드': { ...baseMedalMeta, requiredLevel: 0 },
  '2025 싸전귀 실버': { ...baseMedalMeta, requiredLevel: 0 },
  '유랑의 시작': { ...baseMedalMeta, requiredLevel: 0 },
  '여행의 끝': { ...baseMedalMeta, requiredLevel: 0 },
  '챌린저스 월드 시즌 2 브론즈': { ...baseMedalMeta, requiredLevel: 200 },
  '챌린저스 월드 시즌 2 실버': { ...baseMedalMeta, requiredLevel: 200 },
  '챌린저스 월드 시즌 2 골드': { ...baseMedalMeta, requiredLevel: 200 },
  '챌린저스 월드 시즌 2 플래티넘': { ...baseMedalMeta, requiredLevel: 200 },
  '챌린저스 월드 시즌 2 에메랄드': { ...baseMedalMeta, requiredLevel: 200 },
  '챌린저스 월드 시즌 2 다이아몬드': { ...baseMedalMeta, requiredLevel: 200 },
  '챌린저스 월드 시즌 2 마스터': { ...baseMedalMeta, requiredLevel: 200 },
  '챌린저스 월드 시즌 2 챌린저': { ...baseMedalMeta, requiredLevel: 200 },
  ASSEMBLE: { ...baseMedalMeta, requiredLevel: 0 },
  '내가 바로 메이플 캅스': { ...baseMedalMeta, requiredLevel: 0 },
  '하이퍼 바디': { ...baseMedalMeta, requiredLevel: 0 },
  '선더 볼트': { ...baseMedalMeta, requiredLevel: 0 },
  '유니온 포커스': { ...baseMedalMeta, requiredLevel: 0 },
  '새비지 블로우': { ...baseMedalMeta, requiredLevel: 0 },
  '신비한 한글의 기운': { ...baseMedalMeta, requiredLevel: 0 },
  '메이플 월드의 히어로': { ...baseMedalMeta, requiredLevel: 0 },
  '귀신 사이보그': { ...baseMedalMeta, requiredLevel: 0 },
  '챌린저스 월드 시즌 3 브론즈': { ...baseMedalMeta, requiredLevel: 200 },
  '챌린저스 월드 시즌 3 실버': { ...baseMedalMeta, requiredLevel: 200 },
  '챌린저스 월드 시즌 3 골드': { ...baseMedalMeta, requiredLevel: 200 },
  '챌린저스 월드 시즌 3 플래티넘': { ...baseMedalMeta, requiredLevel: 200 },
  '챌린저스 월드 시즌 3 에메랄드': { ...baseMedalMeta, requiredLevel: 200 },
  '챌린저스 월드 시즌 3 다이아몬드': { ...baseMedalMeta, requiredLevel: 200 },
  '챌린저스 월드 시즌 3 마스터': { ...baseMedalMeta, requiredLevel: 200 },
  '챌린저스 월드 시즌 3 챌린저': { ...baseMedalMeta, requiredLevel: 200 },
  '영혼의 파트너': { ...baseMedalMeta, requiredLevel: 200 },
  CROWN: { ...baseMedalMeta, requiredLevel: 0 },
  KINETIC: { ...baseMedalMeta, requiredLevel: 0 },
  '메이플 캅스 임무 완료': { ...baseMedalMeta, requiredLevel: 0 },
  '탐식의 마침표': { ...baseMedalMeta, requiredLevel: 200 },
  '메이플 X 프리렌': { ...baseMedalMeta, requiredLevel: 0 },
  '일급 마법사': { ...baseMedalMeta, requiredLevel: 0 },
  '메이플 어택': { ...baseMedalMeta, requiredLevel: 0 },
  '악몽의 주인': { ...baseMedalMeta, requiredLevel: 0 },
  '차원의 탑 정복자': { ...baseMedalMeta, requiredLevel: 0 },
  '시즌 4 월드 베스트': { ...baseMedalMeta, requiredLevel: 0 },
  'DEAR MY HERO': { ...baseMedalMeta, requiredLevel: 0 },
} as const satisfies Record<string, AccessoryItemStat<'medal'>>;
