import { createWeaponMetaBuilder } from './builder';
import type { FafnirWeaponName, AbsolabsWeaponName, ArcaneShadeWeaponName, DestinyWeaponName, GenesisWeaponName } from './name';

export const destinyWeaponMetaMap = createWeaponMetaBuilder<DestinyWeaponName>({
  requiredLevel: 250,
  setKey: 'eternal',
  luckyFlag: true,
})
  .add('데스티니 세이버', 'oneHandedSword')
  .add('데스티니 투핸드소드', 'twoHandedSword')
  .add('데스티니 엑스', 'oneHandedAxe')
  .add('데스티니 투핸드엑스', 'twoHandedAxe')
  .add('데스티니 해머', 'oneHandedBluntWeapon')
  .add('데스티니 투핸드해머', 'twoHandedBluntWeapon')
  .add('데스티니 스피어', 'spear')
  .add('데스티니 폴암', 'polearm')
  .add('데스티니 데스페라도', 'desperado')
  .add('데스티니 엘라하', 'gauntletRevolver')
  .add('데스티니 라즐리', 'katana')
  .add('데스티니 라피스', 'greatSword')
  .add('데스티니 튜너', 'tuner')
  .add('데스티니 초극검', 'longSword')
  .add('데스티니 완드', 'wand')
  .add('데스티니 스태프', 'staff')
  .add('데스티니 샤이닝로드', 'shiningRod')
  .add('데스티니 ESP리미터', 'espLimiter')
  .add('데스티니 매직 건틀렛', 'magicGauntlet')
  .add('데스티니 보우', 'bow')
  .add('데스티니 크로스보우', 'crossbow')
  .add('데스티니 듀얼보우건', 'dualBowguns')
  .add('데스티니 에이션트 보우', 'ancientBow')
  .add('데스티니 브레스 슈터', 'breathShooter')
  .add('데스티니 대거', 'dagger')
  .add('데스티니 가즈', 'claw')
  .add('데스티니 케인', 'cane')
  .add('데스티니 체인', 'chain')
  .add('데스티니 초월선', 'fan')
  .add('데스티니 차크람', 'chakram')
  .add('데스티니 에너지체인', 'energySword')
  .add('데스티니 피스톨', 'gun')
  .add('데스티니 클로', 'knuckle')
  .add('데스티니 블래스트캐논', 'handCannon')
  .add('데스티니 소울슈터', 'soulShooter')
  .doneStrict();

export const genesisWeaponMetaMap = createWeaponMetaBuilder<GenesisWeaponName>({
  requiredLevel: 200,
  setKey: 'eternal',
  luckyFlag: true,
  grantedSkills: ['파괴의 얄다바오트'],
})
  .add('제네시스 세이버', 'oneHandedSword')
  .add('제네시스 투핸드소드', 'twoHandedSword')
  .add('제네시스 해머', 'oneHandedBluntWeapon')
  .add('제네시스 투핸드해머', 'twoHandedBluntWeapon')
  .add('제네시스 엑스', 'oneHandedAxe')
  .add('제네시스 투핸드엑스', 'twoHandedAxe')
  .add('제네시스 스피어', 'spear')
  .add('제네시스 폴암', 'polearm')
  .add('제네시스 데스페라도', 'desperado')
  .add('제네시스 엘라하', 'gauntletRevolver')
  .add('제네시스 라즐리', 'katana')
  .add('제네시스 라피스', 'greatSword')
  .add('제네시스 튜너', 'tuner')
  .add('제네시스 창세검', 'longSword')
  .add('제네시스 완드', 'wand')
  .add('제네시스 스태프', 'staff')
  .add('제네시스 샤이닝로드', 'shiningRod')
  .add('제네시스 ESP리미터', 'espLimiter')
  .add('제네시스 매직 건틀렛', 'magicGauntlet')
  .add('제네시스 보우', 'bow')
  .add('제네시스 크로스보우', 'crossbow')
  .add('제네시스 듀얼보우건', 'dualBowguns')
  .add('제네시스 에이션트 보우', 'ancientBow')
  .add('제네시스 브레스 슈터', 'breathShooter')
  .add('제네시스 대거', 'dagger')
  .add('제네시스 가즈', 'claw')
  .add('제네시스 케인', 'cane')
  .add('제네시스 체인', 'chain')
  .add('제네시스 창세선', 'fan')
  .add('제네시스 이클립스', 'chakram')
  .add('제네시스 에너지체인', 'energySword')
  .add('제네시스 피스톨', 'gun')
  .add('제네시스 클로', 'knuckle')
  .add('제네시스 시즈건', 'handCannon')
  .add('제네시스 소울슈터', 'soulShooter')
  .doneStrict();

export const arcaneShadeWeaponMetaMap = createWeaponMetaBuilder<ArcaneShadeWeaponName>({
  requiredLevel: 200,
  setKey: 'arcaneShade',
})
  .add('아케인셰이드 세이버', 'oneHandedSword')
  .add('아케인셰이드 엑스', 'oneHandedAxe')
  .add('아케인셰이드 해머', 'oneHandedBluntWeapon')
  .add('아케인셰이드 투핸드소드', 'twoHandedSword')
  .add('아케인셰이드 투핸드엑스', 'twoHandedAxe')
  .add('아케인셰이드 투핸드해머', 'twoHandedBluntWeapon')
  .add('아케인셰이드 스피어', 'spear')
  .add('아케인셰이드 폴암', 'polearm')
  .add('아케인셰이드 데스페라도', 'desperado')
  .add('아케인셰이드 엘라하', 'gauntletRevolver')
  .add('아케인셰이드 튜너', 'tuner')
  .add('아케인셰이드 환검', 'longSword')
  .add('아케인셰이드 완드', 'wand')
  .add('아케인셰이드 스태프', 'staff')
  .add('아케인셰이드 샤이닝로드', 'shiningRod')
  .add('아케인셰이드 ESP 리미터', 'espLimiter')
  .add('아케인셰이드 매직 건틀렛', 'magicGauntlet')
  .add('아케인셰이드 보우', 'bow')
  .add('아케인셰이드 크로스보우', 'crossbow')
  .add('아케인셰이드 듀얼보우건', 'dualBowguns')
  .add('아케인셰이드 에인션트 보우', 'ancientBow')
  .add('아케인셰이드 브레스 슈터', 'breathShooter')
  .add('아케인셰이드 대거', 'dagger')
  .add('아케인셰이드 가즈', 'claw')
  .add('아케인셰이드 케인', 'cane')
  .add('아케인셰이드 에너지체인', 'energySword')
  .add('아케인셰이드 체인', 'chain')
  .add('아케인셰이드 초선', 'fan')
  .add('아케인셰이드 차크람', 'chakram')
  .add('아케인셰이드 피스톨', 'gun')
  .add('아케인셰이드 클로', 'knuckle')
  .add('아케인셰이드 시즈건', 'handCannon')
  .add('아케인셰이드 소울슈터', 'soulShooter')
  .doneStrict();

export const absolabsWeaponMetaMap = createWeaponMetaBuilder<AbsolabsWeaponName>({
  requiredLevel: 160,
  setKey: 'absolabs',
})
  .add('앱솔랩스 세이버', 'oneHandedSword')
  .add('앱솔랩스 엑스', 'oneHandedAxe')
  .add('앱솔랩스 비트해머', 'oneHandedBluntWeapon')
  .add('앱솔랩스 브로드세이버', 'twoHandedSword')
  .add('앱솔랩스 브로드엑스', 'twoHandedAxe')
  .add('앱솔랩스 브로드해머', 'twoHandedBluntWeapon')
  .add('앱솔랩스 피어싱스피어', 'spear')
  .add('앱솔랩스 핼버드', 'polearm')
  .add('앱솔랩스 데스페라도', 'desperado')
  .add('앱솔랩스 파일 갓', 'gauntletRevolver')
  .add('앱솔랩스 튜너', 'tuner')
  .add('앱솔랩스 폭검', 'longSword')
  .add('앱솔랩스 스펠링완드', 'wand')
  .add('앱솔랩스 스펠링스태프', 'staff')
  .add('앱솔랩스 샤이닝로드', 'shiningRod')
  .add('앱솔랩스 ESP리미터', 'espLimiter')
  .add('앱솔랩스 매직 건틀렛', 'magicGauntlet')
  .add('앱솔랩스 슈팅보우', 'bow')
  .add('앱솔랩스 크로스보우', 'crossbow')
  .add('앱솔랩스 듀얼보우건', 'dualBowguns')
  .add('앱솔랩스 에인션트 보우', 'ancientBow')
  .add('앱솔랩스 브레스 슈터', 'breathShooter')
  .add('앱솔랩스 슬래셔', 'dagger')
  .add('앱솔랩스 리벤지가즈', 'claw')
  .add('앱솔랩스 핀쳐케인', 'cane')
  .add('앱솔랩스 에너지소드', 'energySword')
  .add('앱솔랩스 체인', 'chain')
  .add('앱솔랩스 괴선', 'fan')
  .add('앱솔랩스 차크람', 'chakram')
  .add('앱솔랩스 포인팅건', 'gun')
  .add('앱솔랩스 블로우너클', 'knuckle')
  .add('앱솔랩스 블래스트캐논', 'handCannon')
  .add('앱솔랩스 소울슈터', 'soulShooter')
  .doneStrict();

export const fafnirWeaponMetaMap = createWeaponMetaBuilder<FafnirWeaponName>({
  requiredLevel: 150,
  setKey: 'rootAbyss',
})
  .add('파프니르 미스틸테인', 'oneHandedSword')
  .add('파프니르 트윈클리버', 'oneHandedAxe')
  .add('파프니르 골디언해머', 'oneHandedBluntWeapon')
  .add('파프니르 페니텐시아', 'twoHandedSword')
  .add('파프니르 배틀클리버', 'twoHandedAxe')
  .add('파프니르 라이트닝어', 'twoHandedBluntWeapon')
  .add('파프니르 브류나크', 'spear')
  .add('파프니르 문글레이브', 'polearm')
  .add('파프니르 데스브링어', 'desperado')
  .add('파프니르 빅 마운틴', 'gauntletRevolver')
  .add('파프니르 포기브니스', 'tuner')
  .add('파프니르 용천검', 'longSword')
  .add('파프니르 마나테이커', 'wand')
  .add('파프니르 마나크라운', 'staff')
  .add('파프니르 마나크래들', 'shiningRod')
  .add('파프니르 ESP리미터', 'espLimiter')
  .add('파프니르 매직 건틀렛', 'magicGauntlet')
  .add('파프니르 윈드체이서', 'bow')
  .add('파프니르 윈드윙슈터', 'crossbow')
  .add('파프니르 듀얼윈드윙', 'dualBowguns')
  .add('파프니르 에인션트 보우', 'ancientBow')
  .add('파프니르 나이트체이서', 'breathShooter')
  .add('파프니르 다마스커스', 'dagger')
  .add('파프니르 리스크홀더', 'claw')
  .add('파프니르 클레르시엘', 'cane')
  .add('파프니르 스플릿엣지', 'energySword')
  .add('파프니르 체인', 'chain')
  .add('파프니르 용선', 'fan')
  .add('파프니르 차크람', 'chakram')
  .add('파프니르 첼리스카', 'gun')
  .add('파프니르 펜리르탈론', 'knuckle')
  .add('파프니르 러스터캐논', 'handCannon')
  .add('파프니르 엔젤릭슈터', 'soulShooter')
  .doneStrict();
