import { createWeaponStatBuilder } from './builder';
import type { AbsolabsWeaponName, ArcaneShadeWeaponName, DestinyWeaponName, FafnirWeaponName, GenesisWeaponName } from './name';

export const destinyWeaponStatMap = createWeaponStatBuilder<DestinyWeaponName>({ stat: 190, bossDamage: 30, ignoreMonsterArmor: 20, scrollCount: 8 })
  .add('데스티니 세이버', { attackPower: 358 })
  .add('데스티니 투핸드소드', { attackPower: 373 })
  .add('데스티니 해머', { attackPower: 358 })
  .add('데스티니 투핸드해머', { attackPower: 373 })
  .add('데스티니 엑스', { attackPower: 358 })
  .add('데스티니 투핸드엑스', { attackPower: 373 })
  .add('데스티니 스피어', { attackPower: 373 })
  .add('데스티니 폴암', { attackPower: 334 })
  .add('데스티니 데스페라도', { stat: 0, str: 190, dex: 0, int: 0, luk: 0, maxHp: 3040, attackPower: 373 })
  .add('데스티니 엘라하', { attackPower: 280 })
  .add('데스티니 라즐리', { attackPower: 370 })
  .add('데스티니 라피스', { attackPower: 375 })
  .add('데스티니 튜너', { attackPower: 373 })
  .add('데스티니 초극검', { attackPower: 375 })
  .add('데스티니 완드', { attackPower: 260, magicPower: 439 })
  .add('데스티니 스태프', { attackPower: 275, magicPower: 445 })
  .add('데스티니 샤이닝로드', { attackPower: 260, magicPower: 439 })
  .add('데스티니 ESP리미터', { attackPower: 260, magicPower: 439 })
  .add('데스티니 매직 건틀렛', { attackPower: 260, magicPower: 439 })
  .add('데스티니 보우', { attackPower: 349 })
  .add('데스티니 크로스보우', { attackPower: 358 })
  .add('데스티니 듀얼보우건', { attackPower: 349 })
  .add('데스티니 에이션트 보우', { attackPower: 349 })
  .add('데스티니 브레스 슈터', { attackPower: 349 })
  .add('데스티니 대거', { attackPower: 349 })
  .add('데스티니 가즈', { attackPower: 189 })
  .add('데스티니 케인', { attackPower: 358 })
  .add('데스티니 체인', { attackPower: 349 })
  .add('데스티니 초월선', { attackPower: 349 })
  .add('데스티니 차크람', { attackPower: 349 })
  .add('데스티니 에너지체인', { attackPower: 280 })
  .add('데스티니 피스톨', { attackPower: 273 })
  .add('데스티니 클로', { attackPower: 280 })
  .add('데스티니 블래스트캐논', { attackPower: 382 })
  .add('데스티니 소울슈터', { attackPower: 280 })
  .doneStrict();

export const genesisWeaponStatMap = createWeaponStatBuilder<GenesisWeaponName>({ stat: 150, bossDamage: 30, ignoreMonsterArmor: 20, scrollCount: 8 })
  .add('제네시스 세이버', { attackPower: 326 })
  .add('제네시스 투핸드소드', { attackPower: 340 })
  .add('제네시스 해머', { attackPower: 326 })
  .add('제네시스 투핸드해머', { attackPower: 340 })
  .add('제네시스 엑스', { attackPower: 326 })
  .add('제네시스 투핸드엑스', { attackPower: 340 })
  .add('제네시스 스피어', { attackPower: 340 })
  .add('제네시스 폴암', { attackPower: 304 })
  .add('제네시스 데스페라도', { stat: 0, str: 150, dex: 0, int: 0, luk: 0, maxHp: 2800, attackPower: 340 })
  .add('제네시스 엘라하', { attackPower: 255 })
  .add('제네시스 라즐리', { attackPower: 337 })
  .add('제네시스 라피스', { attackPower: 342 })
  .add('제네시스 튜너', { attackPower: 340 })
  .add('제네시스 창세검', { attackPower: 340 })
  .add('제네시스 완드', { attackPower: 237, magicPower: 400 })
  .add('제네시스 스태프', { attackPower: 251, magicPower: 406 })
  .add('제네시스 샤이닝로드', { attackPower: 237, magicPower: 400 })
  .add('제네시스 ESP리미터', { attackPower: 237, magicPower: 400 })
  .add('제네시스 매직 건틀렛', { attackPower: 237, magicPower: 400 })
  .add('제네시스 보우', { attackPower: 318 })
  .add('제네시스 크로스보우', { attackPower: 326 })
  .add('제네시스 듀얼보우건', { attackPower: 318 })
  .add('제네시스 에이션트 보우', { attackPower: 318 })
  .add('제네시스 브레스 슈터', { attackPower: 318 })
  .add('제네시스 대거', { attackPower: 318 })
  .add('제네시스 가즈', { attackPower: 172 })
  .add('제네시스 케인', { attackPower: 326 })
  .add('제네시스 체인', { attackPower: 318 })
  .add('제네시스 창세선', { attackPower: 318 })
  .add('제네시스 이클립스', { attackPower: 318 })
  .add('제네시스 에너지체인', { attackPower: 255 })
  .add('제네시스 피스톨', { attackPower: 249 })
  .add('제네시스 클로', { attackPower: 255 })
  .add('제네시스 시즈건', { attackPower: 348 })
  .add('제네시스 소울슈터', { attackPower: 255 })
  .doneStrict();

export const arcaneShadeWeaponStatMap = createWeaponStatBuilder<ArcaneShadeWeaponName>({ stat: 100, bossDamage: 30, ignoreMonsterArmor: 20, scrollCount: 9 })
  .add('아케인셰이드 세이버', { attackPower: 283 })
  .add('아케인셰이드 엑스', { attackPower: 283 })
  .add('아케인셰이드 해머', { attackPower: 283 })
  .add('아케인셰이드 투핸드소드', { attackPower: 295 })
  .add('아케인셰이드 투핸드엑스', { attackPower: 295 })
  .add('아케인셰이드 투핸드해머', { attackPower: 283 })
  .add('아케인셰이드 스피어', { attackPower: 295 })
  .add('아케인셰이드 폴암', { attackPower: 264 })
  .add('아케인셰이드 데스페라도', { stat: 0, str: 100, dex: 0, int: 0, luk: 0, maxHp: 2500, attackPower: 295 })
  .add('아케인셰이드 엘라하', { attackPower: 221 })
  .add('아케인셰이드 튜너', { attackPower: 295 })
  .add('아케인셰이드 환검', { attackPower: 295 })
  .add('아케인셰이드 완드', { attackPower: 206, magicPower: 347 })
  .add('아케인셰이드 스태프', { attackPower: 218, magicPower: 353 })
  .add('아케인셰이드 샤이닝로드', { attackPower: 206, magicPower: 347 })
  .add('아케인셰이드 ESP 리미터', { attackPower: 206, magicPower: 347 })
  .add('아케인셰이드 매직 건틀렛', { attackPower: 206, magicPower: 347 })
  .add('아케인셰이드 보우', { attackPower: 276, speed: 19 })
  .add('아케인셰이드 크로스보우', { attackPower: 283, speed: 19 })
  .add('아케인셰이드 듀얼보우건', { attackPower: 276, speed: 19 })
  .add('아케인셰이드 에인션트 보우', { attackPower: 276, speed: 19 })
  .add('아케인셰이드 브레스 슈터', { attackPower: 276, speed: 19 })
  .add('아케인셰이드 대거', { attackPower: 276 })
  .add('아케인셰이드 가즈', { attackPower: 149 })
  .add('아케인셰이드 케인', { attackPower: 283 })
  .add('아케인셰이드 에너지체인', { attackPower: 221 })
  .add('아케인셰이드 체인', { attackPower: 276 })
  .add('아케인셰이드 초선', { attackPower: 276 })
  .add('아케인셰이드 차크람', { attackPower: 276 })
  .add('아케인셰이드 피스톨', { attackPower: 216 })
  .add('아케인셰이드 클로', { attackPower: 221 })
  .add('아케인셰이드 시즈건', { attackPower: 302, armor: 200 })
  .add('아케인셰이드 소울슈터', { attackPower: 221 })
  .doneStrict();

export const absolabsWeaponStatMap = createWeaponStatBuilder<AbsolabsWeaponName>({ stat: 60, bossDamage: 30, ignoreMonsterArmor: 10, scrollCount: 9 })
  .add('앱솔랩스 세이버', { attackPower: 197 })
  .add('앱솔랩스 엑스', { attackPower: 197 })
  .add('앱솔랩스 비트해머', { attackPower: 197 })
  .add('앱솔랩스 브로드세이버', { attackPower: 205 })
  .add('앱솔랩스 브로드엑스', { attackPower: 205 })
  .add('앱솔랩스 브로드해머', { attackPower: 205 })
  .add('앱솔랩스 피어싱스피어', { attackPower: 205 })
  .add('앱솔랩스 핼버드', { attackPower: 184 })
  .add('앱솔랩스 데스페라도', { stat: 0, str: 60, dex: 0, int: 0, luk: 0, maxHp: 2250, attackPower: 205 })
  .add('앱솔랩스 파일 갓', { attackPower: 154 })
  .add('앱솔랩스 튜너', { attackPower: 205 })
  .add('앱솔랩스 폭검', { attackPower: 205 })
  .add('앱솔랩스 스펠링완드', { attackPower: 143, magicPower: 241 })
  .add('앱솔랩스 스펠링스태프', { attackPower: 151, magicPower: 251 })
  .add('앱솔랩스 샤이닝로드', { attackPower: 143, magicPower: 241 })
  .add('앱솔랩스 ESP리미터', { attackPower: 143, magicPower: 241 })
  .add('앱솔랩스 매직 건틀렛', { attackPower: 143, magicPower: 241 })
  .add('앱솔랩스 슈팅보우', { attackPower: 192, speed: 12 })
  .add('앱솔랩스 크로스보우', { attackPower: 197, speed: 15 })
  .add('앱솔랩스 듀얼보우건', { attackPower: 192, speed: 15 })
  .add('앱솔랩스 에인션트 보우', { attackPower: 192, speed: 12 })
  .add('앱솔랩스 브레스 슈터', { attackPower: 192, speed: 12 })
  .add('앱솔랩스 슬래셔', { attackPower: 192 })
  .add('앱솔랩스 리벤지가즈', { attackPower: 103 })
  .add('앱솔랩스 핀쳐케인', { attackPower: 197 })
  .add('앱솔랩스 에너지소드', { attackPower: 154 })
  .add('앱솔랩스 체인', { attackPower: 192 })
  .add('앱솔랩스 괴선', { attackPower: 192 })
  .add('앱솔랩스 차크람', { attackPower: 192 })
  .add('앱솔랩스 포인팅건', { attackPower: 150 })
  .add('앱솔랩스 블로우너클', { attackPower: 154 })
  .add('앱솔랩스 블래스트캐논', { attackPower: 210, armor: 160 })
  .add('앱솔랩스 소울슈터', { attackPower: 154 })
  .doneStrict();

export const fafnirWeaponStatMap = createWeaponStatBuilder<FafnirWeaponName>({ stat: 40, bossDamage: 30, ignoreMonsterArmor: 10, scrollCount: 9 })
  .add('파프니르 미스틸테인', { attackPower: 164 })
  .add('파프니르 트윈클리버', { attackPower: 164 })
  .add('파프니르 골디언해머', { attackPower: 164 })
  .add('파프니르 페니텐시아', { attackPower: 171 })
  .add('파프니르 배틀클리버', { attackPower: 171 })
  .add('파프니르 라이트닝어', { attackPower: 171 })
  .add('파프니르 브류나크', { attackPower: 171 })
  .add('파프니르 문글레이브', { attackPower: 153 })
  .add('파프니르 데스브링어', { stat: 0, str: 40, dex: 0, int: 0, luk: 0, maxHp: 2000, attackPower: 171 })
  .add('파프니르 빅 마운틴', { attackPower: 128 })
  .add('파프니르 포기브니스', { attackPower: 171 })
  .add('파프니르 용천검', { attackPower: 171 })
  .add('파프니르 마나테이커', { attackPower: 119, magicPower: 201 })
  .add('파프니르 마나크라운', { attackPower: 126, magicPower: 204 })
  .add('파프니르 마나크래들', { attackPower: 119, magicPower: 201 })
  .add('파프니르 ESP리미터', { attackPower: 119, magicPower: 201 })
  .add('파프니르 매직 건틀렛', { attackPower: 119, magicPower: 201 })
  .add('파프니르 윈드체이서', { attackPower: 160 })
  .add('파프니르 윈드윙슈터', { attackPower: 164 })
  .add('파프니르 듀얼윈드윙', { attackPower: 160 })
  .add('파프니르 에인션트 보우', { attackPower: 160 })
  .add('파프니르 나이트체이서', { attackPower: 160 })
  .add('파프니르 다마스커스', { attackPower: 160 })
  .add('파프니르 리스크홀더', { attackPower: 86 })
  .add('파프니르 클레르시엘', { attackPower: 164 })
  .add('파프니르 스플릿엣지', { attackPower: 128 })
  .add('파프니르 체인', { attackPower: 160 })
  .add('파프니르 용선', { attackPower: 160 })
  .add('파프니르 차크람', { attackPower: 160 })
  .add('파프니르 첼리스카', { attackPower: 125 })
  .add('파프니르 펜리르탈론', { attackPower: 128 })
  .add('파프니르 러스터캐논', { attackPower: 175, armor: 121 })
  .add('파프니르 엔젤릭슈터', { attackPower: 128 })
  .doneStrict();
