/* eslint-disable */
// This file is generated by packages/generator/scripts/generate-taxonomy-affiliation-class.mjs.

import type { FinalClassName, AdventurerClassName, CygnusClassName, HeroesClassName, ResistanceClassName, DemonClassName, ResistanceSkillClassName, NovaClassName, TranscendentClassName, FriendsWorldClassName, LefClassName, AnimaClassName } from '../class';

export const finalClassNameKeyMap = {
  "히어로": "hero",
  "팔라딘": "paladin",
  "다크나이트": "dark-knight",
  "아크메이지(불,독)": "arch-mage-fire-poison",
  "아크메이지(썬,콜)": "arch-mage-ice-lightning",
  "비숍": "bishop",
  "보우마스터": "bow-master",
  "신궁": "marksman",
  "패스파인더": "pathfinder",
  "나이트로드": "night-lord",
  "섀도어": "shadower",
  "듀얼블레이더": "dual-blader",
  "바이퍼": "viper",
  "캡틴": "captain",
  "캐논마스터": "cannon-master",
  "소울마스터": "soul-master",
  "플레임위자드": "flame-wizard",
  "윈드브레이커": "wind-breaker",
  "나이트워커": "night-walker",
  "스트라이커": "striker",
  "미하일": "mikhail",
  "아란": "aran",
  "에반": "evan",
  "메르세데스": "mercedes",
  "팬텀": "phantom",
  "은월": "eunwol",
  "루미너스": "luminous",
  "데몬슬레이어": "demon-slayer",
  "데몬어벤져": "demon-avenger",
  "배틀메이지": "battle-mage",
  "와일드헌터": "wild-hunter",
  "메카닉": "mechanic",
  "제논": "xenon",
  "블래스터": "blaster",
  "카이저": "kaiser",
  "카인": "kain",
  "카데나": "cadena",
  "엔젤릭버스터": "angelic-buster",
  "제로": "zero",
  "키네시스": "kinesis",
  "아델": "adele",
  "일리움": "illium",
  "칼리": "khali",
  "아크": "ark",
  "렌": "len",
  "라라": "lara",
  "호영": "hoyoung",
} as const;

export type FinalClassNameKey = (typeof finalClassNameKeyMap)[FinalClassName];
export const finalClassNameKeys = Object.values(finalClassNameKeyMap) as FinalClassNameKey[];

export const adventurerClassNameKeyMap = {
  "검사": "swordman",
  "스피어맨": "spearman",
  "버서커": "berserker",
  "다크나이트": "dark-knight",
  "파이터": "fighter",
  "크루세이더": "crusader",
  "히어로": "hero",
  "페이지": "page",
  "나이트": "white-knight",
  "팔라딘": "paladin",
  "아처": "archer",
  "헌터": "hunter",
  "레인저": "ranger",
  "보우마스터": "bow-master",
  "사수": "crossbowman",
  "저격수": "sniper",
  "신궁": "marksman",
  "에이션트 아처": "ancient-archer",
  "체이서": "chaser",
  "패스파인더": "pathfinder",
  "메지션": "magician",
  "위자드(불,독)": "wizard-fire-poison",
  "메이지(불,독)": "mage-fire-poison",
  "아크메이지(불,독)": "arch-mage-fire-poison",
  "위자드(썬,콜)": "wizard-ice-lightning",
  "메이지(썬,콜)": "mage-ice-lightning",
  "아크메이지(썬,콜)": "arch-mage-ice-lightning",
  "클레릭": "cleric",
  "프리스트": "priest",
  "비숍": "bishop",
  "로그": "rogue",
  "어쌔신": "assassin",
  "허밋": "hermit",
  "나이트로드": "night-lord",
  "시프": "thief",
  "시프마스터": "thief-master",
  "섀도어": "shadower",
  "세미듀어러": "semi-dueler",
  "듀어러": "dueler",
  "듀얼마스터": "dual-master",
  "슬래셔": "slasher",
  "듀얼블레이더": "dual-blader",
  "해적": "pirate",
  "인파이터": "infighter",
  "버커니어": "buccaneer",
  "바이퍼": "viper",
  "건슬링거": "gunslinger",
  "발키리": "valkyrie",
  "캡틴": "captain",
  "캐논슈터": "cannon-shooter",
  "캐논블래스터": "cannon-blaster",
  "캐논마스터": "cannon-master",
} as const;

export type AdventurerClassNameKey = (typeof adventurerClassNameKeyMap)[AdventurerClassName];
export const adventurerClassNameKeys = Object.values(adventurerClassNameKeyMap) as AdventurerClassNameKey[];

export const cygnusClassNameKeyMap = {
  "미하일": "mikhail",
  "소울마스터": "soul-master",
  "플레임위자드": "flame-wizard",
  "윈드브레이커": "wind-breaker",
  "나이트워커": "night-walker",
  "스트라이커": "striker",
} as const;

export type CygnusClassNameKey = (typeof cygnusClassNameKeyMap)[CygnusClassName];
export const cygnusClassNameKeys = Object.values(cygnusClassNameKeyMap) as CygnusClassNameKey[];

export const heroesClassNameKeyMap = {
  "아란": "aran",
  "에반": "evan",
  "루미너스": "luminous",
  "메르세데스": "mercedes",
  "팬텀": "phantom",
  "은월": "eunwol",
} as const;

export type HeroesClassNameKey = (typeof heroesClassNameKeyMap)[HeroesClassName];
export const heroesClassNameKeys = Object.values(heroesClassNameKeyMap) as HeroesClassNameKey[];

export const resistanceClassNameKeyMap = {
  "블래스터": "blaster",
  "데몬어벤져": "demon-avenger",
  "데몬슬레이어": "demon-slayer",
  "배틀메이지": "battle-mage",
  "와일드헌터": "wild-hunter",
  "제논": "xenon",
  "메카닉": "mechanic",
} as const;

export type ResistanceClassNameKey = (typeof resistanceClassNameKeyMap)[ResistanceClassName];
export const resistanceClassNameKeys = Object.values(resistanceClassNameKeyMap) as ResistanceClassNameKey[];

export const demonClassNameKeyMap = {
  "데몬어벤져": "demon-avenger",
  "데몬슬레이어": "demon-slayer",
} as const;

export type DemonClassNameKey = (typeof demonClassNameKeyMap)[DemonClassName];
export const demonClassNameKeys = Object.values(demonClassNameKeyMap) as DemonClassNameKey[];

export const resistanceSkillClassNameKeyMap = {
  "블래스터": "blaster",
  "배틀메이지": "battle-mage",
  "와일드헌터": "wild-hunter",
  "제논": "xenon",
  "메카닉": "mechanic",
} as const;

export type ResistanceSkillClassNameKey = (typeof resistanceSkillClassNameKeyMap)[ResistanceSkillClassName];
export const resistanceSkillClassNameKeys = Object.values(resistanceSkillClassNameKeyMap) as ResistanceSkillClassNameKey[];

export const novaClassNameKeyMap = {
  "카이저": "kaiser",
  "카인": "kain",
  "카데나": "cadena",
  "엔젤릭버스터": "angelic-buster",
} as const;

export type NovaClassNameKey = (typeof novaClassNameKeyMap)[NovaClassName];
export const novaClassNameKeys = Object.values(novaClassNameKeyMap) as NovaClassNameKey[];

export const transcendentClassNameKeyMap = {
  "제로": "zero",
} as const;

export type TranscendentClassNameKey = (typeof transcendentClassNameKeyMap)[TranscendentClassName];
export const transcendentClassNameKeys = Object.values(transcendentClassNameKeyMap) as TranscendentClassNameKey[];

export const friendsWorldClassNameKeyMap = {
  "키네시스": "kinesis",
} as const;

export type FriendsWorldClassNameKey = (typeof friendsWorldClassNameKeyMap)[FriendsWorldClassName];
export const friendsWorldClassNameKeys = Object.values(friendsWorldClassNameKeyMap) as FriendsWorldClassNameKey[];

export const lefClassNameKeyMap = {
  "아델": "adele",
  "일리움": "illium",
  "칼리": "khali",
  "아크": "ark",
} as const;

export type LefClassNameKey = (typeof lefClassNameKeyMap)[LefClassName];
export const lefClassNameKeys = Object.values(lefClassNameKeyMap) as LefClassNameKey[];

export const animaClassNameKeyMap = {
  "렌": "len",
  "라라": "lara",
  "호영": "hoyoung",
} as const;

export type AnimaClassNameKey = (typeof animaClassNameKeyMap)[AnimaClassName];
export const animaClassNameKeys = Object.values(animaClassNameKeyMap) as AnimaClassNameKey[];

