type ClassName = string;
type Affiliation = string;

type ClassTreeNode = {
  className: ClassName;
  children?: readonly ClassTreeNode[];
};

type AffiliationClassTree = {
  affiliation: Affiliation;
  roots: readonly ClassTreeNode[];
};

type CreateGeneratedTaxonomyClassNameSourceOptions = {
  allClassKeyMap: Record<string, string>;
  classTree: readonly AffiliationClassTree[];
};

const baseClassNames = new Set<ClassName>(['초보자', '노블레스', '시티즌']);
const demonClassNameSet = new Set<ClassName>(['데몬슬레이어', '데몬어벤져']);

const affiliationConstNameMap: Record<string, string> = {
  모험가: 'adventurer',
  '시그너스 기사단': 'cygnus',
  영웅: 'heroes',
  레지스탕스: 'resistance',
  노바: 'nova',
  초월자: 'transcendent',
  '프렌즈 월드': 'friendsWorld',
  레프: 'lef',
  아니마: 'anima',
};

function flattenClassNames(nodes: readonly ClassTreeNode[]): ClassName[] {
  const classNames: ClassName[] = [];

  for (const node of nodes) {
    classNames.push(node.className);

    if (node.children) {
      classNames.push(...flattenClassNames(node.children));
    }
  }

  return classNames;
}

function unique<T>(values: readonly T[]): T[] {
  return [...new Set(values)];
}

function excludeBaseClassNames(classNames: readonly ClassName[]): ClassName[] {
  return classNames.filter((className) => !baseClassNames.has(className));
}

function toClassKeyMap(classNames: readonly ClassName[], allClassKeyMap: Record<string, string>): Record<string, string> {
  return Object.fromEntries(classNames.map((className) => [className, allClassKeyMap[className] ?? className]));
}

function toPascalCase(value: string): string {
  return value
    .split(/[-_]/g)
    .filter(Boolean)
    .map((word) => `${word[0]?.toUpperCase() ?? ''}${word.slice(1)}`)
    .join('');
}

function stringifyConstObject(name: string, value: Record<string, string>): string {
  const entries = Object.entries(value)
    .map(([key, entryValue]) => `  ${JSON.stringify(key)}: ${JSON.stringify(entryValue)},`)
    .join('\n');

  return `export const ${name} = {\n${entries}\n} as const;`;
}

function createClassKeyMapBlock(namePrefix: string, classNames: readonly ClassName[], allClassKeyMap: Record<string, string>): string {
  const pascalName = toPascalCase(namePrefix);
  const keyMapName = `${namePrefix}ClassKeyMap`;
  const classNameType = `${pascalName}ClassName`;
  const classKeyType = `${pascalName}ClassKey`;
  const classNamesName = `${namePrefix}ClassNames`;
  const classKeysName = `${namePrefix}ClassKeys`;

  return [
    stringifyConstObject(keyMapName, toClassKeyMap(classNames, allClassKeyMap)),
    '',
    `export type ${classNameType} = keyof typeof ${keyMapName};`,
    `export type ${classKeyType} = (typeof ${keyMapName})[${classNameType}];`,
    `export const ${classNamesName} = Object.keys(${keyMapName}) as ${classNameType}[];`,
    `export const ${classKeysName} = Object.values(${keyMapName}) as ${classKeyType}[];`,
  ].join('\n');
}

export function createGeneratedTaxonomyAffiliationClassSource({ allClassKeyMap, classTree }: CreateGeneratedTaxonomyClassNameSourceOptions): string {
  const blocks: string[] = [
    '/* eslint-disable */',
    '// This file is generated by packages/generator/scripts/generate-taxonomy-affiliation-class.mjs.',
    '',
  ];

  for (const { affiliation, roots } of classTree) {
    const classNames = excludeBaseClassNames(unique(flattenClassNames(roots)));
    const prefix = affiliationConstNameMap[affiliation] ?? affiliation;

    blocks.push(createClassKeyMapBlock(prefix, classNames, allClassKeyMap), '');
  }

  const resistanceClassNames = excludeBaseClassNames(unique(flattenClassNames(classTree.find((tree) => tree.affiliation === '레지스탕스')?.roots ?? [])));
  const demonClassNames = resistanceClassNames.filter((className) => demonClassNameSet.has(className));
  const resistanceSkillClassNames = resistanceClassNames.filter((className) => !demonClassNameSet.has(className));

  blocks.push(createClassKeyMapBlock('demon', demonClassNames, allClassKeyMap), '');
  blocks.push(createClassKeyMapBlock('resistanceSkill', resistanceSkillClassNames, allClassKeyMap), '');

  return `${blocks.join('\n')}\n`;
}
