import type { CubePotentialOptionWeightMap } from './builder';

export const blackRedCubeWeaponOptionWeightMap = {
  normal: [
    { optionKey: 'str', value: 6, unit: 'flat', weight: 3 },
    { optionKey: 'dex', value: 6, unit: 'flat', weight: 3 },
    { optionKey: 'int', value: 6, unit: 'flat', weight: 3 },
    { optionKey: 'luk', value: 6, unit: 'flat', weight: 3 },
    { optionKey: 'max-hp', value: 60, unit: 'flat', weight: 3 },
    { optionKey: 'max-mp', value: 60, unit: 'flat', weight: 3 },
    { optionKey: 'attack-power', value: 6, unit: 'flat', weight: 2 },
    { optionKey: 'magic-power', value: 6, unit: 'flat', weight: 2 },
  ],
  rare: [
    { optionKey: 'str', value: 12, unit: 'flat', weight: 3 },
    { optionKey: 'dex', value: 12, unit: 'flat', weight: 3 },
    { optionKey: 'int', value: 12, unit: 'flat', weight: 3 },
    { optionKey: 'luk', value: 12, unit: 'flat', weight: 3 },
    { optionKey: 'max-hp', value: 120, unit: 'flat', weight: 3 },
    { optionKey: 'max-mp', value: 120, unit: 'flat', weight: 3 },
    { optionKey: 'attack-power', value: 12, unit: 'flat', weight: 2 },
    { optionKey: 'magic-power', value: 12, unit: 'flat', weight: 2 },
    { optionKey: 'str-rate', value: 3, unit: 'percent', weight: 3 },
    { optionKey: 'dex-rate', value: 3, unit: 'percent', weight: 3 },
    { optionKey: 'int-rate', value: 3, unit: 'percent', weight: 3 },
    { optionKey: 'luk-rate', value: 3, unit: 'percent', weight: 3 },
    { optionKey: 'attack-power-rate', value: 3, unit: 'percent', weight: 1 },
    { optionKey: 'magic-power-rate', value: 3, unit: 'percent', weight: 1 },
    { optionKey: 'critical-rate', value: 4, unit: 'percent', weight: 1 },
    { optionKey: 'damage', value: 3, unit: 'percent', weight: 1 },
    { optionKey: 'all-stat', value: 5, unit: 'flat', weight: 2 },
    { optionKey: 'attack-trigger-hp-recovery', value: 240, unit: 'flat', chancePercent: 20, weight: 1 },
    { optionKey: 'attack-trigger-mp-recovery', value: 120, unit: 'flat', chancePercent: 20, weight: 1 },
    { optionKey: 'attack-trigger-debuff-poison', value: 6, unit: 'level', chancePercent: 20, weight: 1 },
    { optionKey: 'attack-trigger-debuff-stun', value: 2, unit: 'level', chancePercent: 10, weight: 1 },
    { optionKey: 'attack-trigger-debuff-slow', value: 2, unit: 'level', chancePercent: 20, weight: 1 },
    { optionKey: 'attack-trigger-debuff-darkness', value: 3, unit: 'level', chancePercent: 20, weight: 1 },
    { optionKey: 'attack-trigger-debuff-freeze', value: 2, unit: 'level', chancePercent: 10, weight: 1 },
    { optionKey: 'attack-trigger-debuff-seal', value: 2, unit: 'level', chancePercent: 10, weight: 1 },
    { optionKey: 'ignore-monster-armor', value: 15, unit: 'percent', weight: 1 },
  ],
  epic: [
    { optionKey: 'str-rate', value: 6, unit: 'percent', weight: 2.5 },
    { optionKey: 'dex-rate', value: 6, unit: 'percent', weight: 2.5 },
    { optionKey: 'int-rate', value: 6, unit: 'percent', weight: 2.5 },
    { optionKey: 'luk-rate', value: 6, unit: 'percent', weight: 2.5 },
    { optionKey: 'max-hp-rate', value: 6, unit: 'percent', weight: 2.5 },
    { optionKey: 'max-mp-rate', value: 6, unit: 'percent', weight: 2.5 },
    { optionKey: 'attack-power-rate', value: 6, unit: 'percent', weight: 1 },
    { optionKey: 'magic-power-rate', value: 6, unit: 'percent', weight: 1 },
    { optionKey: 'critical-rate', value: 8, unit: 'percent', weight: 1 },
    { optionKey: 'damage', value: 6, unit: 'percent', weight: 1 },
    { optionKey: 'all-stat-rate', value: 3, unit: 'percent', weight: 1 },
    { optionKey: 'attack-trigger-hp-recovery', value: 360, unit: 'flat', chancePercent: 20, weight: 1 },
    { optionKey: 'attack-trigger-mp-recovery', value: 180, unit: 'flat', chancePercent: 20, weight: 1 },
    { optionKey: 'ignore-monster-armor', value: 15, unit: 'percent', weight: 1 },
  ],
  unique: [
    { optionKey: 'str-rate', value: 9, unit: 'percent', weight: 5 },
    { optionKey: 'dex-rate', value: 9, unit: 'percent', weight: 5 },
    { optionKey: 'int-rate', value: 9, unit: 'percent', weight: 5 },
    { optionKey: 'luk-rate', value: 9, unit: 'percent', weight: 5 },
    { optionKey: 'attack-power-rate', value: 9, unit: 'percent', weight: 3 },
    { optionKey: 'magic-power-rate', value: 9, unit: 'percent', weight: 3 },
    { optionKey: 'critical-rate', value: 9, unit: 'percent', weight: 4 },
    { optionKey: 'damage', value: 9, unit: 'percent', weight: 3 },
    { optionKey: 'all-stat-rate', value: 6, unit: 'percent', weight: 4 },
    { optionKey: 'ignore-monster-armor', value: 30, unit: 'percent', weight: 3 },
    { optionKey: 'boss-damage', value: 30, unit: 'percent', weight: 3 },
  ],
  legendary: [
    { optionKey: 'str-rate', value: 12, unit: 'percent', weight: 2 },
    { optionKey: 'dex-rate', value: 12, unit: 'percent', weight: 2 },
    { optionKey: 'int-rate', value: 12, unit: 'percent', weight: 2 },
    { optionKey: 'luk-rate', value: 12, unit: 'percent', weight: 2 },
    { optionKey: 'attack-power-rate', value: 12, unit: 'percent', weight: 1 },
    { optionKey: 'magic-power-rate', value: 12, unit: 'percent', weight: 1 },
    { optionKey: 'critical-rate', value: 12, unit: 'percent', weight: 1 },
    { optionKey: 'damage', value: 12, unit: 'percent', weight: 1 },
    { optionKey: 'all-stat-rate', value: 9, unit: 'percent', weight: 1.5 },
    { optionKey: 'attack-power', value: 32, unit: 'flat', weight: 1 },
    { optionKey: 'magic-power', value: 32, unit: 'flat', weight: 1 },
    { optionKey: 'ignore-monster-armor', value: 35, unit: 'percent', weight: 1 },
    { optionKey: 'ignore-monster-armor', value: 40, unit: 'percent', weight: 1 },
    { optionKey: 'boss-damage', value: 35, unit: 'percent', weight: 2 },
    { optionKey: 'boss-damage', value: 40, unit: 'percent', weight: 1 },
  ],
} as const satisfies CubePotentialOptionWeightMap;

export const silverGoldCubeWeaponOptionWeightMap = {
  normal: [
    { optionKey: 'str', value: 6, unit: 'flat', weight: 2 },
    { optionKey: 'dex', value: 6, unit: 'flat', weight: 2 },
    { optionKey: 'int', value: 6, unit: 'flat', weight: 2 },
    { optionKey: 'luk', value: 6, unit: 'flat', weight: 2 },
    { optionKey: 'max-hp', value: 60, unit: 'flat', weight: 3 },
    { optionKey: 'max-mp', value: 60, unit: 'flat', weight: 3 },
    { optionKey: 'attack-power', value: 6, unit: 'flat', weight: 1 },
    { optionKey: 'magic-power', value: 6, unit: 'flat', weight: 1 },
  ],
  rare: [
    { optionKey: 'str', value: 12, unit: 'flat', weight: 2 },
    { optionKey: 'dex', value: 12, unit: 'flat', weight: 2 },
    { optionKey: 'int', value: 12, unit: 'flat', weight: 2 },
    { optionKey: 'luk', value: 12, unit: 'flat', weight: 2 },
    { optionKey: 'max-hp', value: 120, unit: 'flat', weight: 3 },
    { optionKey: 'max-mp', value: 120, unit: 'flat', weight: 3 },
    { optionKey: 'attack-power', value: 12, unit: 'flat', weight: 2 },
    { optionKey: 'magic-power', value: 12, unit: 'flat', weight: 2 },
    { optionKey: 'str-rate', value: 3, unit: 'percent', weight: 2 },
    { optionKey: 'dex-rate', value: 3, unit: 'percent', weight: 2 },
    { optionKey: 'int-rate', value: 3, unit: 'percent', weight: 2 },
    { optionKey: 'luk-rate', value: 3, unit: 'percent', weight: 2 },
    { optionKey: 'attack-power-rate', value: 3, unit: 'percent', weight: 1 },
    { optionKey: 'magic-power-rate', value: 3, unit: 'percent', weight: 1 },
    { optionKey: 'critical-rate', value: 4, unit: 'percent', weight: 1 },
    { optionKey: 'damage', value: 3, unit: 'percent', weight: 1 },
    { optionKey: 'all-stat', value: 5, unit: 'flat', weight: 2 },
    { optionKey: 'attack-trigger-hp-recovery', value: 32, unit: 'flat', chancePercent: 3, weight: 3 },
    { optionKey: 'attack-trigger-mp-recovery', value: 32, unit: 'flat', chancePercent: 3, weight: 3 },
    { optionKey: 'attack-trigger-debuff-poison', value: 6, unit: 'level', chancePercent: 10, weight: 3 },
    { optionKey: 'attack-trigger-debuff-stun', value: 2, unit: 'level', chancePercent: 5, weight: 3 },
    { optionKey: 'attack-trigger-debuff-slow', value: 2, unit: 'level', chancePercent: 10, weight: 3 },
    { optionKey: 'attack-trigger-debuff-darkness', value: 3, unit: 'level', chancePercent: 10, weight: 3 },
    { optionKey: 'attack-trigger-debuff-freeze', value: 2, unit: 'level', chancePercent: 5, weight: 3 },
    { optionKey: 'attack-trigger-debuff-seal', value: 2, unit: 'level', chancePercent: 5, weight: 3 },
    { optionKey: 'ignore-monster-armor', value: 15, unit: 'percent', weight: 1 },
  ],
  epic: [
    { optionKey: 'str-rate', value: 6, unit: 'percent', weight: 2 },
    { optionKey: 'dex-rate', value: 6, unit: 'percent', weight: 2 },
    { optionKey: 'int-rate', value: 6, unit: 'percent', weight: 2 },
    { optionKey: 'luk-rate', value: 6, unit: 'percent', weight: 2 },
    { optionKey: 'max-hp-rate', value: 6, unit: 'percent', weight: 3 },
    { optionKey: 'max-mp-rate', value: 6, unit: 'percent', weight: 3 },
    { optionKey: 'attack-power-rate', value: 6, unit: 'percent', weight: 1 },
    { optionKey: 'magic-power-rate', value: 6, unit: 'percent', weight: 1 },
    { optionKey: 'critical-rate', value: 8, unit: 'percent', weight: 1 },
    { optionKey: 'damage', value: 6, unit: 'percent', weight: 1 },
    { optionKey: 'all-stat-rate', value: 3, unit: 'percent', weight: 1 },
    { optionKey: 'attack-trigger-hp-recovery', value: 53, unit: 'flat', chancePercent: 3, weight: 3 },
    { optionKey: 'attack-trigger-mp-recovery', value: 53, unit: 'flat', chancePercent: 3, weight: 3 },
    { optionKey: 'ignore-monster-armor', value: 15, unit: 'percent', weight: 1 },
  ],
  unique: [
    { optionKey: 'str-rate', value: 9, unit: 'percent', weight: 2 },
    { optionKey: 'dex-rate', value: 9, unit: 'percent', weight: 2 },
    { optionKey: 'int-rate', value: 9, unit: 'percent', weight: 2 },
    { optionKey: 'luk-rate', value: 9, unit: 'percent', weight: 2 },
    { optionKey: 'attack-power-rate', value: 9, unit: 'percent', weight: 1 },
    { optionKey: 'magic-power-rate', value: 9, unit: 'percent', weight: 1 },
    { optionKey: 'critical-rate', value: 9, unit: 'percent', weight: 1 },
    { optionKey: 'damage', value: 9, unit: 'percent', weight: 1 },
    { optionKey: 'all-stat-rate', value: 6, unit: 'percent', weight: 1 },
    { optionKey: 'ignore-monster-armor', value: 30, unit: 'percent', weight: 1 },
    { optionKey: 'boss-damage', value: 30, unit: 'percent', weight: 1 },
  ],
  legendary: [
    { optionKey: 'str-rate', value: 12, unit: 'percent', weight: 4 },
    { optionKey: 'dex-rate', value: 12, unit: 'percent', weight: 4 },
    { optionKey: 'int-rate', value: 12, unit: 'percent', weight: 4 },
    { optionKey: 'luk-rate', value: 12, unit: 'percent', weight: 4 },
    { optionKey: 'attack-power-rate', value: 12, unit: 'percent', weight: 2 },
    { optionKey: 'magic-power-rate', value: 12, unit: 'percent', weight: 2 },
    { optionKey: 'critical-rate', value: 12, unit: 'percent', weight: 2 },
    { optionKey: 'damage', value: 12, unit: 'percent', weight: 2 },
    { optionKey: 'all-stat-rate', value: 9, unit: 'percent', weight: 4 },
    { optionKey: 'ignore-monster-armor', value: 35, unit: 'percent', weight: 2 },
    { optionKey: 'ignore-monster-armor', value: 40, unit: 'percent', weight: 1 },
    { optionKey: 'boss-damage', value: 35, unit: 'percent', weight: 4 },
    { optionKey: 'boss-damage', value: 40, unit: 'percent', weight: 1 },
  ],
} as const satisfies CubePotentialOptionWeightMap;
