import type { ErdColumn, ErdDocument, ErdEntity, ErdRelation } from './types';

function toSqlType(column: ErdColumn) {
  if (column.type === 'ENUM') {
    return 'TEXT';
  }

  return column.type || 'TEXT';
}

function escapeSqlStringLiteral(value: string) {
  return value.replaceAll("'", "''");
}

function isRawDefaultValue(value: string) {
  const trimmed = value.trim();

  if (trimmed === '') return false;
  if (/^(true|false|null)$/i.test(trimmed)) return true;
  if (/^[+-]?\d+(\.\d+)?$/.test(trimmed)) return true;
  if (/^(current_timestamp|current_date|current_time|localtimestamp|localtime)$/i.test(trimmed)) return true;
  if (trimmed.includes('(') || trimmed.includes(')')) return true;
  if (trimmed.includes('::')) return true;
  if (/[+\-*/]/.test(trimmed) && /\d/.test(trimmed)) return true;

  return false;
}

function toDefaultClause(value: string) {
  if (isRawDefaultValue(value)) {
    return `DEFAULT ${value.trim()}`;
  }

  return `DEFAULT '${escapeSqlStringLiteral(value)}'`;
}

function buildColumnLine(column: ErdColumn) {
  const chunks = [`  ${column.name} ${toSqlType(column)}`];

  if (!column.isAllowNull) {
    chunks.push('NOT NULL');
  }

  if (column.defaultValue) {
    if (column.defaultValue === 'GENERATED BY DEFAULT AS IDENTITY') {
      chunks.push(column.defaultValue);
    } else {
      chunks.push(toDefaultClause(column.defaultValue));
    }
  }

  if (column.keyType === 'pk') {
    chunks.push('PRIMARY KEY');
  }

  if (column.isUnique) {
    chunks.push('UNIQUE');
  }

  return {
    comment: column.comment ? ` -- ${column.comment}` : '',
    definition: chunks.join(' '),
  };
}

function buildForeignKeyConstraint(entity: ErdEntity, relation: ErdRelation, document: ErdDocument) {
  if (relation.toEntityId !== entity.id || !relation.toColumnId || !relation.fromEntityId || !relation.fromColumnId) {
    return null;
  }

  const sourceEntity = document.entities.find((item) => item.id === relation.fromEntityId);
  const sourceColumn = sourceEntity?.columns.find((column) => column.id === relation.fromColumnId);
  const targetColumn = entity.columns.find((column) => column.id === relation.toColumnId);

  if (!sourceEntity || !sourceColumn || !targetColumn) return null;

  return `  CONSTRAINT ${entity.name}_${targetColumn.name}_fk FOREIGN KEY (${targetColumn.name}) REFERENCES ${sourceEntity.name} (${sourceColumn.name})`;
}

function buildCheckConstraint(entityName: string, column: ErdColumn) {
  if (column.type !== 'ENUM' || !column.enumValues.trim()) {
    return null;
  }

  const values = column.enumValues
    .split(',')
    .map((value) => value.trim())
    .filter(Boolean)
    .map((value) => `'${value}'`)
    .join(', ');

  return `  CONSTRAINT ${entityName}_${column.name}_check CHECK (${column.name} IN (${values}))`;
}

export function buildPostgresDDL(document: ErdDocument) {
  return document.entities
    .map((entity) => {
      const columnLines = entity.columns.map(buildColumnLine);
      const constraints = entity.columns
        .map((column) => buildCheckConstraint(entity.name, column))
        .filter((value): value is string => value !== null);
      const foreignKeys = document.relations
        .map((relation) => buildForeignKeyConstraint(entity, relation, document))
        .filter((value): value is string => value !== null);
      const lines = [
        ...columnLines.map((line) => ({ comment: line.comment, definition: line.definition })),
        ...constraints.map((line) => ({ comment: '', definition: line })),
        ...foreignKeys.map((line) => ({ comment: '', definition: line })),
      ].map((line, index, all) => `${line.definition}${index < all.length - 1 ? ',' : ''}${line.comment}`);

      const body = lines.join('\n');

      return `CREATE TABLE ${entity.name} (\n${body}\n);`;
    })
    .join('\n\n');
}
