import type { ErdDocument, ErdEntity, ErdRelationCardinality } from './types';

const STORAGE_KEY = 'erd-documents';
const DEFAULT_ENTITY_WIDTH = 420;
const DEFAULT_ENTITY_HEIGHT = 240;
const DEFAULT_ENTITY_COLOR = '#0f172a';

function normalizeEntity(entity: ErdEntity): ErdEntity {
  return {
    ...entity,
    color: entity.color ?? DEFAULT_ENTITY_COLOR,
    isUniqueColumnVisible: entity.isUniqueColumnVisible ?? false,
    size: entity.size ?? {
      width: DEFAULT_ENTITY_WIDTH,
      height: DEFAULT_ENTITY_HEIGHT,
    },
    columns: (entity.columns ?? []).map((column) => ({
      ...column,
      relationKeyType: column.relationKeyType ?? null,
      referencedEntityId: column.referencedEntityId ?? null,
      referencedColumnId: column.referencedColumnId ?? null,
      referencedRelationId: column.referencedRelationId ?? null,
    })),
  };
}

function normalizeRelations(relations: ErdDocument['relations']) {
  const normalizeCardinality = (value: unknown, fallback: ErdRelationCardinality): ErdRelationCardinality => {
    const allowed: ErdRelationCardinality[] = ['one', 'one-only', 'zero-or-one', 'many', 'zero-or-many', 'one-or-many'];
    return typeof value === 'string' && allowed.includes(value as ErdRelationCardinality) ? (value as ErdRelationCardinality) : fallback;
  };

  return (relations ?? []).map((relation) => {
    const legacyRelation = relation as typeof relation & { kind?: unknown };

    return {
      ...relation,
      fromColumnId: relation.fromColumnId ?? null,
      toColumnId: relation.toColumnId ?? null,
      fromCardinality: normalizeCardinality('fromCardinality' in relation ? relation.fromCardinality : null, 'one'),
      toCardinality: normalizeCardinality('toCardinality' in relation ? relation.toCardinality : legacyRelation.kind, 'zero-or-many'),
      relationshipType: 'relationshipType' in relation && relation.relationshipType ? relation.relationshipType : 'non-identifying',
    };
  });
}

function createUsersEntity(): ErdEntity {
  return {
    id: 'entity-users',
    name: 'users',
    comment: '사용자 기본 테이블',
    color: DEFAULT_ENTITY_COLOR,
    isUniqueColumnVisible: false,
    position: {
      x: 120,
      y: 96,
    },
    size: {
      width: 460,
      height: 280,
    },
    columns: [
      {
        id: 'col-user-id',
        keyType: 'pk',
        relationKeyType: null,
        referencedEntityId: null,
        referencedColumnId: null,
        referencedRelationId: null,
        name: 'user_id',
        pName: '사용자 ID',
        domain: 'ID',
        type: 'BIGINT',
        enumValues: '',
        isAllowNull: false,
        isUnique: false,
        defaultValue: 'GENERATED BY DEFAULT AS IDENTITY',
        comment: 'PRIMARY KEY',
      },
      {
        id: 'col-email',
        keyType: null,
        relationKeyType: null,
        referencedEntityId: null,
        referencedColumnId: null,
        referencedRelationId: null,
        name: 'email',
        pName: '이메일',
        domain: 'EMAIL',
        type: 'VARCHAR(255)',
        enumValues: '',
        isAllowNull: true,
        isUnique: true,
        defaultValue: '',
        comment: 'UNIQUE',
      },
      {
        id: 'col-password',
        keyType: null,
        relationKeyType: null,
        referencedEntityId: null,
        referencedColumnId: null,
        referencedRelationId: null,
        name: 'password',
        pName: '비밀번호',
        domain: 'PASSWORD_HASH',
        type: 'VARCHAR(60)',
        enumValues: '',
        isAllowNull: false,
        isUnique: false,
        defaultValue: '',
        comment: 'bcrypt=60',
      },
      {
        id: 'col-status',
        keyType: null,
        relationKeyType: null,
        referencedEntityId: null,
        referencedColumnId: null,
        referencedRelationId: null,
        name: 'status',
        pName: '상태',
        domain: 'USER_STATUS',
        type: 'ENUM',
        enumValues: 'ACTIVE,INACTIVE,BLOCKED',
        isAllowNull: false,
        isUnique: false,
        defaultValue: 'ACTIVE',
        comment: '사용자 상태',
      },
    ],
  };
}

function createSeedDocuments(): ErdDocument[] {
  return [
    {
      id: 'erd-sample',
      thumbnail: null,
      title: 'Sample ERD',
      updatedAt: new Date().toISOString(),
      entities: [createUsersEntity()],
      memos: [
        {
          id: 'memo-1',
          title: '메모',
          content: 'ENUM 기본 전략은 TEXT + CHECK',
        },
      ],
      relations: [],
    },
  ];
}

export function loadErdDocuments(): ErdDocument[] {
  const raw = window.localStorage.getItem(STORAGE_KEY);
  if (!raw) {
    const seed = createSeedDocuments();
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(seed));
    return seed;
  }

  try {
    const parsed = JSON.parse(raw) as ErdDocument[];
    return Array.isArray(parsed)
      ? parsed.map((document) => ({
          ...document,
          thumbnail: document.thumbnail ?? null,
          entities: Array.isArray(document.entities) ? document.entities.map(normalizeEntity) : [],
          relations: normalizeRelations(document.relations),
        }))
      : createSeedDocuments();
  } catch {
    return createSeedDocuments();
  }
}

export function saveErdDocuments(documents: ErdDocument[]) {
  window.localStorage.setItem(STORAGE_KEY, JSON.stringify(documents));
}

export function createEmptyDocument(): ErdDocument {
  return {
    id: crypto.randomUUID(),
    thumbnail: null,
    title: 'Untitled ERD',
    updatedAt: new Date().toISOString(),
    entities: [],
    memos: [],
    relations: [],
  };
}

export function removeErdDocument(documentId: string) {
  const documents = loadErdDocuments().filter((document) => document.id !== documentId);
  saveErdDocuments(documents);
  return documents;
}

export function updateErdDocumentThumbnail(documentId: string, thumbnail: string | null) {
  const documents = loadErdDocuments().map((document) =>
    document.id === documentId
      ? {
          ...document,
          thumbnail,
          updatedAt: new Date().toISOString(),
        }
      : document,
  );
  saveErdDocuments(documents);
  return documents;
}

export function duplicateErdDocument(documentId: string) {
  const documents = loadErdDocuments();
  const source = documents.find((document) => document.id === documentId);

  if (!source) return null;

  const entityIdMap = new Map<string, string>();
  const columnIdMap = new Map<string, string>();

  const duplicatedEntities = source.entities.map((entity) => {
    const nextEntityId = crypto.randomUUID();
    entityIdMap.set(entity.id, nextEntityId);

    return {
      ...entity,
      id: nextEntityId,
      columns: entity.columns.map((column) => {
        const nextColumnId = crypto.randomUUID();
        columnIdMap.set(column.id, nextColumnId);
        return {
          ...column,
          id: nextColumnId,
        };
      }),
    };
  });

  const duplicatedDocument: ErdDocument = {
    ...source,
    id: crypto.randomUUID(),
    thumbnail: source.thumbnail,
    title: `${source.title} Copy`,
    updatedAt: new Date().toISOString(),
    entities: duplicatedEntities,
    memos: source.memos.map((memo) => ({
      ...memo,
      id: crypto.randomUUID(),
    })),
    relations: source.relations.map((relation) => ({
      ...relation,
      id: crypto.randomUUID(),
      fromEntityId: relation.fromEntityId ? (entityIdMap.get(relation.fromEntityId) ?? relation.fromEntityId) : relation.fromEntityId,
      fromColumnId: relation.fromColumnId ? (columnIdMap.get(relation.fromColumnId) ?? relation.fromColumnId) : relation.fromColumnId,
      toEntityId: relation.toEntityId ? (entityIdMap.get(relation.toEntityId) ?? relation.toEntityId) : relation.toEntityId,
      toColumnId: relation.toColumnId ? (columnIdMap.get(relation.toColumnId) ?? relation.toColumnId) : relation.toColumnId,
    })),
  };

  saveErdDocuments([duplicatedDocument, ...documents]);
  return duplicatedDocument;
}
